### PR TITLE
Update centos-8 repositories

### PR DESCRIPTION
**Pull request by jrusz**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by ondrejbudai — APPROVED** [review]
Awesome, thanks for the quick fix!

**Comment by ondrejbudai** [comment]
@thozza Did you already regenerate cs8 manifests? If you did, you might have to do it once more, sorry. :(

**Comment by jrusz** [comment]
@ondrejbudai I'm afraid it might not be as quick... There is some problem with booting centos-8 vm in azure
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1575477233
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1575477266

**Comment by jrusz** [comment]
Yeah ok, let's unblock CI first and solve this later.

**Review by ondrejbudai — APPROVED** [review]

**Comment by jrusz** [comment]
Ugh, of course the longest running task failed because we want to get this merged ASAP https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1575761535 ... Restarting, should be unrelated to this change.

**Comment by ondrejbudai** [comment]
Force-merging, the only failed test is for RHEL 8.5, this PR has nothing in common with it.

**Pull request merged**
