### PR TITLE
test/README: describe vendoring modified images repo

### PR DESCRIPTION
**Pull request by achilleas-k**
Add instructions for how to test an updated osbuild/images repo against osbuild-composer and update test manifest generation instructions.

### CODE REVIEW

**Comment by bcl** [comment]
This should say something about making the replace+vendor change in a separate commit, and not merging it with the replace in place :)

**Comment by achilleas-k** [comment]
> This should say something about making the replace+vendor change in a separate commit, and not merging it with the replace in place :)

Good idea.  Updated.  Let me know what you think.

**Review by bcl — APPROVED** [review]
Looks good!

**Comment by ondrejbudai** [comment]
Just a doc update.

**Pull request merged**
