### PR TITLE
distro/rhel90: re-include nss-altfiles for edge

### PR DESCRIPTION
**Pull request by gicmo**
The `nss-altfiles` package is actually needed for OSTree based systems, since in those the user/groups database is located in the /usr/lib directory (in addition to /etc). It was removed because it was not available in RHEL 9 (rhbz#1916260). This has been fixed, so we need to re-include the package.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by achilleas-k — DISMISSED** [review]
Perfect, thank you!

**Comment by henrywang** [comment]
@gicmo I'll run the test locally. If everything works, I'll update test in this PR.

**Review by ondrejbudai — DISMISSED** [review]
We need an exception for this, I'm blocking this for now.

**Comment by henrywang** [comment]
@gicmo I just push a commit to make `osbuild-composer-worker` depend on `osbuild-35` instead of `osbuild-36`. If everything works, you can remove this commit before merge. Thanks.

**Comment by henrywang** [comment]
@gicmo @achilleas-k @ondrejbudai This PR works in my local test env.

**Review by teg — APPROVED** [review]

**Comment by jrusz** [comment]
@ondrejbudai we got exception+ in bz#2005315

**Comment by ondrejbudai** [comment]
@gicmo can you please rebase?

**Comment by ondrejbudai** [comment]
We should also regenerate the test cases for this, @thozza can you help? It needs some coordination with #1810, I think that we should firstly merge this, and then continue with #1810

**Comment by thozza** [comment]
I'm regenerating image test cases...

**Comment by ondrejbudai** [comment]
Hmm, I guess we need to remove the second commit. We don't want to lower the osbuild dependency. Everything will be fine though when we will backport this change to the right branch.

**Comment by ondrejbudai** [comment]
I force-pushed to remove the second commit.

**Comment by thozza** [comment]
@ondrejbudai can you please remove your request for changes, so that we can merge this PR? The exception has been granted, the CI passed. This one should be good to go...

**Review by thozza — APPROVED** [review]

**Pull request merged**
