### PR TITLE
Extend scheduled cloud cleaner to GCP

### PR DESCRIPTION
**Pull request by jabia99**
Scheduled cloud cleaner only works in azure and aws. This PR extends this functionality to GCP. To do so, we have to tag every gcp testing resource with "gitlab-ci-test". 

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by jabia99** [comment]
Link to cloud cleaner logs: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1877341904

**Review by jrusz — COMMENTED** [review]
IMO it looks good, I'm just wondering how did you test it? I would expect you created a debug PR with only gcp jobs to trigger CI and then cancel it somewhere in between or let it fail and run the cleaner afterwards. In your test run I can see just a bunch of images removed... 

Also since I have basically no experience with GCP, @thozza would you mind giving it a quick look as well please?

**Comment by jabia99** [comment]
> IMO it looks good, I'm just wondering how did you test it? I would expect you created a debug PR with only gcp jobs to trigger CI and then cancel it somewhere in between or let it fail and run the cleaner afterwards. In your test run I can see just a bunch of images removed...

To test it, I removed the GCP cleanup function on api.sh. I also had to set scheduled cloud cleaner to run every time.

**Comment by jabia99** [comment]
I don't know how GCP works exactly, but I think the only resources that could be left behind would be the ones on GCP Cloud Storage. There's not an easy way to tag these and there's already functions to clean the storage ([cloudbuild](https://github.com/osbuild/osbuild-composer/blob/4da7ec68a04261c51ec444c5512d7e0dcbb9e38f/internal/cloud/gcp/cloudbuild.go#L94)) So I'll go back to it if we see a lot of resources on Cloud Storage

**Comment by jrusz** [comment]
Did a bit of side testing of my own, these are the logs https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1882403910 It looks like it's working fine.

**Comment by jabia99** [comment]
> Did a bit of side testing of my own, these are the logs https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1882403910 It looks like it's working fine.

Thanks a lot !

**Review by jrusz — APPROVED** [review]
LGTM.

**Pull request merged**
