### PR TITLE
Remove image info from all test manifests

### PR DESCRIPTION
**Pull request by achilleas-k**
We never generated it for the newest distro versions and we don't test
it on any of the old ones.

It's better this way.

I used `cmd/gen-manifests` to generate these.  The order of elements in the compose request for some manifests has changed.  The order is now fixed, based on the struct defined (and serialised) in the `gen-manifests` tool, rather than the order they appear in the `format-request-map.json`, which `generate-test-cases` retains.

### CODE REVIEW

**Comment by teg** [comment]
Are these now tested elsewhere?

**Comment by gicmo** [comment]
> Are these now tested elsewhere?

It tested via the diff-manifest check that will post the warning message on PRs that change manifests, like this: https://github.com/osbuild/osbuild-composer/pull/2812#pullrequestreview-1033356663

**Comment by ondrejbudai** [comment]
Note that this actually doesn't fix the failing tests in rawhide.

**Comment by achilleas-k** [comment]
> > Note that this actually doesn't fix the failing tests in rawhide.
> 
> We need the remaining two commits from [main...achilleas-k:osbuild-composer:sort-fstab](https://github.com/osbuild/osbuild-composer/compare/main...achilleas-k:osbuild-composer:sort-fstab)

I didn't want to mix the two in the same PR in case a discussion starts about a better way to fix the sorting issue.

Feel free to add those commits here if you think it's alright or make a new PR out of them while I'm away.

**Review by thozza — APPROVED** [review]

**Review by gicmo — APPROVED** [review]
👍

**Pull request merged**
