### PR TITLE
Add support for RHEL 8.5

### PR DESCRIPTION
**Pull request by achilleas-k**
This pull request includes:

- [x] adequate testing for the new functionality or fixed issue: _basic testing of arch listing_
- [x] adequate documentation informing people about the change such as
  - [x] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news: _not needed_
  - [x] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/: _not needed_

Cherry-picked commits from #1351 that add support for RHEL 8.5 without any defined image types.

This adds the basic functions and types for defining RHEL 8.5 image types using the new v2 manifest schema of osbuild.

Helper functions for defining stages and pipelines are added but are based on the Edge image types of the original PR, so they will probably need to be adjusted as new image types are added.

Each image type defines its own top-level `pipelines()` function now.  I kept the edge type pipeline definitions from the original previous PR, but they are "dead code" for now since they're not attached to any image type definition.  I can remove them from the PR and add them when the edge image types are added if anyone would prefer the distro definition to be cleaner.

With this PR, osbuild-composer can now run on RHEL 8.5, but since no image types are defined, there's not much you can do with it:
```
composer-cli --json compose types
{
    "types": null
}
```

### CODE REVIEW

**Comment by achilleas-k** [comment]
Unused functions are going to be a problem for golint, it seems.  I think the PR isn't very useful without them.  How do we feel about marking the new files with `// nolint: deadcode,unused` until the next PR?

**Comment by ondrejbudai** [comment]
I'm fine with that to unblock the effort. Maybe let's put the lint change into one commit so we can simply revert?

**Comment by achilleas-k** [comment]
Rebased on main.

**Review by ondrejbudai — APPROVED** [review]
lgtm! thanks!

**Comment by ondrejbudai** [comment]
(I restarted the tests)

**Pull request merged**
