### PR TITLE
image-tests: fix hostname typo in customizations

### PR DESCRIPTION
**Pull request by achilleas-k**
This pull request includes:

- [x] adequate testing for the new functionality or fixed issue
- [x] adequate documentation informing people about the change

The test case generation script contained a typo in the blueprint
customizations dictionary: "hosname" instead of "hostname".

Fixed typo and regenerated relevant test cases.

### CODE REVIEW

**Review by gicmo — APPROVED** [review]
👍

**Comment by gicmo** [comment]
Shoutout to #1190 so that this doesn't happen.

**Comment by achilleas-k** [comment]
Tests are failing because the hostname in the `image-info` of the test-cases wasn't added and the expected doesn't match the actual.  Not sure if the cases just need to be regenerated or if generation script might need changes.  Will check tomorrow and update accordingly.

**Comment by larskarlitski** [comment]
> This pull request includes:
> 
> * [ ]  adequate testing for the new functionality or fixed issue
>   * N/A: Test fix
> * [ ]  adequate documentation informing people about the change   
>   * N/A: Test fix

I would say *technically* N/A means you can check those boxes. 😉 

Nice catch!

**Comment by achilleas-k** [comment]
Edited.

**Review by teg — DISMISSED** [review]

**Comment by achilleas-k** [comment]
Regenerated test cases without the `--keep-image-info` to add the hostname to the expected output for the tests.  Tests _should_ pass now :crossed_fingers:.

**Review by ondrejbudai — APPROVED** [review]
Nice catch, thanks a lot for fixing it! :)

**Comment by ondrejbudai** [comment]
#1202 and #1196 appeared but otherwise, this is green! :green_heart:

**Pull request merged**
