### PR TITLE
internal/cloud/gcp/compute: Add SEV_SNP_CAPABLE Guest OS Feature

### PR DESCRIPTION
**Pull request by travier**
See: https://github.com/coreos/coreos-assembler/pull/3547
See: https://cloud.google.com/blog/products/identity-security/rsa-snp-vm-more-confidential
See: https://issues.redhat.com/browse/COS-2343

---

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by thozza** [comment]
Hi @travier.

Thanks a lot for the PR. Do you know if all RHEL-9 versions support SNP feature or if it is available only since some specific minor version of RHEL-9?

**Comment by travier** [comment]
> Do you know if all RHEL-9 versions support SNP feature or if it is available only since some specific minor version of RHEL-9?

Unfortunately I don't know. I've asked that to the folks that should know 🙂.

**Comment by travier** [comment]
From another chat, this is RHEL 9.2 only (potentially 9.1 but with lesser support): https://bugzilla.redhat.com/show_bug.cgi?id=2081424

**Review by ondrejbudai — APPROVED** [review]

**Comment by achilleas-k** [comment]
The installer test on RHEL 8.9 has been causing issues all around lately.  I did a rebase to help it along.

**Review by achilleas-k — APPROVED** [review]

**Pull request merged**
