### PR TITLE
Use Go 1.21 and update osbuild/images to v0.69.0

### PR DESCRIPTION
**Pull request by achilleas-k**
**go.mod: update to go v1.21**

Go 1.21 is included in all currently supported distro versions.
It is required by new updates to some of our dependencies, including
osbuild/images.

---

**go.mod: update osbuild/images to v0.69.0**

---

**weldr: update expected error messages**

Some depsolve-related error messages in osbuild/images changed.  Update
the expected error messages in our tests.

---

### CODE REVIEW

**Review by thozza — DISMISSED** [review]
Thanks!

**Review by croissanne — DISMISSED** [review]

**Comment by achilleas-k** [comment]
Tests failing with
```
✔️ Instance checking
Warning: Permanently added '129.213.58.207' (ECDSA) to the list of known hosts.
postgresql-10.23-4.module+el8.9.0+21317+d2c6bf8a.x86_64
dummy-1.0.0-0.noarch
System is subscribed.
Unregistering from: subscription.rhsm.redhat.com:443/subscription
System has been unregistered.
✔️ Checking custom directories and files
✔️ Checking custom repositories
✔️ Checking OpenSCAP customizations
cat: /usr/share/xml/osbuild-openscap-data/tailoring.xml: No such file or directory
```

@kingsleyzissou Is this related to recent oscap changes in osbuild/images?  Either [v0.68.0](https://github.com/osbuild/images/releases/tag/v0.68.0) or [v0.69.0](https://github.com/osbuild/images/releases/tag/v0.69.0)?

**Comment by kingsleyzissou** [comment]
> Tests failing with
> 
> ```
> ✔️ Instance checking
> Warning: Permanently added '129.213.58.207' (ECDSA) to the list of known hosts.
> postgresql-10.23-4.module+el8.9.0+21317+d2c6bf8a.x86_64
> dummy-1.0.0-0.noarch
> System is subscribed.
> Unregistering from: subscription.rhsm.redhat.com:443/subscription
> System has been unregistered.
> ✔️ Checking custom directories and files
> ✔️ Checking custom repositories
> ✔️ Checking OpenSCAP customizations
> cat: /usr/share/xml/osbuild-openscap-data/tailoring.xml: No such file or directory
> ```
> 
> @kingsleyzissou Is this related to recent oscap changes in osbuild/images? Either [v0.68.0](https://github.com/osbuild/images/releases/tag/v0.68.0) or [v0.69.0](https://github.com/osbuild/images/releases/tag/v0.69.0)?

Yeah, I fixed the test, but we moved the tailoring file to `/oscap_data` since all the osbuild stage saves all the artifacts there.

**Comment by achilleas-k** [comment]
> Yeah, I fixed the test (in images), but we moved the tailoring file to `/oscap_data` since all the osbuild stage saves all the artifacts there.

So is it enough to update the path in the test to look for the file in `/oscap_data`?  Just confirming before I start the CI runs again.

**Comment by kingsleyzissou** [comment]
> > Yeah, I fixed the test (in images), but we moved the tailoring file to `/oscap_data` since all the osbuild stage saves all the artifacts there.
> 
> So is it enough to update the path in the test to look for the file in `/oscap_data`? Just confirming before I start the CI runs again.

Yeah, as far as I can see we aren't running any scans. So changing it to `/oscap_data/tailoring.xml` should be enough. Here is the commit from images: https://github.com/osbuild/images/commit/7bd70d828ee7dc066a4c529cb2b8eb8f39ef0a06

**Review by kingsleyzissou — APPROVED** [review]

**Pull request merged**
