### PR TITLE
.gitlabci.yml: Add fedora-35 testing

### LINKED ISSUE #1802: Fedora 34 - Produces refs to fedora/33
**Describe the bug**
When building an iot-commit.tar from Fedora 34, the resulting tar file points to refs/heads/fedora/33/x86_64/iot

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`):
 ```
# cat /etc/os-release
NAME=Fedora
VERSION="34 (Server Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Server Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server

# cat /etc/fedora-release 
Fedora release 34 (Thirty Four)
```
 * osbuild-composer version (`rpm -qi osbuild-composer)`
```
Name        : osbuild-composer
Version     : 31
Release     : 1.fc34
Architecture: x86_64
```

**To Reproduce**
 * Generate a Commit.tar file 

**Expected behavior**
Should produce refs that point to fedora/34 (or whatever current version)

**Additional context**
Not sure if this is related, but this server was originally a Fedora33 server which I upgraded to Fedora34. Not sure if that is related in someway?

### PR DESCRIPTION
**Pull request by Gundersanne**
Add Fedora 35 testing in CI.

Enable F34 testing on AWS as there is nothing blocking it. F34 is not
yet supported on `rhos-01` as there is no runner definition.

Clean up some implementation aspects of the Fedora distro definition:
 - Do not have default Fedora distro version and use `fedora` as the package name in all places that use it, instead of `fedora33`.
 - Fix bugs when wrong (Fedora 33) values were returned by `OSTreeRef()` and `Releasever()` for newer Fedora releases.
 - Test Fedora 35 in package unit tests.
 - Add unit test for `OSTreeRef()` method.
 - Use architecture name constants from `distro` package, instead of string literals.
 - fix one issue in Fedora distro definition, which got revealed on Fedora 34 and newer due to dosfstools v4.2. 

Fix #1802

### CODE REVIEW

**Comment by thozza** [comment]
This PR is from my point of view 99% complete, but the `OSTree` test gets stuck on Fedora while running `virt-install`. Not sure how to debug this. @achilleas-k or @henrywang, I'm not sure if you ever encountered something like this, but wanted to ask you first, before I dig deeper into this.

**Comment by achilleas-k** [comment]
I've seen this in RHEL 8.6 and I don't know what to make of it.  I'm hoping Xiaofeng will know how to troubleshoot that.
https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/2042337610

**Comment by achilleas-k** [comment]
I just noticed that I made a mistake with the `$OS_VARIANT` variable in that other PR and fixed it.  If it's fixed that might mean it's a similar issue here.
I checked osinfo-db at the version being installed in the test and it's correct though: https://gitlab.com/libosinfo/osinfo-db/-/blob/47a08e15532cd6e655fe4aeff6da8d2cfbba206b/data/os/fedoraproject.org/fedora-35.xml.in

**Comment by thozza** [comment]
CI passed. We can ignore PackIt for now as it has an outage and it is not required for merge. I feel that I should not approve this on my own, since I modified this PR quite a bit... 🙄

**Review by gicmo — APPROVED** [review]
🙇

**Pull request merged**
