### PR TITLE
CI: Updates to ensure smoother running

### PR DESCRIPTION
**Pull request by jrusz**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by jrusz** [comment]
Changing the way how iostats are started and stopped because the previous way was causing CI jobs to hang on failure and wait for timeout. @atodorov could you please also take a look if you see any problem with this implementation?

**Review by atodorov — APPROVED** [review]

**Review by lavocatt — APPROVED** [review]
Thanks a lot for doing this.

**Comment by jrusz** [comment]
There was this line in almost every script which removes all traps on EXIT `trap - EXIT` which removed even the trap for the iostats and so even passing jobs got stuck. I removed the line I don't think it will cause any problems but let's see what the CI thinks.

**Review by lavocatt — APPROVED** [review]
Yes that makes sense to not remove traps in the scripts.

**Comment by jrusz** [comment]
This approach won't work that easily.. The `set-env-variables.sh` is not only called in `deploy.sh` so it starts and stop there, then does kinda the same in the test script and then each test script runs 'provision.sh' which also sources 'set-env-variables.sh' ... We'll have to put it somewhere else or figure out something different.

**Comment by jrusz** [comment]
I have a suggestion. Let's just remove iostats alltogether from the CI temporarily (just the `.gitlab-ci.yml`), merge this so people can work with CI reliably and then figure out where to put the iostats in a different PR. What do you think @lavocatt ?

**Comment by lavocatt** [comment]
Having everyone able to work effectively is more important. Let's figure out later a way to keep the iostat thing.

**Review by lavocatt — APPROVED** [review]

**Comment by jrusz** [comment]
There are some unrelated issues with ostree tests on 8.6 and 9.0 that also affect main, we'll have to solve those first or get approval to force merge this...

**Pull request merged**
