### PR TITLE
distro/rhel84: no hybrid boot on aarch64

### PR DESCRIPTION
**Pull request by gicmo**
Hybrid boot, i.e. MBR+UEFI, is only supported on X86_64, but not on aarch64, which only supports UEFI. Therefore, disable legacy, i.e. MBR, boot for aarch64 and remove the corresponding BIOS boot partition.

Since hybrid boot is always used on X86_64, the "uefi" parameter is removed completely, together with the "legacy only" option on X86_64. Thus we are left with a simple one to one mapping of architecture to qemu assembler stage options in `qemuAssembler`.

### CODE REVIEW

**Review by larskarlitski — APPROVED** [review]
Yep! Thank you so much for this. So much simpler now.

**Review by teg — APPROVED** [review]

**Review by teg — APPROVED** [review]
Thanks for the quick rebase! And thanks for the fix and testing.

**Comment by gicmo** [comment]
For the record, I manually checked `aarch64` and `s390x` (built an image and booted it) .

**Comment by gicmo** [comment]
Manually also checked `ppc64le` now too (built an image and booted it).

**Comment by teg** [comment]
The F32 and F33 openstack image tests failed with:
```
Cannot create instance: The service is currently unable to handle the request due to a temporary overloading or maintenance. This is a temporary condition. Try again later.
```
This is unrelated to this PR, which only touches RHEL.

**Comment by teg** [comment]
There was an issue with fedora iot on F33, but again that is clearly unrelated to this PR. Merge to let CI re-run on `main`.

**Pull request merged**
