### PR TITLE
rhel9: enable & fix installer test

### PR DESCRIPTION
**Pull request by diaasami**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by jrusz** [comment]
This is currently suffering from the same issue as https://github.com/osbuild/osbuild-composer/pull/1688

**Comment by diaasami** [comment]
rebased to benefit from the updated schutzbot terraform

**Comment by ondrejbudai** [comment]
Hmm, looks like that the CI failed for this. Can you please investigate?

**Review by achilleas-k — APPROVED** [review]
Wonderful!  Thanks for fixing this

**Pull request merged**
