### PR TITLE
Simplified installer: add support for encrypted raw images

### PR DESCRIPTION
**Pull request by runcom**
This PR depends on:

- osbuild stages https://github.com/osbuild/osbuild/pull/967
- luks support https://github.com/osbuild/osbuild-composer/pull/2141
- ~~still missing rhel86 support (will do asap)~~

### CODE REVIEW

**Comment by gicmo** [comment]
I think we should bump the osbuild requirement in the spec file here to the release that contains the corresponding stages.

**Comment by runcom** [comment]
> I think we should bump the osbuild requirement in the spec file here to the release that contains the corresponding stages.

ack, is there a release already with those new stages? 48 is a week old

**Comment by teg** [comment]
> > I think we should bump the osbuild requirement in the spec file here to the release that contains the corresponding stages.
> 
> ack, is there a release already with those new stages? 48 is a week old

@ochosi will do a release today.

**Comment by runcom** [comment]
despite the last commit, this is still picking up osbuild 46 instead of latest

```
++ cat Schutzfile
++ jq -r '.["rhel-8.6"].dependencies.osbuild.commit'
+ OSBUILD_GIT_COMMIT=8f75d1e7a10879dfc41ad82dc2f1c6183f5ff4f8
+ [[ 8f75d1e7a10879dfc41ad82dc2f1c6183f5ff4f8 != \n\u\l\l ]]
+ setup_repo osbuild 8f75d1e7a10879dfc41ad82dc2f1c6183f5ff4f8 10
+ local project=osbuild
+ local commit=8f75d1e7a10879dfc41ad82dc2f1c6183f5ff4f8
+ local priority=10
+ local REPO_PATH=osbuild/rhel-8.6/x86_64/8f75d1e7a10879dfc41ad82dc2f1c6183f5ff4f8
+ [[ false == \t\r\u\e ]]
+ greenprint 'Setting up dnf repository for osbuild 8f75d1e7a10879dfc41ad82dc2f1c6183f5ff4f8'
++ date -Isecond
+ echo -e '\033[1;32m[2022-02-23T17:48:43-05:00] Setting up dnf repository for osbuild 8f75d1e7a10879dfc41ad82dc2f1c6183f5ff4f8\033[0m'
[1;32m[2022-02-23T17:48:43-05:00] Setting up dnf repository for osbuild 8f75d1e7a10879dfc41ad82dc2f1c6183f5ff4f8[0m
+ sudo tee /etc/yum.repos.d/osbuild.repo
[osbuild]
name=osbuild 8f75d1e7a10879dfc41ad82dc2f1c6183f5ff4f8
baseurl=http://osbuild-composer-repos.s3-website.us-east-2.amazonaws.com/osbuild/rhel-8.6/x86_64/8f75d1e7a10879dfc41ad82dc2f1c6183f5ff4f8
enabled=1
gpgcheck=0
```

**Comment by runcom** [comment]
> despite the last commit, this is still picking up osbuild 46 instead of latest

I think it's just related to the fact that the repo has priority=10 (but keep making no sense as to why it doesn't work as the osbuild-composer repo has priority=5 and it installs the correct RPM :man_shrugging: )

**Comment by runcom** [comment]
we should also make sure to bump the Requires on osbuild to be > 49 when this lands

**Comment by teg** [comment]
I pulled in the fixes from #2369.

**Comment by runcom** [comment]
tests are failing here cause the layout of the disk changed and we have some ansible checks around that, @yih-redhat will fix them in a couple hours

**Comment by runcom** [comment]
but I can tell the raw image built just fine with encryption if we got to the ansible ostree checks :smile:

**Pull request merged**
