### PR TITLE
Add coveralls.io coverage reports to the unit tests

### PR DESCRIPTION
**Pull request by bcl**
This uses the goveralls project to run the tests and push the results to
coveralls.io

### CODE REVIEW

**Comment by bcl** [comment]
I think an admin needs to add this repo to coveralls.io for this to work completely.

**Comment by bcl** [comment]
Turned on more verbose output, looks like it is running all the tests so I'm not sure why that coveralls report only showed coverage for crypt.

**Comment by msehnout** [comment]
We need to discuss enabling of coveralls for this organization first. I enabled it for a while, but other didn't agree, so I denied the access again. But I'm definitely interested in having code coverage tool.

**Comment by gicmo** [comment]
I switched one of the projects (G-Node/nix) from https://coveralls.io to https://codecov.io because I personally preferred that (better config options, etcpp).

**Comment by bcl** [comment]
See PR #225 for a simpler coverage report.

**Pull request closed without merging**
