### PR TITLE
🐣 Add RHEL 8.3 test cases

### PR DESCRIPTION
**Pull request by major**
Created with:

    ./tools/test-case-generators/generate-test-cases \
      --distro rhel-8.3 --arch x86_64 --store .osbuild/ \
      --output test/cases/

Signed-off-by: Major Hayden <major@redhat.com>

### CODE REVIEW

**Comment by teg** [comment]
So, I wonder about this. We are now pointing to the latest nightly in the test case, so it will get out-of-sync as soon as a new nightly is released.

**Comment by teg** [comment]
@dvdhrm this sounds like a job for `fedmir`.

**Comment by major** [comment]
There's an 8.3.0 option, too. It seems there is some compose shuffling happening today.

**Comment by major** [comment]
Nevermind. The redhat-release file for 8.3 is not signed yet.

**Pull request closed without merging**
