### PR TITLE
blueprint: sshkey to users in images blueprint conversion

### PR DESCRIPTION
**Pull request by achilleas-k**
See https://github.com/osbuild/images/pull/928 for reasoning.

---

**go.mod: update osbuild/images to v0.87.0**

Update osbuild/images to include:
- blueprint: remove the sshkey customization
  (https://github.com/osbuild/images/pull/928).
- [RHEL-9] Drop RHSM and RHUI-specific config from Azure and EC2 images
  (COMPOSER-2308) (https://github.com/osbuild/images/pull/857).

---

**blueprint: sshkey to users in images blueprint conversion**

The sshkey customization in osbuild/images has been dropped.  In
osbuild-composer we maintain it for backwards compatibility, converting
each to a user customization, which is a superset of the sshkey.

---

**cloudapi: update expected image type test for gcp-rhui**

gce-rhui is now gone from RHEL 9 [1] and the old name simply aliases to
gce.  gcp-rhui in the cloudapi now resolves to 'gce' in RHEL 9 and
'gce-rhui' in RHEL 8.

[1] https://github.com/osbuild/images/pull/857

---

### CODE REVIEW

**Review by thozza — DISMISSED** [review]
Thanks, LGTM!

**Review by thozza — APPROVED** [review]

**Comment by thozza** [comment]
```
System doesn't contain the expected image-builder.insights facts (profile-id)
```
:thinking:

**Comment by thozza** [comment]
https://github.com/osbuild/osbuild-composer/blob/f58193dbebef99cb53a9562f6740645bdb6825ff/test/cases/api/common/common.sh#L63

It is now called:
```
image-builder.insights.compliance-profile-id: pci-dss
```

**Comment by achilleas-k** [comment]
> https://github.com/osbuild/osbuild-composer/blob/f58193dbebef99cb53a9562f6740645bdb6825ff/test/cases/api/common/common.sh#L63
> 
> It is now called:
> 
> ```
> image-builder.insights.compliance-profile-id: pci-dss
> ```

Awesome, thanks for looking it up!

**Review by thozza — APPROVED** [review]

**Pull request merged**
