### PR TITLE
Set the tenant in the request context, reuse it for the status and request duration metrics

### PR DESCRIPTION
**Pull request by croissanne**
Adds the tenant field to the status and request duration metrics, and uses the the latter in the worker api as well.

---

Once we update the dashboards we can move the total_requests and total_compose_requests counters.

### CODE REVIEW

**Comment by kingsleyzissou** [comment]
Neat, I've verified this locally and it's working well! Not sure what's going on with the api tests though

**Comment by croissanne** [comment]
> Neat, I've verified this locally and it's working well! Not sure what's going on with the api tests though

ah I changed the metrics test there, must've done it wrong. Will take a look

**Review by ondrejbudai — COMMENTED** [review]
Looks good!

**Comment by croissanne** [comment]
> Looks good!

still a wee bug, missing a `!`

**Review by kingsleyzissou — APPROVED** [review]

**Pull request merged**
