### PR TITLE
Add CentOS Stream 9 support

### PR DESCRIPTION
**Pull request by achilleas-k**
This pull request includes:

- [x] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by Gundersanne — APPROVED** [review]

**Review by ondrejbudai — COMMENTED** [review]
:heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: 

(will review later)

**Comment by achilleas-k** [comment]
I put the wrong usernames for the CI runners in the terraform config.  The images were created with `cloud-user` for openstack and `ec2-user` for AWS.
Fix PR: https://github.com/osbuild/gitlab-ci-terraform/pull/39

**Comment by ondrejbudai** [comment]
FTR so far I did these changes:
- fixed mockbuild so it supports centos stream 9
- rebase to latest `main` to pickup the terraform runner changes

**Comment by achilleas-k** [comment]
**`schutzbot/terraform` conflict:** the new hash in `main` points to a commit in the `gitlab-ci-terraform` repo that's on a branch (`rhos-01`).  Will this be merged into `gitlab-ci-terraform/main`?

**Manifest tests:** I used the latest production repos [0] for the tests.  This will cause issues with changing package versions.  We're going to need a repo snapshot.

[0] -https://composes.stream.centos.org/production/latest-CentOS-Stream/

**Comment by ondrejbudai** [comment]
> **`schutzbot/terraform` conflict:** the new hash in `main` points to a commit in the `gitlab-ci-terraform` repo that's on a branch (`rhos-01`). Will this be merged into `gitlab-ci-terraform/main`?

Not necessarily, `main` is currently used for projects that use RHOS-D (image-builder, osbuild), whereas `rhos-01` is used in `osbuild-composer` that uses RHOS-01. If you need to make any changes in `rhos-01`, feel free to send a PR. @lavocatt knows everything if you need help. :)

**Comment by achilleas-k** [comment]
> > **`schutzbot/terraform` conflict:** the new hash in `main` points to a commit in the `gitlab-ci-terraform` repo that's on a branch (`rhos-01`). Will this be merged into `gitlab-ci-terraform/main`?
> 
> Not necessarily, `main` is currently used for projects that use RHOS-D (image-builder, osbuild), whereas `rhos-01` is used in `osbuild-composer` that uses RHOS-01. If you need to make any changes in `rhos-01`, feel free to send a PR. @lavocatt knows everything if you need help. :)

oh, okay.  I thought the new flavour ID was necessary in general because I saw some failures in the previous run with message `Flavor could not be found` [0].

[0] - https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1904731287

**Comment by achilleas-k** [comment]
## Updates

- Added s390x for CS9
- Changed test repositories (`test/data/repositories/centos-9.json`) and test case generator repositories (`tools/test-case-generators/repos.json`) to use the new rpmrepo snapshots.
  - Main repositories (`repositories/centos-9.json`) still point to latest production repos.
- (Re)generated all test cases, including s390x, for the new repos.

**Comment by achilleas-k** [comment]
Moved all CS9 tests to internal network for
https://github.com/osbuild/osbuild-composer/blob/0faf8a2ec291f0582a12e6f88749e97c31091bfc/tools/provision.sh#L14-L18

**Comment by achilleas-k** [comment]
OSTree tests are failing with
```
curl: error downloading {'url': '...'}: error code 23
```
which likely means they runner is out of space (some tests even say so).

Is this an issue with the image in openstack?  What controls the instance storage size?

**Comment by ondrejbudai** [comment]
@lavocatt any ideas on the disk space in RHOS-01?

**Comment by lavocatt** [comment]
Hey! Yes Ladislav gave us the properties of the machines https://docs.google.com/spreadsheets/d/18IznFSzRDRPwdV9cAlz4L1OhnCWQ8S6l3F5L2HieyII/edit#gid=0 I think that we still need to use the ssd flavor for ostree tests, but we can bump from to medium or large for the one that is crashing ? You can also have a try with a disk focused flavor if you want.

**Comment by ondrejbudai** [comment]
Which flavor do we use now?

**Comment by lavocatt** [comment]
`openstack/rhel-8.5-ga-x86_64` and `openstack/rhel-8.6-nightly-x86_64` are using the flavor `f2c4469b-f516-46d1-8b87-1dcca68fb3d9` which is `ci-ssd.standard.medium` I've just notice however that we could use `77f58261-d373-4749-8781-aff678329d57` which is `ci-ssd.disk.medium` that gives us 60 gigs of storage instead of 40.

**Comment by achilleas-k** [comment]
I already added `c3ec7a0a-0443-4253-a6ab-040cc0278ced` to the Terraform config as `centos-stream-9-large`, which corresponds to `ci-ssd.standard.large`.  That's 60 GB.

That was meant for OSTree tests and I accidentally added the standard to one to all of them.  Running with large noe.

**Comment by henrywang** [comment]
@achilleas-k I re-build installer ISO file with [function](https://github.com/osbuild/osbuild-composer/blob/main/test/cases/installers.sh#L16). Everything works well.
I suspect the `Volume id` in the ISO file. I checked [`CentOS-Stream-9-latest-x86_64-boot.iso`](http://mirror.stream.centos.org/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-latest-x86_64-boot.iso) and got the following info.
I can't find volume id for centos.
```
$ isoinfo -d -i CentOS-Stream-9-latest-x86_64-boot.iso
CD-ROM is in ISO 9660 format
System id:
Volume id: CentOS-Stream-9-BaseOS-x86_64
Volume set id:
Publisher id:
Data preparer id: XORRISO-1.5.4 2021.01.30.150001, LIBISOBURN-1.5.4, LIBISOFS-1.5.4, LIBBURN-1.5.4
Application id:
Copyright File id:
Abstract File id:
Bibliographic File id:
Volume set size is: 1
Volume set sequence number is: 1
Logical block size is: 2048
Volume size is: 388096
El Torito VD version 1 found, boot catalog is in sector 40
Joliet with UCS level 3 found
Rock Ridge signatures version 1 found
Eltorito validation header:
    Hid 1
    Arch 0 (x86)
    ID ''
    Key 55 AA
    Eltorito defaultboot header:
        Bootid 88 (bootable)
        Boot media 0 (No Emulation Boot)
        Load segment 0
        Sys type 0
        Nsect 4
        Bootoff 161D 5661
```

**Comment by achilleas-k** [comment]
@henrywang thanks for looking into this.

Looks like the volume ID should be `CentOS-Stream-9-BaseOS-$arch`.  I had reused/adapted the one from the CentOS Stream 8 which was `CentOS-Stream-8-$arch-dvd`.

**Comment by achilleas-k** [comment]
I think we should switch to using the `development` repositories for CS9 for now:
https://github.com/osbuild/rpmrepo/pull/20

**Comment by henrywang** [comment]
@achilleas-k I upgraded my CS9 test VM, and run test again. Everything works great!
```
[admin@centos-stream-9-220110 rhel-edge]$ rpm -q osinfo-db
osinfo-db-20211216-1.el9.noarch
[admin@centos-stream-9-220110 rhel-edge]$ sudo osinfo-detect 6d7dfb07-e80f-4300-8ee3-1454ff8bf613-installer.iso
Media is bootable.
Media is an installer for OS 'CentOS Stream 9 (x86_64)'
```

**Comment by achilleas-k** [comment]
- Resolved merge conflicts
- Made a new rpmrepo snapshot and switched the repo configs for the tests
- Updated the cs9 manifests

**Comment by achilleas-k** [comment]
CS9 `New OSTree` test was hit by [rhbz#2046612](https://bugzilla.redhat.com/show_bug.cgi?id=2046612).  Fixed by updating repos, but that means updating the greenboot packages, so we're either blocked on #2196 or we absorb it into this one.
I don't know why the F35 `OSTree` test is failing.

**Comment by achilleas-k** [comment]
Rebased on #2196

**Comment by achilleas-k** [comment]
Rebased on main.

**Review by Gundersanne — APPROVED** [review]

**Pull request merged**
