### PR TITLE
test: [rhel-8.4.0] Update Edge related tests on rhel-8.4.0 branch

### PR DESCRIPTION
**Pull request by henrywang**
The Edge for RHEL 8.4 downstream CI uses the same test code as test code in branch `rhel-8.4.0`. Some of test code updates are merged in `main`, but they're not available in branch `rhel-8.4.0`.

This PR cherry picked 6 commits which is related with file `ostree-ng.sh` from `main` to branch `rhel-8.4.0`.

### CODE REVIEW

**Review by achilleas-k — DISMISSED** [review]
Awesome.  Thanks!

Probably not necessary to cherry-pick, but e7b3063f7ec06fdb547515c24fd956ed1af74e0b also made a small change to the ostree* test scripts.
Wanted to point out that this difference will still remain between the two branches.

**Comment by henrywang** [comment]
> Awesome. Thanks!
> 
> Probably not necessary to cherry-pick, but [e7b3063](https://github.com/osbuild/osbuild-composer/commit/e7b3063f7ec06fdb547515c24fd956ed1af74e0b) also made a small change to the ostree* test scripts.
> Wanted to point out that this difference will still remain between the two branches.

Nice catch. Thanks @achilleas-k! I added [e7b3063](https://github.com/osbuild/osbuild-composer/commit/e7b3063f7ec06fdb547515c24fd956ed1af74e0b) in.

**Review by achilleas-k — APPROVED** [review]

**Comment by henrywang** [comment]
@achilleas-k I have to drop commit `test: Update test to align with customer scenario` and `test: Update test to cover two more scenarios` because both of them covered your fix `weldr: improve ostree ref and URL handling`. But your fix has not been included in rhel 8.4 release and not in branch `rhel `-8.4.0` as well.
That's really not what I expected.

**Comment by ondrejbudai** [comment]
Just a small note to prevent misunderstandings: These changes won't be reflected in the nightly testing as it uses a build from the latest nightly.

**Comment by henrywang** [comment]
> Just a small note to prevent misunderstandings: These changes won't be reflected in the nightly testing as it uses a build from the latest nightly.

Thanks for your reminder. It's for RHEL for Edge downstream test which uses test code in branch `rhel-8.4.0`.

**Comment by achilleas-k** [comment]
> @achilleas-k I have to drop commit `test: Update test to align with customer scenario` and `test: Update test to cover two more scenarios` because both of them covered your fix `weldr: improve ostree ref and URL handling`. But your fix has not been included in rhel 8.4 release and not in branch `rhel `-8.4.0` as well.
> That's really not what I expected.

I think what happened was we decided it wasn't a big enough issue to try to get an exception for 8.4.0.  It wasn't a big breaking bug and it came up pretty late, so we focused on getting more serious issues through.

**Comment by henrywang** [comment]
Close this PR because downstream has its own test code. Downstream test will not share test code with upstream, because some test code can't be cherry picked to `rhel-8.4.0` branch, such as `test: Update test to align with customer scenario` and `test: Update test to cover two more scenarios`. Downstream test code is able to add both tests and is more easy to update test code.

**Pull request closed without merging**
