### PR TITLE
distro/rhel85: ability to create users during installation (edge installer)

### PR DESCRIPTION
**Pull request by gicmo**
This includes users and groups customizations in the kickstart file for the anaconda based edge installer.

NB: this is only for the anaconda based edge installer, not the simplified one, which does not use kickstarts.

This PR is based on #1699

- [ ] adequate testing for the new functionality or fixed issue
- [x] adequate documentation informing people about the change such as
  - [x] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news

### CODE REVIEW

**Comment by gicmo** [comment]
Manually tested, with osbuild PR (https://github.com/osbuild/osbuild/pull/783) which includes a fix to quote the ssh keys.

**Comment by henrywang** [comment]
@gicmo do we need land PR #1699 first and make a rebase in order to test this PR? Thanks.

**Comment by ondrejbudai** [comment]
> @gicmo do we need land PR #1699 first and make a rebase in order to test this PR? Thanks.

I think so. (@gicmo is out for next two weeks.)

**Comment by henrywang** [comment]
@gicmo could you please make a rebase due to PR #1699 has been merged already. Thanks.

**Comment by achilleas-k** [comment]
Rebased while gicmo is away

**Comment by henrywang** [comment]
@gicmo @achilleas-k I got the following error on anaconda installation:
Looks user configured in blueprint does not work in this case.
```
================================================================================

================================================================================
Installation

1) [x] Installation Destination          2) [x] Kdump
       (Automatic partitioning                  (Kdump is enabled)
       selected)
3) [x] Network configuration             4) [!] User creation
       (Wired (enp1s0) connected)               (No user will be created)

Please make a selection from the above ['b' to begin installation, 'q' to quit,
'r' to refresh]:
```

**Comment by achilleas-k** [comment]
> @gicmo @achilleas-k I got the following error on anaconda installation:
> Looks user configured in blueprint does not work in this case.
> 
> ```
> ================================================================================
> 
> ================================================================================
> Installation
> 
> 1) [x] Installation Destination          2) [x] Kdump
>        (Automatic partitioning                  (Kdump is enabled)
>        selected)
> 3) [x] Network configuration             4) [!] User creation
>        (Wired (enp1s0) connected)               (No user will be created)
> 
> Please make a selection from the above ['b' to begin installation, 'q' to quit,
> 'r' to refresh]:
> ```

Strange.  I don't see the same on my end.  What does the kickstart file look like on the ISO?

**Comment by henrywang** [comment]
> Strange. I don't see the same on my end. What does the kickstart file look like on the ISO?
```
text
network --bootproto=dhcp --device=link --activate --onboot=on
zerombr
clearpart --all --initlabel --disklabel=msdos
autopart --nohome --noswap --type=plain
ostreesetup --nogpg --osname=rhel-edge --remote=rhel-edge --url=file://${INSTALLER_PATH} --ref=${OSTREE_REF}
poweroff
%post --log=/var/log/anaconda/post-install.log --erroronfail
# no sudo password for user admin
echo -e 'admin\tALL=(ALL)\tNOPASSWD: ALL' >> /etc/sudoers
echo -e 'installeruser\tALL=(ALL)\tNOPASSWD: ALL' >> /etc/sudoers
# delete local ostree repo and add external prod edge repo
ostree remote delete rhel-edge
ostree remote add --no-gpg-verify --no-sign-verify rhel-edge ${PROD_REPO_URL}
%end
```

**Comment by henrywang** [comment]
@achilleas-k @gicmo I found an issue about password. When adding user in kickstart, `--iscrypted` should be added because password in blueprint is encrypted.
kickstart in ISO:
```
user --name installeruser --password $6$GRmb7S0p8vsYmXzH$o0E020S.9JQGaHkszoog4ha4AQVs3sk8q0DvLjSMxoxHBKnB2FBXGQ/OkwZQfW/76ktHd0NX5nls2LPxPuUdl. --groups wheel --homedir /home/installeruser/
```

**Comment by achilleas-k** [comment]
> @achilleas-k @gicmo I found an issue about password. When adding user in kickstart, `--iscrypted` should be added because password in blueprint is encrypted.
> kickstart in ISO:
> 
> ```
> user --name installeruser --password $6$GRmb7S0p8vsYmXzH$o0E020S.9JQGaHkszoog4ha4AQVs3sk8q0DvLjSMxoxHBKnB2FBXGQ/OkwZQfW/76ktHd0NX5nls2LPxPuUdl. --groups wheel --homedir /home/installeruser/
> ```
> 
> BTW: SSH key works in this case.

Great catch.  Thank you.  I just opened https://github.com/osbuild/osbuild/pull/794

**Comment by henrywang** [comment]
@ondrejbudai The CI status keeps on `Expected — Waiting for status to be reported` status. How can I re-start the test? Thanks.

**Comment by ondrejbudai** [comment]
We're sometimes hitting Gitlab quota for parallel running jobs. In this case, you need to go to [this page](https://gitlab.com/osbuild/ci/osbuild-composer/-/pipelines), find you PR, cancel the pipeline and restart it. I'm currently working on fixing this by moving the project under a premium group.

I restarted the pipeline for you. ;)

**Comment by henrywang** [comment]
@achilleas-k @teg I found osbuild/osbuild#794 is not included in osbuild-35 release. May I pin osbuild to latest commit? I found osbuild pin got removed. So I have to ask here. Thanks!

**Comment by teg** [comment]
yeah, pin until we have landed that in 8.5

**Review by ondrejbudai — CHANGES_REQUESTED** [review]
We need an exception for this, blocking until this is resolved.

**Comment by achilleas-k** [comment]
To keep everyone in the loop:
We discussed with @teg the possibility of having the same kind of user creation during deployment of the edge raw image, which would add the same functionality to the simplified edge installer.  This might need more work though so we're keeping it open until I have time to look into it.

**Comment by teg** [comment]
This did not make it for 8.5. Would need a rebase for 8.6 / 9.0-GA.

**Pull request closed without merging**
