### PR TITLE
CI: test installer

### PR DESCRIPTION
**Pull request by achilleas-k**
This pull request includes:

- [x] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

Keeping as draft to find the best way to test the installer.

### CODE REVIEW

**Review by atodorov — APPROVED** [review]
LGTM but it seems like this PR needs to be rebased.

**Comment by achilleas-k** [comment]
The test script needs some work.  I'm having trouble getting the installation to work fully automatically.  I suspect it has to do with the ISO having a kickstart file already embedded and the addition of the other kickstart through `virt-install`.  From reading the docs+source it seemed like the new ks would override the existing one, but maybe I missed something.

**Comment by atodorov** [comment]
@achilleas-k can you explain why do you need to have 2 kickstart files? I'm not sure I understand what's the point here.

**Comment by achilleas-k** [comment]
> @achilleas-k can you explain why do you need to have 2 kickstart files? I'm not sure I understand what's the point here.

The `tar-installer` image type that we build already contains a kickstart file.  It contains a single `liveimg` line that points to the tarball on the ISO.

For testing, we would need to override that ks file to perform a fully non-interactive installation (primarily `autopart`) and also keep the original `liveimg` command.

**Comment by achilleas-k** [comment]
Updated the test: The kickstart file is now modified by mounting the ISO, reading the existing content, and then using `mkksiso` to write a new one with the existing commands and some extra ones specifically for automating the installation and testing.  This should now work without needing to add kickstart-related directives to the `virt-install` command and brings the test closer to the original intended usage, since the original ks contents aren't overwritten entirely but wrapped in the new commands.

**Comment by achilleas-k** [comment]
I think we're ready now.  Watching the tests closely :eyes:

**Review by ondrejbudai — APPROVED** [review]
Looks good, thanks!

**Review by ondrejbudai — APPROVED** [review]

**Pull request merged**
