### PR TITLE
gen-manifests: derrive seedArg from filename and env

### PR DESCRIPTION
**Pull request by mvo5**
To ensure that manifests get random(ish) and stable UUIDs we set the seed arg based on the filename and the environment (`OSBUILD_GEN_MANIFEST_RNG_SEED`).

This should fix the issue discovered in
https://github.com/osbuild/manifest-db/pull/124

that duplicated UUIDs for xfs/btrfs can trigger random(ish) and hard to diagnose errors.

[draft as it lacks testing, I don't know yet how to do that]

### CODE REVIEW

**Comment by achilleas-k** [comment]
I think we might want to get rid of this cmd and only keep the one in images.  We'd have retool some things in manifest-db maybe so let's discuss it tomorrow and do it all then.

**Comment by achilleas-k** [comment]
Unless this is urgent

**Comment by mvo5** [comment]
If we get rid of this command I will close this PR and open one that removes the command  - otherwise we could simply import the helper from https://github.com/osbuild/images/pull/674 here now

**Comment by mvo5** [comment]
Closing in favor of https://github.com/osbuild/osbuild-composer/pull/4152

**Pull request closed without merging**
