### PR TITLE
New distro: RHEL 9.0 GA

### PR DESCRIPTION
**Pull request by achilleas-k**
New distro added, RHEL 9.0 GA (`rhel-90-ga`) including an alias for CentOS Stream 9 (`centos-9`).

Note: The subpackage is called `rhel90`, even though the distro string `rhel-90` is currently an alias for `rhel-90-beta`.  This alias will switch to the new `rhel-90-ga` distro in the near future.

The new distro is initially a copy of the existing `rhel90beta` subpackage.  Changes from the `rhel86` distro subpackage were then copied into the new distribution to bring it up to date with changes and fixes in RHEL 8.6.
The CentOS Stream 9 alias was added in the same way that the CentOS Stream 8 alias is added to RHEL 8.6.

Opening as draft for review while the test setup is finalised:
- [x] Set up test runners for RHEL 9.0 (non-beta) ~~and CentOS Stream 9~~
- [ ] ~~Repositories for CentOS Stream 9~~
- [ ] ~~Test manifests for CentOS Stream 9~~

-----

This pull request includes:

- [x] adequate testing for the new functionality or fixed issue

### CODE REVIEW

**Comment by teg** [comment]
> What's the plan with the `_ga` suffix? Is that something that we will use for all 9.y minor versions?

My understanding was that we would drop that as soon as we can drop the `rhel-90` alias from the beta, which is as soon as pungi no longer uses it.

**Comment by achilleas-k** [comment]
> > What's the plan with the `_ga` suffix? Is that something that we will use for all 9.y minor versions?
> 
> My understanding was that we would drop that as soon as we can drop the `rhel-90` alias from the beta, which is as soon as pungi no longer uses it.

It'd be nice if we could drop it before the first release that includes it, otherwise we might have to keep it for backwards compatibility.

**Comment by achilleas-k** [comment]
Looks like I didn't properly set up the RHEL 9.0 CI runners

**Comment by henrywang** [comment]
I tried this mock build, and greenboot services are enabled by `redhat-release`. Thanks @achilleas-k :+1: 
```
[admin@localhost ~]$ sudo systemctl is-enabled greenboot-grub2-set-counter greenboot-grub2-set-success greenboot-healthcheck greenboot-rpm-ostree-grub2-check-fallback greenboot-status greenboot-task-runner redboot-auto-reboot redboot-task-runner
enabled
enabled
enabled
enabled
enabled
enabled
enabled
enabled
[admin@localhost ~]$ journalctl -b -0 -u boot-complete.target -u greenboot -u greenboot-healthcheck -u greenboot-rpm-ostree-grub2-check-fallback -u greenboot-grub2-set-counter -u greenboot-grub2-set-success -u greenboot-status -u redboot -u redboot-auto-reboot -u redboot.target
-- Journal begins at Wed 2021-11-03 00:19:52 EDT, ends at Wed 2021-11-03 02:49:29 EDT. --
Nov 03 00:19:57 localhost.localdomain systemd[1]: Starting Check for fallback boot...
Nov 03 00:19:57 localhost.localdomain systemd[1]: Finished Check for fallback boot.
Nov 03 00:19:57 localhost.localdomain systemd[1]: Starting greenboot Health Checks Runner...
Nov 03 00:19:57 localhost.localdomain greenboot[709]: Running Required Health Check Scripts...
Nov 03 00:19:57 localhost.localdomain 00_required_scripts_start.sh[716]: Running greenboot Required Health Check Scripts
Nov 03 00:19:57 localhost.localdomain greenboot[709]: Script '00_required_scripts_start.sh' SUCCESS
Nov 03 00:19:57 localhost.localdomain greenboot[709]: Running Wanted Health Check Scripts...
Nov 03 00:19:57 localhost.localdomain 00_wanted_scripts_start.sh[723]: Running greenboot Wanted Health Check Scripts
Nov 03 00:19:57 localhost.localdomain greenboot[709]: Script '00_wanted_scripts_start.sh' SUCCESS
Nov 03 00:19:57 localhost.localdomain systemd[1]: Finished greenboot Health Checks Runner.
Nov 03 00:19:57 localhost.localdomain systemd[1]: Reached target Boot Completion Check.
Nov 03 00:19:57 localhost.localdomain systemd[1]: Starting Mark boot as successful in grubenv...
Nov 03 00:19:57 localhost.localdomain systemd[1]: Finished Mark boot as successful in grubenv.
Nov 03 00:19:57 localhost.localdomain systemd[1]: Starting greenboot MotD Generator...
Nov 03 00:19:57 localhost.localdomain greenboot-status[753]: Boot Status is GREEN - Health Check SUCCESS
Nov 03 00:19:57 localhost.localdomain systemd[1]: Finished greenboot MotD Generator.
```

**Comment by henrywang** [comment]
@achilleas-k `ostree-ng.sh` failed at pachage `python36`. Change line https://github.com/osbuild/osbuild-composer/blob/c0ceede084e2744512259904785e1daf6b623555/test/cases/ostree-ng.sh#L295 and https://github.com/osbuild/osbuild-composer/blob/c0ceede084e2744512259904785e1daf6b623555/test/cases/ostree-ng.sh#L569 to `python3` can fix.

**Comment by henrywang** [comment]
@achilleas-k I found the RHEL 9 test does not have `raw-installer` and `simplified-installer` included. Does RHEL 9 GA needs cover them? Thanks.

**Comment by achilleas-k** [comment]
Thanks for the review and noticing the missing tests @henrywang.  I changed the python36 package in the test blueprints to python3 and enabled the new ostree tests for RHEL 9.0 now.

> BTW: `RHEL 9 beta` test does not use `ostree-ng.sh` but use `ostree-ng-og.sh`, which updated package to `python3`.

I'm removing the `ostree-ng-og.sh` since it was for RHEL 9.0 Beta only and we're dropping those tests.  It was there because in the Beta we were still using the old container that ran Apache.  That's all gone now in RHEL 9.0.

**Comment by achilleas-k** [comment]
It seems we're missing one package `subscription-manager-cockpit` to get CentOS Stream 9 to work.  There may be more, but I haven't found them yet.

**Comment by henrywang** [comment]
@achilleas-k `osbuild` is pined to `662fe0feb9c3fd2843b34501900d466272aac776` which is old (osbuild-37-1.20210924git662fe0f.el9.noarch). I think we can remove the pin and use osbuild-39 on RHEL 9 instead.

**Comment by henrywang** [comment]
@achilleas-k The mock build `osbuild-composer-38-1.20211105gitf6ec776.el9.x86_64` still uses `httpd` for container image. The [manifest](https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1754215402/artifacts/browse/ci-artifacts/) shows the httpd as container http server.

**Comment by achilleas-k** [comment]
@henrywang There's some confusion as to which distro is being built because of the `rhel-90` alias to `rhel-90-beta`.  I'm going to drop that now and it will make life much easier.  Testing a few things locally before I push.  Might need to update the CI runners as well.

**Comment by achilleas-k** [comment]
Updates:
- Dropped the `_ga` suffix.  We now only have `rhel-90` and `rhel-90-beta`.  No aliases.
- Disabled `edge-simplified-installer` and associated test in RHEL 9.0.  The `coreos-installer` package isn't available yet.
- Fixed some missing packages.

**Comment by henrywang** [comment]
@achilleas-k Run RHEL 9 Edge container on OCP failed with the following error:
```
2021/11/09 04:35:24 [emerg] 1#1: open() "/var/log/nginx/access.log" failed (13: Permission denied)
```
This error does not exist on RHEL 8/CentOS Stream 8 Edge container. Could you please take a look if you have time? Thanks!

**Comment by achilleas-k** [comment]
> @achilleas-k Run RHEL 9 Edge container on OCP failed with the following error:
> 
> ```
> 2021/11/09 04:35:24 [emerg] 1#1: open() "/var/log/nginx/access.log" failed (13: Permission denied)
> ```
> 
> This error does not exist on RHEL 8/CentOS Stream 8 Edge container. Could you please take a look if you have time? Thanks!

oh thank you so much.  I was wondering what was wrong there.

**Comment by achilleas-k** [comment]
PR is ready and should be green on CI after the last push.

### CentOS Stream 9 disabled

CS9 is untested and will likely need some changes with packages that aren't yet available in the repos.  Disabling the distro now until we can fully test it in a followup PR.

**Comment by henrywang** [comment]
@achilleas-k `coreos-installer` is ready in nightly (http://download-node-02.eng.bos.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0.0/compose/AppStream/x86_64/os/Packages/coreos-installer-0.10.1-2.el9.x86_64.rpm). Enable `simplified-installer` test in this PR or in another PR? Both of them work for me. Thanks.

**Review by ondrejbudai — APPROVED** [review]
This is great!

**Comment by jrusz** [comment]
Ugh, is Azure serious? https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-ssh-keys-detailed#supported-ssh-key-formats

**Comment by achilleas-k** [comment]
> @achilleas-k `coreos-installer` is ready in nightly (http://download-node-02.eng.bos.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0.0/compose/AppStream/x86_64/os/Packages/coreos-installer-0.10.1-2.el9.x86_64.rpm). Enable `simplified-installer` test in this PR or in another PR? Both of them work for me. Thanks.

I'm leaning towards doing it separately since this PR should be ready to merge now (pending green CI) and I don't want to start pushing changes again.

**Review by ondrejbudai — APPROVED** [review]

**Pull request merged**
