### PR TITLE
Update images to `v0.77.0` and enable `rpm` and `rhsm` customizations (COMPOSER-2308)

### PR DESCRIPTION
**Pull request by thozza**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the READMEs [listed here](https://github.com/osbuild/osbuild.github.io/blob/main/readme-list)
  - [ ] submit a PR for the [osbuild.org website](https://github.com/osbuild/osbuild.github.io/) repository if this PR changed any behavior not covered by the automatically updated READMEs

### CODE REVIEW

**Review by achilleas-k — DISMISSED** [review]
Very nice.
LGTM

**Review by kingsleyzissou — APPROVED** [review]
Thanks and sorry for the rpm spec! Thanks for fixing

**Comment by thozza** [comment]
I had to disable the `rpm` customization test case on el10 after the rebase on `main`. The reason is that the GPG key used in the test case uses SHA-1 in its signature, which is no longer allowed by default on c10s / el10.

While I was at it, I also updated the `osbuild/images` ref to `v0.77.0`.

**Review by ondrejbudai — DISMISSED** [review]
Thanks!

**Review by kingsleyzissou — APPROVED** [review]

**Comment by thozza** [comment]
Sorry, there are additional new issues after the rebase. I'm looking into it.... :roll_eyes:

**Comment by thozza** [comment]
OK, looks like the main Gitlab CI finally passed :roll_eyes:

**Review by kingsleyzissou — APPROVED** [review]

**Pull request merged**
