### PR TITLE
cloudapi: use Recover middleware to handle panics

### PR DESCRIPTION
**Pull request by diaasami**
Recover middleware recovers from panics anywhere in the
chain & prints stack trace

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by teg — COMMENTED** [review]
This sounds cool. But could you elaborate a bit in the commit message? What kind of things are we catching in this way, and what is the change in behaviour compared to the current one?

**Comment by Gundersanne** [comment]
Ah @diaasami discussed this yesterday. 

So by default a panic will not crash the webserver of course, but the client will just get an empty reply. Using this, which simply calls `recover()`, it will make it to the errorhandler and return a 500 at least. And it will log the error using `echo.Logger` which with some minor work we can hook up to logrus, instead of stderr.

That said they'd probably get the `ErrorNotHTTPError` error code, which is true of course but not very informative? Is it worth just writing our own and returning a specific error, `ErrorRecoveredFromPanic` or something?

**Comment by diaasami** [comment]
> That said they'd probably get the `ErrorNotHTTPError` error code, which is true of course but not very informative? Is it worth just writing our own and returning a specific error, `ErrorRecoveredFromPanic` or something?

I do not think an error without details and message would be helpful for the client, may be only for metrics.

**Comment by Gundersanne** [comment]
> > That said they'd probably get the `ErrorNotHTTPError` error code, which is true of course but not very informative? Is it worth just writing our own and returning a specific error, `ErrorRecoveredFromPanic` or something?
> 
> I do not think an error without details and message would be helpful for the client, may be only for metrics.

Yea ErrorRecoveredFromPanic is about as useful as ErrorNotHTTPError, plus the details of those errors should really only be seen by us as who knows what they might contain.

**Comment by teg** [comment]
I think some generic 500 makes sense and details in the logs. Don't think we really need to say it was a panic, but don't have a strong opinion.

**Comment by Gundersanne** [comment]
Agreed, this is fine as is.

**Review by Gundersanne — APPROVED** [review]

**Pull request merged**
