### PR TITLE
dnf-json: explicitly set priority

### PR DESCRIPTION
**Pull request by teg**
Prioritise the repositories in the order they are passed. Currently their priorities are all
the same, which gives (to me) unexpected results.

The logic is now that appending a repo to the list of repositories, means that it overrides
the previously passed ones. This is relevant in case the same packages exist in the
base repositories as in the payload repositories. In this case we should prefer the
payload ones.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by teg** [comment]
I ran into this when trying to use image builder to build our worker images from the RPMs in COPR. I ended up with RPMs from AppStream, which is not what I wanted.

I think it stands to reason that for the packages in our base package set (the first depsolve we do in the chain) we get the packages from the base repos. However, in the subsequent depsolve, when we depsolve the packages given in the blueprint we should prefer the packages in the payload repository, which is what this PR attempts to do (untested...).

**Comment by teg** [comment]
The alternative approach is to set the priority by "group of repositories", and then keep it the same for the whole group, there could be that BaseOS and AppStream having the same priority is intentional and important (for instance). The important part is that payload repos override base repos (and if ever we get "payload override repos" they should fit in-between), how the repos are prioritised internally in the group might be less important, and maybe we should not make it explicit.

**Comment by achilleas-k** [comment]
Good way to test this would be with the `dummy` package repo we create in a few tests: we can create two of them and control which one gets selected based on order.

**Comment by teg** [comment]
I agree to both comments. I might not get the chance to finish this up, so please consider it a glorified RFE, and feel free to take it over :)

**Comment by thozza** [comment]
I'm not 100% sure how will DNF behave if we would try to depsolve 2nd+ transaction with payload repos, which would contain newer versions of packages in the base image package set. IIRC, we do not want to allow user to replace packages from the base package set with packages in repos provided by them. If this is still the case, we should cover this case with a test case before using priorities. Otherwise I think that it makes sense to put higher priority on user-provided repositories.

Unless users need to have different priority set for the repositories provided by them, it makes sense to start with setting the priority per "group of repositories". Also it IMO does not make much sense for the "base" RHEL repositories to not have the same priority.

I also like Ondrej's suggestion to not make `dnf-json` smarter, and instead make composer to pass the priorities to it.

**Comment by teg** [comment]
Regarding replacing base packages. I think we have the following scenarios (and I think @ondrejbudai might be looking into clarifying this):
 - user wants to add software to a RHEL system, which does not exist in RHEL (the current payload support)
 - user wants to add software to a RHEL system, which exists in RHEL, but is not installed in the base system (what I'm trying to do, which I think could be made to work by setting the priority right for the payload repositories, though needs verification - it really should work as if you added high-prio repos and did a manual dnf install on top of your base system)
 - user wants to replace packages from the base system with their own (say from COPR if you are doing rhel/centos/fedora development), this would be needed by anaconda, and is not currently supported (would need some sort of `BaseReposOverride`), this should work as if the given repositories were used (at a higher priority) to create the base system.

**Pull request closed without merging**
