### PR TITLE
test: Add Fedora 33 ostree test back

### PR DESCRIPTION
**Pull request by yuxisun1217**
Fix: #1497 

Signed-off-by: Yuxin Sun <yuxisun@redhat.com>

This pull request includes:

- [x] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by ondrejbudai — DISMISSED** [review]
Looks good, let's see if the CI suceeds.

**Review by atodorov — APPROVED** [review]

**Comment by yuxisun1217** [comment]
Blocked by #1561

**Comment by yuxisun1217** [comment]
Rebased. But some vmware.sh+rhel jobs failed(see https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1437164333):
```
Jul 20 07:57:41 ip-10-30-18-54.us-east-1.aws.redhat.com osbuild-worker[22136]: /usr/libexec/osbuild-composer/osbuild-worker: Post "https://[MASKED]/sdk": dial tcp: lookup [MASKED] on 10.5.30.160:53: no such host
Jul 20 07:57:41 ip-10-30-18-54.us-east-1.aws.redhat.com osbuild-worker[22136]: 2021/07/20 07:57:41 target failed: importing vmdk failed
Jul 20 07:57:42 ip-10-30-18-54.us-east-1.aws.redhat.com osbuild-worker[22136]: 2021/07/20 07:57:42 Job 68cce813-b7ff-4101-9d95-f9601c40520f finished
Jul 20 07:57:42 ip-10-30-18-54.us-east-1.aws.redhat.com osbuild-worker[22136]: Waiting for a new job...
💬 Getting compose log and metadata
/usr/libexec/tests/osbuild-composer/vmware.sh: line 164: 22191 Terminated              sudo journalctl -af -n 1 -u "${WORKER_UNIT}"
Something went wrong with the compose. 😢
```

**Review by atodorov — APPROVED** [review]
Newly added test job reports PASS.

**Review by ondrejbudai — APPROVED** [review]

**Pull request merged**
