### PR TITLE
Test job parity b/w GitLab & Jenkins

### PR DESCRIPTION
**Pull request by atodorov**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by atodorov** [comment]
@ondrejbudai I'm getting the following failures:

1) Base on 8.4 aarch64 fails b/c there's no matching osbuild RPM simply because we don't build that yet. Once the osbuild repo is migrated to GitLab we can add this. 

2) Base F34 fails with some errors from Azure, not sure what this is
3) Integration F34 also fails with the same `Code: BlobNotFound` error from Azure.

Can you advise ? Are the F34 failures known issues ?

**Comment by jrusz** [comment]
> 2. Base F34 fails with some errors from Azure, not sure what this is
> 3. Integration F34 also fails with the same `Code: BlobNotFound` error from Azure.

That's actually cloud-cleaner running because it's in the after_script section and that's not what's causing the failure. The actual failure is a bit further up: 
```
ERROR: Show Error: Get "http://localhost/api/status": read unix @->/run/weldr/api.socket: read: connection reset by peer
```
which is because osbuild-composer does not yet support fedora-34. If you try to start osbuild-composer.socket you'll get something like:
``` 
osbuild-composer[37981]: 2021/05/10 05:44:51 Error initializing weldr API: unknown distro: fedora-34
```
 in the journal.

**Comment by atodorov** [comment]
@jrusz indeed you are correct. I've created tracking tickets for these issues and commented out the failing test jobs.

**Comment by atodorov** [comment]
@henrywang, @yih-redhat  Please see https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1282996618 near the end of the log: `Start UEFI VM`, then `Checking for SSH is ready to go` and after a bunch of retries it fails.  Currently this is the only piece blocking migrating this new test onto GitLab CI and IDK why it fails.

**Comment by henrywang** [comment]
> @henrywang, @yih-redhat Please see https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1282996618 near the end of the log: `Start UEFI VM`, then `Checking for SSH is ready to go` and after a bunch of retries it fails. Currently this is the only piece blocking migrating this new test onto GitLab CI and IDK why it fails.

Is that possible to run `ostree.sh` and `ostree-ng.sh` on different VM?
Test failed is caused by libvirt network. The test runs `ostree.sh` first, then runs `ostree-ng.sh`. `ostree.sh` configured `integration` libvirt network which only configured one IP and MAC bundle on DHCP. `ostree-ng.sh checked the same `integration` libvirt network, it found the network exist and running. So `ostree-ng.sh` will not create a new network. But `ostree-ng.sh` needs two IP and MAC bundles for both BIOS VM and UEFI VM.

**Comment by henrywang** [comment]
@atodorov, one more question. Will `ostree-ng.sh` still run if `ostree.sh` failed?
- `ostree.sh` is to test `rhel-edge-commit` image type.
- `ostree-ng.sh` is to test `rhel-edge-container` and `rhel-edge-installer` image types.

If `ostree-ng.sh` can't be run, it's better to make them running on separate VM(runner). Thanks.

**Comment by atodorov** [comment]
> @atodorov, one more question. Will `ostree-ng.sh` still run if `ostree.sh` failed?

With the latest changes to this PR yes!

**Review by jrusz — APPROVED** [review]
Looks OK to me.

**Pull request merged**
