### PR TITLE
github/workflows: downgrade golang to 1.12

### PR DESCRIPTION
**Pull request by msehnout**
We currently declare compatibility with golang 1.12 so we should also
use it in our CI. Once we agree that we would benefit from some features
in golang 1.13 or 1.14 we can bump it back.

Follow up to #495

### CODE REVIEW

**Comment by teg** [comment]
This makes sense to me. Coludn't access the Travis logs though, so don't know what's up there.

**Comment by msehnout** [comment]
> This makes sense to me. Coludn't access the Travis logs though, so don't know what's up there.

```
...
go: finding github.com/Azure/go-autorest/autorest/mocks v0.1.0

go: finding github.com/mattn/go-ieproxy v0.0.0-20190610004146-91bb50d98149

go: finding github.com/Azure/go-autorest/autorest/date v0.1.0

go: finding github.com/kr/pty v1.1.1

go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405

go: finding github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af

can't load package: package github.com/osbuild/osbuild-composer/cmd/osbuild-image-tests: build constraints exclude all Go files in /home/travis/build/osbuild/osbuild-composer/cmd/osbuild-image-tests

The command "go test -c -tags travis,integration -o osbuild-image-tests ./cmd/osbuild-image-tests" exited with 1.

0.01s$ sudo ./osbuild-image-tests -test.v test/cases/$TRAVIS_JOB_NAME*

sudo: ./osbuild-image-tests: command not found

The command "sudo ./osbuild-image-tests -test.v test/cases/$TRAVIS_JOB_NAME*" exited with 1.
```

I'm not yet sure what that means.

**Comment by ondrejbudai** [comment]
Running the `go test` with `GO111MODULE=on` could help... There was some changes in the modules behaviour between 1.12 and 1.13.

**Comment by msehnout** [comment]
> Running the `go test` with `GO111MODULE=on` could help... There was some changes in the modules behaviour between 1.12 and 1.13.

Thanks for suggestion. Unfortunatelly it didn't help.

**Comment by ondrejbudai** [comment]
`gimme` unsets the `GO111MODULE` variable, maybe setting it right before the `go test` command would fix it? https://github.com/travis-ci/gimme/blob/4d1d7250f02d103de60c7b91fe1df9dde4c64304/gimme#L920

**Comment by msehnout** [comment]
f32 RPM build fails because it does not use `updates-testing` repo any more. codecov fails with some weird decrease in code coverage, but I haven't changed any code in our codebase.

**Pull request merged**
