### PR TITLE
Use PackIt for building RPMs in COPR for PRs and commits to `main`

### PR DESCRIPTION
**Pull request by thozza**
SSIA

### CODE REVIEW

**Review by ondrejbudai — APPROVED** [review]

**Review by teg — DISMISSED** [review]

**Comment by ondrejbudai** [comment]
s390x is failing. :/

**Comment by thozza** [comment]
Apparently `go` segfaulted while building composer:
```
/var/tmp/rpm-tmp.n9Ed7P: line 41:   125 Segmentation fault      (core dumped) GOPATH="/builddir/build/BUILD/osbuild-composer-39/_build:${GOPATH:+${GOPATH}:}/usr/share/gocode" GO111MODULE=off go build -buildmode pie -compiler gc -tags="rpm_crashtraceback ${BUILDTAGS:-}" -ldflags "${LDFLAGS:-} -X github.com/osbuild/osbuild-composer/version=39 -B 0x$(head -c20 /dev/urandom|od -An -tx1|tr -d ' \n') -compressdwarf=false -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  '" -a -v -x -o _bin/osbuild-composer github.com/osbuild/osbuild-composer/cmd/osbuild-composer
```

**Comment by thozza** [comment]
I reproduced the issue locally. The `go` binary segfaults when building osbuild-composer RPMs. The issue is that I was not able to get any coredump from the crash. This is the command run by `mock`:
```
 /usr/bin/qemu-s390x-static /usr/bin/go build -buildmode pie -compiler gc -tags=rpm_crashtraceback  -ldflags  -X 'github.com/osbuild/osbuild-composer/internal/common.GitRev=52961dab2e144e42c1ac04eef5b02529d70fd615' -X 'github.com/osbuild/osbuild-composer/internal/common.RpmVersion=osbuild-composer-40-1.20211203git52961da.fc34.s390x' -X github.com/osbuild/osbuild-composer/version.commit=52961dab2e144e42c1ac04eef5b02529d70fd615 -X github.com/osbuild/osbuild-composer/version=40 -B 0xcfe4cc1d17c48cdb33dc28f86640683e535bca2a -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  ' -a -v -x -o _bin/osbuild-composer github.com/osbuild/osbuild-composer/cmd/osbuild-composer
```

I can disable s390x for now, but it is very unfortunate as the s390x will be needed for image test case generation once "dnf-json as a service" PR is merged 😕

**Comment by ondrejbudai** [comment]
I think that's the only way for now. :/ We need to think of a way to make the test case generation work with dnf-json-as-a-servce.

**Review by teg — APPROVED** [review]

**Pull request merged**
