### PR TITLE
schutzbot: move repo override into -test subpackage

### PR DESCRIPTION
**Pull request by teg**
This moves even more of the testing logic into the subpackage, ideally making it easier to re-run tests outside of schutzbot.

This should in particular make it easier for reverse dependency tests done (osbuild) and re-running tests in gating.

We still have work to do to make sure all tests use these repos, but then it should be very easy to update and/or override them all in one place.

### CODE REVIEW

**Review by larskarlitski — DISMISSED** [review]
Lovely. Thanks!

**Comment by henrywang** [comment]
Awesome!! Thanks @teg! :+1:

**Review by dvdhrm — APPROVED** [review]

**Review by ondrejbudai — APPROVED** [review]
nice!

**Review by gicmo — APPROVED** [review]
👍

**Review by msehnout — APPROVED** [review]
LGTM :+1:

**Pull request merged**
