### PR TITLE
re-enable cs9 runner for simplified installer

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <antoniomurdaca@gmail.com>

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by henrywang** [comment]
@runcom We need a new CS9 repo to have new coreos-installer.

**Comment by henrywang** [comment]
@runcom PR #3136 merged, I make a rebase on main to have new CS9 repo. Let's see what happens.

**Comment by henrywang** [comment]
@runcom The failure is due to bug  https://bugzilla.redhat.com/show_bug.cgi?id=2123611. The repo yesterday does not have fix included. We needs CS9 CentOS-Stream-9-20221121.0 compose to have this fix.

**Comment by henrywang** [comment]
@runcom I found PR https://github.com/osbuild/osbuild-composer/pull/3155. Let's try `20221124` repo and see what happens.

**Comment by henrywang** [comment]
@runcom Repo `20221124` works. The only failed case is not ostree related.

**Comment by runcom** [comment]
works again now :)

**Comment by henrywang** [comment]
@runcom We should change repo to `20221124`.  Repo `20221121` still has DNF error.

**Comment by henrywang** [comment]
All green now!

**Review by achilleas-k — APPROVED** [review]

**Pull request merged**
