### PR TITLE
schutzbot: akoutsou ssh keys

### PR DESCRIPTION
**Pull request by achilleas-k**

### CODE REVIEW

**Review by ondrejbudai — DISMISSED** [review]
Content good, typo in the PR title bad.

**Comment by achilleas-k** [comment]
> Content good, typo in the PR title bad.

At the cost of restarting CI, I had to fix the commit message as well

**Review by teg — DISMISSED** [review]

**Comment by ondrejbudai** [comment]
can you please rebase?

**Review by atodorov — DISMISSED** [review]

**Comment by ondrejbudai** [comment]
I guess we need one more rebase to include #1529? Sorry :/

**Comment by achilleas-k** [comment]
> I guess we need one more rebase to include #1529? Sorry :/

Yeah no worries.  Quick and easy.  Thanks for the reminder.

**Review by teg — APPROVED** [review]

**Pull request merged**
