### PR TITLE
Rhel84 add missing packages

### PR DESCRIPTION
**Pull request by jkozol**
The packages in the last imagefactory nightly differ from ours. The
following packages are now added:

oddjob
oddjob-mkhomedir
psmisc
authselect-compat
rng-tools
dbxtool

Also, the rngd and nfs-convert services are enabled.

This PR addresses issues listed in #1176 

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change

### CODE REVIEW

**Review by teg — APPROVED** [review]
Very nice! Are these all the ones you want to add, or a partial list? Will there also be follow-ups to remove some? I see in the ticket there are plenty more, but I guess many/most/all will be pulled in as deps of these?

**Comment by jkozol** [comment]
> Very nice! Are these all the ones you want to add, or a partial list? Will there also be follow-ups to remove some? I see in the ticket there are plenty more, but I guess many/most/all will be pulled in as deps of these?

@teg These are all the packages that I want to add. I will create separate PRs for enabling/disabling services and for removing packages (aka as adding them to our list of excluded packages)

**Comment by jkozol** [comment]
Also, is it okay to merge this since the test failures are unrelated to the changes?

**Comment by teg** [comment]
Yeah, if the failures are caused by flaky infrastructure, leave a brief comment about what's going on and why it is unrelated, then we can merge.

**Comment by jkozol** [comment]
The tests are failing due to issues with openstack being overloaded. This is not related to this rhel 8.4 specific PR.

**Pull request merged**
