### PR TITLE
GitLab CI: Add GCP &Vmware tests

### PR DESCRIPTION
**Pull request by atodorov**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by atodorov** [comment]
GCP test jobs reported PASS here: https://gitlab.com/osbuild/ci/osbuild-composer/-/pipelines/309751069 with some of the rest of the jobs removed for speed of execution.  PR updated to not remove other jobs afterwards.

**Comment by atodorov** [comment]
This PR is ready for review.

Notes:
- See previous link I posted for passing results
- Currently integration test job on CentOS failed. I've seen this multiple times/restarted other jobs as well and it is unrelated. The actual error comes from libvirt/qemu: `ERROR    internal error: unknown feature amd-sev-es` and is documented in https://bugzilla.redhat.com/show_bug.cgi?id=1961562

Let's merge if there are no objections and work on improving GitLab CI afterwards.

**Review by jrusz — COMMENTED** [review]
Looks good. I have one question though, are we really ready to remove Jenkins trigger? We're still missing `vmware.sh` test that is ran on RHEL-8 in Jenkins. I don't know how important that is, should be fairly easy to add later though.

**Comment by atodorov** [comment]
> Looks good. I have one question though, are we really ready to remove Jenkins trigger? 

Rather sooner than later. It will help reveal if something is broken/missing so it can be fixed faster. And also aleviate some of the pressure on our limited resources in PSI. Worst case scenario we revert the commit back so there's nothing to worry about. The Jenkins instance itself will still be operation for some time after all of the other projects have migrated away from it.

> We're still missing `vmware.sh` test that is ran on RHEL-8 in Jenkins. 

Dang it, good catch. I've added the vmware test but I need to figure out the credentials situation. Moved back to draft.

**Comment by jrusz** [comment]
> Dang it, good catch. I've added the vmware test but I need to figure out the credentials situation. Moved back to draft.

There are some credentials in Gitlab CI already, not sure if you added them now or they've been added before, but one issue I see here is that since it was ran only on RHEL-8 and since the integration tests are not split yet, it'll probably be failing on the other runners.

**Comment by atodorov** [comment]
FTR GitLab doesn't like one of our values b/c it contains characters it can't mask. I've requested that to be updated and need to wait until that's done before restarting any tests.

**Comment by thozza** [comment]
Great work @atodorov, thanks for adding testing for GCP. It seems that the GCP test is now working. Please let me know if there is anything that I should help with or review. Otherwise I'll wait for the VMware with any approval of this PR....

**Comment by atodorov** [comment]
vmware test reporting PASS in https://gitlab.com/osbuild/ci/osbuild-composer/-/pipelines/311253416, dropped the last commit and refreshed this PR. Ready for review.

**Review by jrusz — APPROVED** [review]
Looks good, failures in latest test run are unrelated and the added tests seem to be working as expected.

**Review by ondrejbudai — APPROVED** [review]

**Pull request merged**
