### PR TITLE
distro: add an alias for RHEL 8.7

### PR DESCRIPTION
**Pull request by ondrejbudai**
This won't work without https://github.com/osbuild/osbuild/pull/963 but since we don't have any tests for RHEL 8.7 yet, this should be fine.

This is the first step to implementing 8.7. After 8.6 is frozen, we can proceed with working on #2225 (that probably shouldn't be merged before the branching).

Signed-off-by: Ondřej Budai <ondrej@budai.cz>

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by thozza** [comment]
@ondrejbudai I guess that we should right away add an alias also for RHEL-9.1, right? 🤔

**Review by thozza — APPROVED** [review]
LGTM

**Review by gicmo — APPROVED** [review]
👍

**Comment by ondrejbudai** [comment]
Rebased to include #2271

**Review by thozza — APPROVED** [review]

**Review by achilleas-k — APPROVED** [review]
LGTM

**Pull request merged**
