### PR TITLE
Makefile for templates/openshift

### PR DESCRIPTION
**Pull request by schuellerf**
I just wanted to check #4102 locally.
maybe that's helpful for someone

### CODE REVIEW

**Review by croissanne — COMMENTED** [review]
Hmm I wonder if this makes sense to put in the makefile. The only reason we process them in the github workflow is so that kubelinter can do a very basic check. The processing of the template when actually deploying is something that is out of our hands. If we put it in the makefile, then i'd just consider it as a helper for the github workflow.

**Comment by schuellerf** [comment]
We could use it from GitHub Workflow but I just wanted to call it so see if there are syntax problems locally (avoid GitHub Action problems before pushing - the usual problem)

**Comment by bcl** [comment]
I like having the ability to run things from the Makefile. I'd also add a commit that converts the workflow to use the Makefile target so that things don't drift.

**Review by bcl — APPROVED** [review]
Looks Good!

**Review by bcl — APPROVED** [review]
Looks good!

**Pull request merged**
