### PR TITLE
update osbuild submodule

### PR DESCRIPTION
**Pull request by ondrejbudai**

### CODE REVIEW

**Comment by dvdhrm** [comment]
@ondrejbudai It looks like osbuild fixed a double-output of the grub2 boot-id. See the failed travis-test. Can you adjust the tests with this PR?

**Comment by ondrejbudai** [comment]
Fixed ;)

**Comment by dvdhrm** [comment]
Ah, right, it was:

```
commit b3ae34b07e791447eecdb1810d1af329b87b24eb
Author: Christian Kellner <christian@kellner.me>
Date:   Fri Jan 17 15:33:24 2020 +0100

    stages/grub2: make $boot just an alias for $root
```

**Comment by ondrejbudai** [comment]
Thanks for pointing out! I added the commit hash into the commit message.

**Pull request merged**
