### PR TITLE
8.4 cleanup after transitioning to 8.5 

### PR DESCRIPTION
**Pull request by atodorov**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change

### CODE REVIEW

**Review by teg — APPROVED** [review]
This makes sense to me to do sooner rather than later, but we expect this to fail for the time being as we don't have the required 8.5 support, right?

**Comment by atodorov** [comment]
> This makes sense to me to do sooner rather than later, but we expect this to fail for the time being as we don't have the required 8.5 support, right?

We don't have any cloud images tagged with `85` which means no Jenkins nodes to run the jobs. Otherwise I'm realizing I need to update the image manifest files. The rest should work like before IMO.

**Comment by atodorov** [comment]
Needs #1351 first!

**Comment by teg** [comment]
#1351 merged, and this is ready for rebase.

**Comment by atodorov** [comment]
> #1351 merged, and this is ready for rebase.

I think we'll also need to wait for #1401 before continuing with the rest of this PR, but let's see what the results say.

**Comment by teg** [comment]
#1401 has now been merged.

**Comment by atodorov** [comment]
@chris1984 can you please check vcenter. I got 2 consecutive failures from the vmware test jobs and what I see in the logs is:
```
Uploading osbuild-composer-vmware-test-ea232482-9d25-41bd-81bd-38be1570ef48.vmdk... (100%, 12.4MiB/s)
[K[16-08-21 12:25:12] Uploading osbuild-composer-vmware-test-ea232482-9d25-41bd-81bd-38be1570ef48.vmdk... OK
Aug 16 12:25:13 ip-10-30-18-19.us-east-1.aws.redhat.com osbuild-worker[23888]: 2021/08/16 12:25:13 Job 2cce9472-8f7a-4194-b35d-68321cfddd1e finished
Aug 16 12:25:13 ip-10-30-18-19.us-east-1.aws.redhat.com osbuild-worker[23888]: Waiting for a new job...
[1;32mðŸ’¬ Getting compose log and metadata[0m
[1;32mðŸ‘·ðŸ» Building VM in vSphere[0m
/usr/libexec/tests/osbuild-composer/vmware.sh: line 186: 23969 Terminated              sudo journalctl -af -n 1 -u "${WORKER_UNIT}"
[1;32mGetting IP of created VM[0m
/tmp/govc: please specify a datacenter
```

And for CI we've got `GOVMOMI_DATACENTER=RH_Engineering` which used to work before.  I am suspecting some temporary issue in vcenter.

**Comment by atodorov** [comment]
@teg, @ondrejbudai please review. The failures are not related IMO.

**Comment by ondrejbudai** [comment]
I wonder what to do with these 8.4 manifests. We should still test 8.4 on the CI because we're building images of 8.4 in the service. We should probably regenerate the test manifest with 8.4 GA content (currently, the manifests are generated from an outdated nightly).

**Comment by atodorov** [comment]
> I wonder what to do with these 8.4 manifests. We should still test 8.4 on the CI because we're building images of 8.4 in the service. We should probably regenerate the test manifest with 8.4 GA content (currently, the manifests are generated from an outdated nightly).

Hmm fair point. Sounds like I should drop the last commit in this case.

**Review by jrusz — APPROVED** [review]
LGTM

**Pull request merged**
