### PR TITLE
worker API: introduce job types and architecture

### PR DESCRIPTION
**Pull request by larskarlitski**
This is an effort to future-proof the worker API. It removes the assumption that all jobs are osbuild jobs and requires a worker to pass both the jobs it can handle and the architecture it runs on.

### CODE REVIEW

**Review by teg — DISMISSED** [review]
Perfect!

**Comment by larskarlitski** [comment]
Update to resolve the conflict and set a correct list of accepted job types.

**Review by teg — DISMISSED** [review]
Thanks! (CI failures are, again, unrelated and caused by the ostree tests).

**Comment by larskarlitski** [comment]
> Thanks! (CI failures are, again, unrelated and caused by the ostree tests).

There was a failure in `aws.sh` as well, which might have been a flake. I restarted the tests to make sure.

**Comment by larskarlitski** [comment]
> There was a failure in `aws.sh` as well, which might have been a flake. I restarted the tests to make sure.

This was an actual bug (yay testing and thanks for tracking it down @ondrejbudai). I've copied the logic to assemble job types from `osbuild-composer` to `osbuild-composer-cloud`. I didn't bother sharing the code because we're about to merge the two.

**Comment by larskarlitski** [comment]
That last fix did it indeed. The only remaining failure is due to https://github.com/osbuild/osbuild-composer/issues/997.

**Review by teg — APPROVED** [review]
Nice!

**Pull request merged**
