### PR TITLE
repositories: distinguish between RHEL8 beta and GA

### PR DESCRIPTION
**Pull request by teg**
We need the same RPMs to work equally well on a host running a beta
release (pulling beta content) as on a machine running GA (pulling GA
content). Detect this at run-time and point at the right repository.

Testing this is a bit hairy as we are building 8.3 images, but obviously
there is currently no 8.3 content at the GA URLs.

Test on RHEL-8.3 Beta:
```
# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 Beta (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:beta"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3 Beta"

# composer-cli sources info baseos
[baseos]
name = "baseos"
type = "yum-baseurl"
url = "https://cdn.redhat.com/content/beta/rhel8/8/x86_64/baseos/os"
check_gpg = true
check_ssl = true
system = true
```

Test on RHEL-8.2 GA:
```
# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION="8.2"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"

# composer-cli sources info baseos
[baseos]
name = "baseos"
type = "yum-baseurl"
url = "https://cdn.redhat.com/content/dist/rhel8/8/x86_64/baseos/os"
check_gpg = true
check_ssl = true
system = true
```

### CODE REVIEW

**Comment by teg** [comment]
PSI failure due to resource exhaustion is unrelated.

**Comment by teg** [comment]
PSI failure due to resource exhaustion is unrelated.

**Review by ondrejbudai — APPROVED** [review]
Looks good to me, thanks!

**Comment by atodorov** [comment]
> PRETTY_NAME="Red Hat Enterprise Linux 8.3 Beta (Ootpa)"

This is going to break as soon as we hit RC phase and the "Beta" string is removed. At that time the content still won't be available on CDN so we're back to overwriting `rhel-8.json`. 

I don't really see the point here. It's very easy to modify the sources or add additional ones if need be so why make it more complex ?

**Pull request merged**
