### PR TITLE
test: Install package sssd in all edge images for BZ#2088459

### PR DESCRIPTION
**Pull request by henrywang**
Update test to install package `sssd` in all edge images for regression due to bug [BZ#2088459](https://bugzilla.redhat.com/show_bug.cgi?id=2088459)

### CODE REVIEW

**Comment by henrywang** [comment]
All ostree tests are green! The other failure are not related with this PR.

**Review by achilleas-k — DISMISSED** [review]
LGTM

**Comment by achilleas-k** [comment]
All the test failures are about spot instance availability, except the new regression test.  I've seen that failure before and I'm still trying to figure out how it happens.

**Comment by henrywang** [comment]
@gicmo @achilleas-k All green now.

**Review by achilleas-k — APPROVED** [review]

**Pull request merged**
