### PR TITLE
GH Actions: Use upstream Fedora containers

### PR DESCRIPTION
**Pull request by major**
Work around the quay.io issues by using the standard Fedora containers.
Also, make most of the dnf operations a little quieter to make it easier
to find problems.

Signed-off-by: Major Hayden <major@redhat.com>

### CODE REVIEW

**Comment by major** [comment]
Essentially the same change as osbuild/osbuild#411.

**Comment by teg** [comment]
What's the difference between the containers? Why did we have our own in quay to begin with? (I seem to remember there was a reason)

**Comment by teg** [comment]
Wasn't the idea to have pre created containers with all dependencies installed so they would be stable between runs?

**Comment by ondrejbudai** [comment]
Hmm, good point... Let's wait for @major

**Comment by major** [comment]
Well, to be honest, now that we're doing mock builds in Jenkins, we probably don't need these jobs any longer. Should we just remove them?

**Comment by teg** [comment]
> Well, to be honest, now that we're doing mock builds in Jenkins, we probably don't need these jobs any longer. Should we just remove them?

Hehe, even better! Let's!

**Comment by major** [comment]
> Hehe, even better! Let's!

https://tenor.com/view/kevin-hart-its-about-to-go-down-calm-before-the-storm-gif-4420127

**Pull request closed without merging**
