### PR TITLE
rhel9: enable & fix ostree installer test

### PR DESCRIPTION
**Pull request by diaasami**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by teg — DISMISSED** [review]
Thanks!

**Review by ondrejbudai — APPROVED** [review]
Thanks1

**Comment by ondrejbudai** [comment]
Ah, I think this needs a bit more work. Can you please look into it, @diaasami?

**Comment by diaasami** [comment]
I am, thanks

**Review by achilleas-k — COMMENTED** [review]
Looks good, thanks.

Couple of notes:
- Commit messages could use some fixing up.
- It might be worth porting over the package set handling change from 8.5 as well.
The changes to the way package sets are defined and merged changed in 8.5 to accommodate the arch-specific sets for the installers.  I think with this PR it makes sense to copy over the same change as well.  It might be a bit tricky to reconcile the changes that were already made to the RHEL 9.0 package sets, but I think it's worth doing now that we need them.

**Comment by diaasami** [comment]
Blocked by rhel90 not having `coreos-installed` & `coreos-installer-bootinfra` packages yet

**Pull request closed without merging**
