### PR TITLE
🐣 Add initial RHEL 8.3 support

### PR DESCRIPTION
**Pull request by major**

### CODE REVIEW

**Comment by major** [comment]
> Oh, the test file needs to be in the `rhel83_test` package.

Yup, just saw that and pushed more code. :hugs:

**Comment by major** [comment]
schutzbot

**Comment by major** [comment]
schutzbot

**Comment by major** [comment]
So it looks like dnf-json fails with:

```
=== RUN   TestCrossArchDepsolve/fedora-30/aarch64/ami
    TestCrossArchDepsolve/fedora-30/aarch64/ami: main_test.go:75: 
        	Error Trace:	main_test.go:75
        	Error:      	Received unexpected error:
        	            	unexpected end of JSON input
        	Test:       	TestCrossArchDepsolve/fedora-30/aarch64/ami
```

and osbuild-tests fails with:

```
=== RUN   TestEverything
    TestEverything: main_test.go:104: 
        	Error Trace:	main_test.go:104
        	            				main_test.go:61
        	Error:      	Not equal: 
        	            	expected: "FAILED"
        	            	actual  : "FINISHED"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-FAILED
        	            	+FINISHED
        	Test:       	TestEverything
        	Messages:   	Unexpected compose result: FAILED
```

**Comment by major** [comment]
Verifying that Jenkins is behaving in #520

**Comment by ondrejbudai** [comment]
schutzbot

**Comment by ondrejbudai** [comment]
schutzbot

**Comment by major** [comment]
@ondrejbudai Děkuji!

**Pull request merged**
