### PR TITLE
RHEL-9.0 API testing fixes

### PR DESCRIPTION
**Pull request by thozza**
- test/api.sh: use 'ec2-user' to log into RHEL-9 AMI images
- test/api.sh: run cloud CLI tools from a container
- CI: enable API testing on RHEL-9
- test/repos: update el8.5 rpmrepo snapshots used by CI to 20210827
- test/repos: update el9.0 rpmrepo snapshots used by CI to 20210827

Resolves: #1631

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by teg — APPROVED** [review]

**Comment by thozza** [comment]
There seems to be issue with the EPEL-9 repos installed on the RHEL-9 testing system. I'll have to investigate it further... 😕

**Comment by jrusz** [comment]
> There seems to be issue with the EPEL-9 repos installed on the RHEL-9 testing system. I'll have to investigate it further...

This should fix it https://github.com/osbuild/osbuild-composer/pull/1647/commits/b1ac597893aa8e6b7b6f63060e3b6e4e97ad3c6d

**Comment by thozza** [comment]
Thanks @jrusz ! What is the plan with #1647, which includes the change? I'm wondering what is the best course of action here, probably wait for #1647 to get merged first, if it will happen in the near future.

**Comment by jrusz** [comment]
> Thanks @jrusz ! What is the plan with #1647, which includes the change? I'm wondering what is the best course of action here, probably wait for #1647 to get merged first, if it will happen in the near future.

Well the plan is to get it merged ASAP :D ... I'm not sure about my chages WRT the testing if that can be improved or if it's fine (not skilled enought in GO to tell) so I can see two ways to get this resolved either you take the commit from me which will unblock you, merge first and I'll just rebase which is fine with me or help me get my PR merged sooner by reviewing/providing some feedback about what I did there so that I can get it merged :)

**Review by teg — APPROVED** [review]
Thanks!

**Pull request merged**
