### PR TITLE
Investigate how often the openstack test fails

### PR DESCRIPTION
**Pull request by ondrejbudai**
do not merge this ever

### CODE REVIEW

**Comment by msehnout** [comment]
50 successful attempts? I find it hard to believe :D

**Comment by ondrejbudai** [comment]
They added more hardware to the PSI this weekend, maybe this issue might be gone without any changes on our side...

**Comment by teg** [comment]
Thanks for looking into this. How about we make the openstack not actually fail CI, but instead just count how often it fails/succeeds in our regular runs, and if we see the stats improve we can reenable it?

**Comment by ondrejbudai** [comment]
See #1254

**Pull request closed without merging**
