### PR TITLE
image tests: update GPG keys used for RHEL-9.0 repos

### PR DESCRIPTION
**Pull request by thozza**
SHA-1 key is no longer supported, update it with a new one from
redhat-release.

Related rhbz#2058497

Signed-off-by: Tomas Hozza <thozza@redhat.com>

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by achilleas-k — APPROVED** [review]
I haven't checked every single key that it's the correct one but it all looks good to me :)

**Review by jrusz — APPROVED** [review]
Agree with @achilleas-k, keys look good. I also tried running the image-tests in a VM and came across some issues, but that' not what this change is about, right? For example this:
```
                                Diff:                                                                                                                                                                                 
                                --- Expected                                                                                                                                                                          
                                +++ Actual                                                                                                                                                                            
                                @@ -691,3 +691,3 @@                                                                                                                                                                   
                                  (string) (len=7) "selinux": (map[string]interface {}) (len=2) {                                                                                                                     
                                -  (string) (len=16) "context-mismatch": ([]interface {}) (len=1) {                                                                                                                   
                                +  (string) (len=16) "context-mismatch": ([]interface {}) (len=3) {                                                                                                                   
                                    (map[string]interface {}) (len=3) {                                                                                                                                               
                                @@ -696,2 +696,12 @@                                                                                                                                                                  
                                     (string) (len=8) "filename": (string) (len=5) "/proc"                                                                                                                            
                                +   },                                                                                                                                                                                
                                +   (map[string]interface {}) (len=3) {                                                                                                                                               
                                +    (string) (len=6) "actual": (string) (len=32) "system_u:object_r:unlabeled_t:s0",                                                                                                 
                                +    (string) (len=8) "expected": (string) (len=41) "system_u:object_r:usbguard_unit_file_t:s0",                                                                                      
                                +    (string) (len=8) "filename": (string) (len=40) "/usr/lib/systemd/system/usbguard.service"                                                                                        
                                +   },                                                                                                                                                                                
                                +   (map[string]interface {}) (len=3) {                                                                                                                                               
                                +    (string) (len=6) "actual": (string) (len=32) "system_u:object_r:unlabeled_t:s0",                                                                                                 
                                +    (string) (len=8) "expected": (string) (len=36) "system_u:object_r:usbguard_exec_t:s0",                                                                                           
                                +    (string) (len=8) "filename": (string) (len=25) "/usr/sbin/usbguard-daemon"                                                                                                       
                                    }                                                                                                                                                                                 
                Test:           TestImages/rhel_90-x86_64-edge_commit_rt-boot.json/image_info                                                                                                                         
--- FAIL: TestImages (436.28s)                                                                                                                                                                                        
    --- FAIL: TestImages/rhel_90-x86_64-edge_commit_rt-boot.json (435.56s)                                                                                                                                            
        --- FAIL: TestImages/rhel_90-x86_64-edge_commit_rt-boot.json/image_info (30.92s)
```

**Comment by achilleas-k** [comment]
> Agree with @achilleas-k, keys look good. I also tried running the image-tests in a VM and came across some issues, but that' not what this change is about, right? For example this:
> 
> ```
>                                 Diff:                                                                                                                                                                                 
>                                 --- Expected                                                                                                                                                                          
>                                 +++ Actual                                                                                                                                                                            
>                                 @@ -691,3 +691,3 @@                                                                                                                                                                   
>                                   (string) (len=7) "selinux": (map[string]interface {}) (len=2) {                                                                                                                     
>                                 -  (string) (len=16) "context-mismatch": ([]interface {}) (len=1) {                                                                                                                   
>                                 +  (string) (len=16) "context-mismatch": ([]interface {}) (len=3) {                                                                                                                   
>                                     (map[string]interface {}) (len=3) {                                                                                                                                               
>                                 @@ -696,2 +696,12 @@                                                                                                                                                                  
>                                      (string) (len=8) "filename": (string) (len=5) "/proc"                                                                                                                            
>                                 +   },                                                                                                                                                                                
>                                 +   (map[string]interface {}) (len=3) {                                                                                                                                               
>                                 +    (string) (len=6) "actual": (string) (len=32) "system_u:object_r:unlabeled_t:s0",                                                                                                 
>                                 +    (string) (len=8) "expected": (string) (len=41) "system_u:object_r:usbguard_unit_file_t:s0",                                                                                      
>                                 +    (string) (len=8) "filename": (string) (len=40) "/usr/lib/systemd/system/usbguard.service"                                                                                        
>                                 +   },                                                                                                                                                                                
>                                 +   (map[string]interface {}) (len=3) {                                                                                                                                               
>                                 +    (string) (len=6) "actual": (string) (len=32) "system_u:object_r:unlabeled_t:s0",                                                                                                 
>                                 +    (string) (len=8) "expected": (string) (len=36) "system_u:object_r:usbguard_exec_t:s0",                                                                                           
>                                 +    (string) (len=8) "filename": (string) (len=25) "/usr/sbin/usbguard-daemon"                                                                                                       
>                                     }                                                                                                                                                                                 
>                 Test:           TestImages/rhel_90-x86_64-edge_commit_rt-boot.json/image_info                                                                                                                         
> --- FAIL: TestImages (436.28s)                                                                                                                                                                                        
>     --- FAIL: TestImages/rhel_90-x86_64-edge_commit_rt-boot.json (435.56s)                                                                                                                                            
>         --- FAIL: TestImages/rhel_90-x86_64-edge_commit_rt-boot.json/image_info (30.92s)
> ```

That's a known issue.  You need to label image-info with the same selinux labels/context as osbuild.
The `generate-all-test-cases` script does this automatically, but if you're running `generate-test-cases` individually, you can do it with:
```
osbuildcon=$(matchpathcon -n /usr/bin/osbuild)
sudo chcon "${osbuildcon}" "${composerdir}/tools/image-info"
```

**Comment by thozza** [comment]
Thanks @achilleas-k for the explanation. I'll add that this is documented in https://github.com/osbuild/osbuild-composer/tree/main/test#image-tests

**Comment by jrusz** [comment]
I've rebased this PR, I thought it was in already, I need it to update the snapshots for el9

**Pull request merged**
