### PR TITLE
Enables 'fdo.di_mfg_string_type_mac_iface' variable passing

### PR DESCRIPTION
**Pull request by djach7**
Adds implementation of the 'fdo.di_mfg_string_type_mac_iface' dracut variable to allow simplified installer images to pass this value to the manufacturing-client.service.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by djach7** [comment]
This PR is linked to https://github.com/osbuild/images/pull/208, which enables 'fdo.di_mfg_string_type_mac_iface' passing in the images repo.

**Comment by miabbott** [comment]
See https://github.com/osbuild/osbuild-composer/pull/3723 for an example of how to vendor in a copy of `osbuild/images`  which may allow the CI to run successfully

**Comment by croissanne** [comment]
Rebased to prevent OCI private key leaking. Apologies :(

**Review by achilleas-k — APPROVED** [review]
I did a minor commit rewrite and split for cleaner history.
LGTM.

**Review by achilleas-k — APPROVED** [review]

**Pull request merged**
