### PR TITLE
distro: fix failed image build due to SELinux

### PR DESCRIPTION
**Pull request by msehnout**
Fixes: https://github.com/osbuild/osbuild-composer/issues/798
Depends on: #805

See commit messages for details.

### CODE REVIEW

**Comment by msehnout** [comment]
CI failures are coming from `curl` as usual. Otherwise I think it should be fine. Can you please take a look @teg ?

**Comment by teg** [comment]
I think this is ready to go in, though I think it needs a rebase to pick up some CI fix (I think the tests pass but the reporting is wrong).
To make it easier to follow, I suggest reordering the PR something like this (feel free to order them differently of course, just a suggestion if you are going to rebase anyway):
 - preparatory patches (test case generation refactoring, printing debug info on test failure)
 - the functional changes (buildroot labelling + cp labelling)
 - one patch updating all the test cases (ideally would be done as part of the patches introducing the changes making the test updates necessary, but since there are two patches in this PR, that would probably not be worth it). Squash any fixes together into one patch, and explain what was done (probably just re-ran the generation). As aarch64 image tests are not ran in our CI, leave a comment why this is still ok (you ran them manually as part of generating the test cases)
 - bump the spec file

**Comment by msehnout** [comment]
> I think this is ready to go in, though I think it needs a rebase to pick up some CI fix (I think the tests pass but the reporting is wrong).
> To make it easier to follow, I suggest reordering the PR something like this (feel free to order them differently of course, just a suggestion if you are going to rebase anyway):
> 
>     * preparatory patches (test case generation refactoring, printing debug info on test failure)
> 
>     * the functional changes (buildroot labelling + cp labelling)
> 
>     * one patch updating all the test cases (ideally would be done as part of the patches introducing the changes making the test updates necessary, but since there are two patches in this PR, that would probably not be worth it). Squash any fixes together into one patch, and explain what was done (probably just re-ran the generation). As aarch64 image tests are not ran in our CI, leave a comment why this is still ok (you ran them manually as part of generating the test cases)
> 
>     * bump the spec file

I think the bump should go first because without osbuild > 18, the `labels` field won't work. Is it ok like it is now?

**Comment by msehnout** [comment]
The test cases are not working, because they are already outdated. I'm not sure we want to commit to updating them because this patch introduced `updates` repositories:
4b0409df5b8128dbcf3c83f67893720840342e62
If we wanted to keep track od this repo, we would have to update the test-cases all the time. Maybe we could deploy our own mirror, @major ?

**Comment by major** [comment]
@msehnout That's possible, but it may be better to just regenerate the test cases without updates. I forgot that they would disappear in Fedora after they are updated again. 🤦🏻‍♂️

**Comment by msehnout** [comment]
I regenerated the test cases and ran them. It went just fine, but I don't think it is necessary to update them until we agree on the path forward. If that is ok with you @teg , I  would not block this PR on this issue.

**Pull request merged**
