### PR TITLE
schutzbot: test against EL8 nightly builds

### PR DESCRIPTION
**Pull request by atodorov**
# Description

Reopening of #976 since it was closed due to branch rename + rebased onto latest changes.

### CODE REVIEW

**Comment by atodorov** [comment]
Tested as PR pipeline - PASS:
https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/PR-1086/1/pipeline/138

Tested as cron pipeline - PASS:
https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/PR-1086/2/pipeline/82/

However the cron logs don't appear to show usage of the nightly build rpms so that needs investigation.

**Comment by ondrejbudai** [comment]
I rebased this PR on top of the current `main`. Hopefully, this fixes the pipeline. :crossed_fingers:

**Comment by atodorov** [comment]
First successful nightly test:
https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/PR-1086/123/pipeline

**Review by ondrejbudai — APPROVED** [review]
Thanks!

**Pull request merged**
