### PR TITLE
Update test suite after rebase to weldr-client-35.9

### PR DESCRIPTION
**Pull request by atodorov**
in order to avoid failures in nightly pipelines b/c JSON format has changed

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by jrusz — APPROVED** [review]

**Comment by atodorov** [comment]
Nightly CI pipeline: https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/pipelines/783186155

**Review by jrusz — CHANGES_REQUESTED** [review]
`/usr/libexec/osbuild-composer-test/libvirt_test.sh: line 169: get_build_info: command not found` in the nightly pipelines. I guess the common script is not sourced.

This should help: `source /usr/libexec/tests/osbuild-composer/shared_lib.sh`

**Comment by jrusz** [comment]
I don't understand where this comes from:
```
/usr/libexec/osbuild-composer-test/libvirt_test.sh: line 13: /usr/libexec/tests/osbuild-composer/shared_lib: No such file or directory
```
other test scripts use the exact same line and are fine.

**Comment by jrusz** [comment]
Oh, it's probably missing `.sh`

**Review by thozza — APPROVED** [review]

**Comment by atodorov** [comment]
@thozza , @achilleas-k the regular pipeline reports pass but the nightly pipeline still fails with

```
jq: error (at /tmp/tmp.5qFeCFQ0pk/compose-info-osbuild-composer-qemu-test-84749d9a-9b5a-44f7-9204-fdd547881440.json:4641): Cannot index array with string "body"
```

see https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/3814296429. I see the same code snippet used in other locations, for example `cases/azure.sh` which is passing. Any ideas ?

**Comment by jrusz** [comment]
`libvirt.sh` now passes but the s3 tests are still failing and it seems it's because they have their own implementation of the `get_build_info` function https://github.com/osbuild/osbuild-composer/blob/main/tools/s3_test.sh#L17

**Comment by atodorov** [comment]
@thozza nightly pipeline is passing except vmware job, see https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/pipelines/790084179. Please admin merge this PR.

**Comment by thozza** [comment]
> @thozza nightly pipeline is passing except vmware job, see https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/pipelines/790084179. Please admin merge this PR.

Thanks. There were two failed "regression-*" jobs in the regular CI pipeline. I rescheduled them. Will merge this PR once only the VSphere jobs will be failed.

**Review by thozza — APPROVED** [review]

**Review by jrusz — APPROVED** [review]
Refreshing my approval to be relevant again :)

**Comment by thozza** [comment]
Only VSphere jobs failed. Based on team discussion admin-merging this one.

**Pull request merged**
