### PR TITLE
Testing with rhel-9.5 nightly

### PR DESCRIPTION
**Pull request by atodorov**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the READMEs [listed here](https://github.com/osbuild/osbuild.github.io/blob/main/readme-list)
  - [ ] submit a PR for the [osbuild.org website](https://github.com/osbuild/osbuild.github.io/) repository if this PR changed any behavior not covered by the automatically updated READMEs

### CODE REVIEW

**Comment by croissanne** [comment]
Let's drop 8.10 nightlies?

**Review by jrusz — APPROVED** [review]
Added some comments, but looking at the commits it's supposed to be a temporary change so not really necessary to address them. Also is edge testing ready to be switched? Otherwise LGTM

**Comment by atodorov** [comment]
> Also is edge testing ready to be switched?

That IDK, see https://redhat-internal.slack.com/archives/C0235DZB0DT/p1717663941739349

**Review by achilleas-k — COMMENTED** [review]
LGTM but I agree with Jakub's comments for skipping the run entirely.

**Comment by achilleas-k** [comment]
> LGTM but I agree with Jakub's comments for skipping the run entirely.

Oh, I just realised the nightly rule was already dropped for those tests.

**Review by achilleas-k — DISMISSED** [review]
LGTM

**Review by jrusz — DISMISSED** [review]
Dropping the nightly rules will just remove it from the scheduled nightly, you need to update the blacklist regex above in order to remove it from the regular pipelines as well. The `generic_s3` part seems to have it for example,  but like I said since this is temporary and there is a ticket to revert it later I don't see it as blocking.

**Review by jrusz — APPROVED** [review]
Great, the regression test is now not scheduled in CI :). LGTM

**Pull request merged**
