### PR TITLE
test: Add installer test on BIOS VM

### PR DESCRIPTION
**Pull request by henrywang**
According to @teg's suggestion:
> I agree UEFI is the most important to test, and we have now some coverage of both BIOS and UEFI, which is great.
> I wonder, should we also test our installer on BIOS though? Now only the commits are tested on BIOS with the standard installer, but not the one we produce? That would anyway be a separate PR.

This PR will test installer on both BIOS and UEFI VM.

### CODE REVIEW

**Review by teg — APPROVED** [review]
thanks!

**Review by atodorov — APPROVED** [review]

**Comment by henrywang** [comment]
__All green__ now.

**Review by achilleas-k — APPROVED** [review]
Thanks.  LGTM.

**Comment by achilleas-k** [comment]
Build failures are a little strange.  One hit the timeout (12h) and the ostree tests failed at the end when pushing artifacts.

**Comment by henrywang** [comment]
> Build failures are a little strange. One hit the timeout (12h) and the ostree tests failed at the end when pushing artifacts.
> 
> I imagine it's GitLab specific since the PSI builds are green.

The ostree test failure reason is the one package inside redhat can't be downloaded. @ondrejbudai All GitLab CI runner can't access resource inside redhat, right? Thanks.

**Comment by henrywang** [comment]
@ondrejbudai, looks [`ostree-ng.sh`](https://github.com/osbuild/osbuild-composer/blob/ef0105945a314daf30de30f36219cde1a4e95435/schutzbot/Jenkinsfile#L585) test is not included in GitLab CI. Could you please take a look? Thanks.

**Comment by ondrejbudai** [comment]
GitLab machines can access internal stuff. I think that was a network failure, I restarted both jobs. No need to wait for them though if you want to merge this soon. ;)

**Comment by henrywang** [comment]
Thanks @ondrejbudai! All GREEN now.

**Pull request merged**
