### PR TITLE
dnf-json codestyle cleanup

### PR DESCRIPTION
**Pull request by achilleas-k**
While working on other things, I did some cleanup of `dnf-json`.  Since it's a pretty important component of the service, I think it would be good to do a quick `pylint` run on it in the CI workflows.

### CODE REVIEW

**Review by ondrejbudai — APPROVED** [review]

**Review by thozza — DISMISSED** [review]
Great stuff ❤️

**Comment by achilleas-k** [comment]
Rebased on `main`

**Review by lavocatt — APPROVED** [review]
Thanks a lit for doing this! :100:

**Review by gicmo — APPROVED** [review]
Love it! 🐍

**Comment by gicmo** [comment]
Only tests that failed are installer tests.

**Pull request merged**
