### PR TITLE
Pin the `staticfiles` Go dep in devcontainer.

### PR DESCRIPTION
**Pull request by supakeen**
The staticfiles dependency updated to support Go 1.18 generics in the
2022.1 release. This prevents the devcontainer (which has Go 1.16) from
being built. This pins to the latest release of staticfiles which builds
on 1.16.

Another option would be to bump Go to 1.18 in the devcontainer which would
allow for the dep to be installed `@latest`.

As this is a developer container I'm unsure how the checklist below
applies.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by ondrejbudai** [comment]
Idea: Fedora 36 ships with Go 1.18, we can switch to that (the GA is very near :crossed_fingers:, I'm fine with switching to it now).

Note that `osbuild-composer` still needs to be buildable by Go 1.16 until Fedora 35 is EOL (Tue 2022-11-15) but for development, I don't mind using the latest and greatest.

**Comment by supakeen** [comment]
@ondrejbudai That seems like a good option, I've force-pushed the change to fedora:36 instead, the containers luckily still work afterwards. Are these included in tests?

**Comment by ondrejbudai** [comment]
Nope, they aren't. FTR, we check if the code works on Fedora 35 (and thus Go 1.16) in multiple tests, so it's very hard to sneak incompatible code in.

**Review by ondrejbudai — APPROVED** [review]
Thanks for this! It's always lovely when dev-oriented tools just works. :-)

(admin-merging this, `.devcontainer` isn't covered)

**Pull request merged**
