### PR TITLE
Update fedora-33 test repository

### PR DESCRIPTION
**Pull request by yuxisun1217**
The old fedora-33 repo contains an old version of WALinuxAgent, which has a critical issue that fails to provision Fedora 33 on Azure. The new repo https://rpmrepo.osbuild.org/v2/mirror/public/f33/f33-x86_64-updates-released-20210526 has the new version WALinuxAgent-2.2.52-1.fc33 that includes the fix.

Signed-off-by: Yuxin Sun <yuxisun@redhat.com>

This pull request includes:

- [x] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by ondrejbudai — DISMISSED** [review]
Looks good!

**Review by atodorov — DISMISSED** [review]

**Comment by yuxisun1217** [comment]
This PR cannot pass the OSTree test because when "sudo rpm-ostree upgrade" it reports "error: Bus owner changed, aborting. This likely means the daemon crashed; check logs with `journalctl -xe`."

**Comment by yuxisun1217** [comment]
> This PR cannot pass the OSTree test because when "sudo rpm-ostree upgrade" it reports "error: Bus owner changed, aborting. This likely means the daemon crashed; check logs with `journalctl -xe`."
> 
> Print rpm-ostree status and journal log in ostree.sh to see what happened.

Printed debug log in https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1372529554 :
```
error: Bus owner changed, aborting. This likely means the daemon crashed; check logs with `journalctl -xe`.
State: idle
Deployments:
  ostree://fedora-iot-commit:fedora/33/x86_64/iot
                 Timestamp: 2021-06-24T01:46:23Z
                    Commit: f3ad26afb2864bbfe0e4aab5e5489d6d14d11b84e96c1ca13681b90d13dbca8a
Bail out! rpm-ostreed:ERROR:src/lib/rpmostree-package.c:251:_rpm_ostree_package_list_for_commit: assertion failed (pkglist->len > 0): (0 > 0)
**
rpm-ostreed:ERROR:src/lib/rpmostree-package.c:251:_rpm_ostree_package_list_for_commit: assertion failed (pkglist->len > 0): (0 > 0)
bash: line 1:  1106 Aborted                 sudo rpm-ostree status
-- Logs begin at Thu 2021-06-24 01:39:21 UTC, end at Thu 2021-06-24 01:47:31 UTC. --
Jun 24 01:47:31 vm rpm-ostree[1111]: In idle state; will auto-exit in 60 seconds
Jun 24 01:47:31 vm rpm-ostree[1111]: client(id:cli dbus:1.31 unit:session-3.scope uid:0) vanished; remaining=0
Jun 24 01:47:30 vm rpm-ostree[1111]: client(id:cli dbus:1.31 unit:session-3.scope uid:0) added; new total=1
Jun 24 01:47:30 vm systemd[1]: Started rpm-ostree System Management Daemon.
Jun 24 01:47:30 vm rpm-ostree[1111]: In idle state; will auto-exit in 63 seconds
Jun 24 01:47:30 vm rpm-ostree[1111]: Reading config file '/etc/rpm-ostreed.conf'
Jun 24 01:47:30 vm systemd[1]: Starting rpm-ostree System Management Daemon...
Jun 24 01:47:30 vm systemd[1]: rpm-ostreed.service: Consumed 7.138s CPU time.
Jun 24 01:47:30 vm systemd[1]: rpm-ostreed.service: Failed with result 'signal'.
Jun 24 01:47:30 vm systemd[1]: rpm-ostreed.service: Main process exited, code=killed, status=6/ABRT
Jun 24 01:47:29 vm rpm-ostree[1078]: Bail out! rpm-ostreed:ERROR:src/lib/rpmostree-package.c:251:_rpm_ostree_package_list_for_commit: assertion failed (pkglist->len > 0): (0 > 0)
Jun 24 01:47:29 vm rpm-ostree[1078]: rpm-ostreed:ERROR:src/lib/rpmostree-package.c:251:_rpm_ostree_package_list_for_commit: assertion failed (pkglist->len > 0): (0 > 0)
Jun 24 01:47:29 vm rpm-ostree[1078]: **
Jun 24 01:47:28 vm rpm-ostree[1078]: sanitycheck(/usr/bin/true) successful
Jun 24 01:47:28 vm rpm-ostree[1078]: Created new deployment /ostree/deploy/fedora-iot-commit/deploy/f3ad26afb2864bbfe0e4aab5e5489d6d14d11b84e96c1ca13681b90d13dbca8a.0
Jun 24 01:47:18 vm rpm-ostree[1078]: libostree pull from 'fedora-iot-commit' for fedora/33/x86_64/iot complete
                                     security: GPG: disabled 
                                     security: SIGN: disabled http: TLS
                                     non-delta: meta: 114 content: 92
                                     transfer: secs: 8 size: 7.8 MB
Jun 24 01:47:09 vm rpm-ostree[1078]: Process [pid: 1051 uid: 0 unit: session-3.scope] connected to transaction progress
Jun 24 01:47:09 vm rpm-ostree[1078]: Initiated txn Upgrade for client(id:cli dbus:1.28 unit:session-3.scope uid:0): /org/projectatomic/rpmostree1/fedora_iot_commit
Jun 24 01:47:09 vm rpm-ostree[1078]: Locked sysroot
Jun 24 01:47:09 vm rpm-ostree[1078]: client(id:cli dbus:1.28 unit:session-3.scope uid:0) added; new total=1
Jun 24 01:47:09 vm systemd[1]: Started rpm-ostree System Management Daemon.
Jun 24 01:47:09 vm rpm-ostree[1078]: In idle state; will auto-exit in 63 seconds
Jun 24 01:47:09 vm rpm-ostree[1078]: Reading config file '/etc/rpm-ostreed.conf'
Jun 24 01:47:09 vm systemd[1]: Starting rpm-ostree System Management Daemon...
```

It seems like hitting this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1959907
This bug has been fixed in rpm-ostree-2021.5-1.el8 but I didn't find this .fc33 version in https://koji.fedoraproject.org/koji/packageinfo?packageID=18142.(the latest one is rpm-ostree-2021.4-3.fc33 that was released at 2021-04-28. I'm not sure if there will be an update for fedora 33 anymore. The .fc34 and .fc35 has new versions already.)

So I tried to use the old base repos and new updates repos to see if can workaround this issue.

**Comment by yuxisun1217** [comment]
It's still failed. I think we cannot use the new Fedora 33 repo now because of https://bugzilla.redhat.com/show_bug.cgi?id=1959907 .

**Comment by ondrejbudai** [comment]
Argh, can you open a Fedora bug, please?

**Comment by yuxisun1217** [comment]
> Argh, can you open a Fedora bug, please?

Thanks for reminding! Open BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1975660

**Comment by ondrejbudai** [comment]
Thanks! :)

**Comment by yuxisun1217** [comment]
Blocked by #1496

**Review by atodorov — APPROVED** [review]

**Pull request merged**
