### PR TITLE
distro/rhel87: copy all definitions from rhel86

### PR DESCRIPTION
**Pull request by dhodovsk**
Adjust strings from 86, 8.6, 8-6 to 87, 8.7, 8-7
Diff can be seen here: http://pastebin.test.redhat.com/1024612 

heavily inspired by https://github.com/osbuild/osbuild-composer/commit/513b7f94b9cc5c84c0b8c0b9ff8a445f25fc66c7?diff=split 

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by thozza** [comment]
Thank you a lot for your contribution and kickstarting this work...

IMO the following things should be part of this PR before we merge it:

- the new distro definition needs to be added to the distroregistry - https://github.com/osbuild/osbuild-composer/blob/main/internal/distroregistry/distroregistry.go
- image test cases should be generated for 8.7 (howto https://github.com/osbuild/osbuild-composer/tree/main/test#image-tests).
- we need to create RPMRepo snapshots for 8.7 and create appropriate repo definitions for testing and image test case generator tools.
- ideally enable CI testing on 8.7

I'm not saying that Dominika should do it as most of these things require knowledge of our processes. However without this the code is not tested and not used so there is no point in merging it.

**Comment by thozza** [comment]
Since #2270 adds alias for RHEL-8.7, I propose to close this PR. The reason is that 8.6 definition is still being worked on and there is no point in copying it now into 8.7 and later double check and ensure that all changes from 8.6 were really moved to 8.7 definition. Instead we should copy/fork the 8.6 definition once it is "frozen" to not create additional work for us and prevent regressions.

**Comment by dhodovsk** [comment]
I am all for closing this PR :upside_down_face: As stated in the description it was heavily inspired by what has been done for rhel-86 and as such, it is just a midless copy of 8.6 with most of the "6" changed to "7" (not in x86_64 :grin: ). I did it only in hope of unblocking new 8.7. builds but we now use rhel-86 distro and it seems to be sufficient for the early phases.

**Comment by ondrejbudai** [comment]
Even though this gets closed, big THANK YOU for opening the PR and forcing us to do some actions. :D

**Comment by thozza** [comment]
Definitely, BIG Thank You @dhodovsk for submitting the PR!

**Pull request closed without merging**
