### PR TITLE
test: Add greenboot testing

### PR DESCRIPTION
**Pull request by henrywang**

### CODE REVIEW

**Comment by henrywang** [comment]
`EL8.3 Integration` and `F31 Image` test failure are not related with this PR.

**Comment by ondrejbudai** [comment]
@henrywang is this still relevant?

**Comment by henrywang** [comment]
> @henrywang is this still relevant?

Sorry for late response, just saw this notification.
Yes, edge image depends on greenboot. Greenboot is part of Edge/IoT image. Adding greenboot testing is very important for osbuild to run edge/iot image testing. Thanks.

**Comment by ondrejbudai** [comment]
Thanks for your answer, Xiaofeng! Can you rebase this PR then?

**Comment by henrywang** [comment]
@ondrejbudai, Thanks. :1st_place_medal: 
I'll rebase after PR #1050 got landed.

**Comment by henrywang** [comment]
@ondrejbudai, PR rebased. Thanks.

**Comment by ondrejbudai** [comment]
@gicmo may I ask you for a review? Thanks!

**Review by gicmo — APPROVED** [review]
Looks good to me! Thanks a bunch!

**Pull request merged**
