### PR TITLE
Return error if source name matches system repo         

### PR DESCRIPTION
**Pull request by bcl**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change

### CODE REVIEW

**Review by atodorov — APPROVED** [review]
Tests look good. :+1: from me.

**Comment by ondrejbudai** [comment]
The change looks good but one integration test needs adjusting.

**Review by ondrejbudai — APPROVED** [review]
lgtm, thanks!

**Review by teg — APPROVED** [review]
Nice!

**Comment by bcl** [comment]
Schutzbot build failure is due to infrastructure problems, not related to these changes. All the other tests in there pass.

**Pull request merged**
