### PR TITLE
mockbuild: use public EPEL-9

### PR DESCRIPTION
**Pull request by jrusz**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by jrusz** [comment]
I'm not sure if we need the mock templates. When I added `centos-9` runner in osbuild repository it wasn't needed... https://github.com/osbuild/osbuild/pull/974 Should I remove them?

**Comment by ondrejbudai** [comment]
CS9 mock templates are shipped in `mock-core-configs`, RHEL 9's are not yet (I guess they are waiting for GA).

```
my fedora 35 $ ls /etc/mock/ | grep centos-stream-9
centos-stream-9-aarch64.cfg
centos-stream-9-ppc64le.cfg
centos-stream-9-s390x.cfg
centos-stream-9-x86_64.cfg
```

**Comment by jrusz** [comment]
> CS9 mock templates are shipped in `mock-core-configs`, RHEL 9's are not yet (I guess they are waiting for GA).
> 
> ```
> my fedora 35 $ ls /etc/mock/ | grep centos-stream-9
> centos-stream-9-aarch64.cfg
> centos-stream-9-ppc64le.cfg
> centos-stream-9-s390x.cfg
> centos-stream-9-x86_64.cfg
> ```

Ok I've just remove the `centos-stream-9` ones.

**Comment by jrusz** [comment]
Huh, since when this is a thing? `ERROR    Libvirt version does not support UEFI.` It's in all the failed jobs.

**Review by ondrejbudai — APPROVED** [review]
Noice!

**Pull request merged**
