### PR TITLE
Update GPG keys for all RHEL 8.x repos

### PR DESCRIPTION
**Pull request by achilleas-k**
Follow-up to 60db6ad06fec398fe82a9bdcabb46554932addb8

The SHA-1 key is no longer supported in RHEL 9.0.  This isn't a problem for RHEL 8.x in general, but it prevents cross building RHEL 8.x images on RHEL 9.0, since the host (RHEL 9.0) rpm and openssl cannot import the older keys and we fail to bootstrap the build root for the new image if the source repositories use SHA-1 keys.

Related [rhbz#2058497 (Comment 18)](https://bugzilla.redhat.com/show_bug.cgi?id=2058497#c18).

### CODE REVIEW

**Review by ondrejbudai — COMMENTED** [review]
Looks good, should we also do this change in test manifests and the related tooling? Here's the list of affected file (`ls8J` are the last characters of the affected key):

```
$ rg --count-matches ls8J
tools/test-case-generators/repos.json:59
repositories/rhel-85.json:8
internal/osbuild2/result_test_data.go:12
internal/rpmmd/test/confpaths/priority2/repositories/test-distro-2.json:4
test/data/repositories/rhel-8.json:8
test/data/repositories/rhel-86.json:9
test/data/manifests/rhel_86-x86_64-edge_container-boot.json:8
test/data/manifests/rhel_90_beta-x86_64-edge_container-boot.json:8
test/data/manifests/rhel_8-x86_64-rhel_edge_commit_rt-boot.json:9
test/data/manifests/rhel_90_beta-x86_64-vhd-boot.json:6
test/data/repositories/rhel-85.json:8
test/data/manifests/rhel_90_beta-x86_64-edge_commit_rt-boot.json:9
test/data/manifests/rhel_90_beta-x86_64-openstack-boot.json:6
test/data/manifests/rhel_90_beta-x86_64-edge_commit-boot.json:9
test/data/manifests/rhel_90_beta-s390x-qcow2_customize-boot.json:6
test/data/manifests/rhel_90_beta-x86_64-vmdk-boot.json:6
test/data/manifests/rhel_90_beta-ppc64le-qcow2_customize-boot.json:6
test/data/manifests/rhel_90_beta-aarch64-openstack-boot.json:6
test/data/manifests/rhel_90_beta-aarch64-qcow2_customize-boot.json:6
test/data/manifests/rhel_90_beta-aarch64-edge_commit-boot.json:6
test/data/manifests/rhel_86-x86_64-qcow2_customize-boot.json:6
test/data/manifests/rhel_86-x86_64-gce_rhui-boot.json:6
test/data/manifests/rhel_86-x86_64-gce-boot.json:6
test/data/manifests/rhel_90_beta-x86_64-qcow2_customize-boot.json:6
test/data/repositories/rhel-90-beta.json:9
test/data/manifests/rhel_86-x86_64-openstack-boot.json:6
test/data/manifests/rhel_86-x86_64-vmdk-boot.json:6
test/data/manifests/rhel_86-x86_64-edge_commit_rt-boot.json:9
test/data/manifests/rhel_86-x86_64-edge_commit-boot.json:9
test/data/manifests/rhel_86-aarch64-qcow2_customize-boot.json:6
test/data/manifests/rhel_86-aarch64-openstack-boot.json:6
test/data/manifests/rhel_86-ppc64le-qcow2_customize-boot.json:6
test/data/manifests/rhel_85-x86_64-vmdk-boot.json:6
test/data/manifests/rhel_86-aarch64-edge_commit-boot.json:6
test/data/manifests/rhel_85-x86_64-gce-boot.json:6
test/data/manifests/rhel_85-x86_64-gce_rhui-boot.json:6
test/data/manifests/rhel_85-x86_64-openstack-boot.json:6
test/data/manifests/rhel_85-x86_64-vhd-boot.json:6
test/data/manifests/rhel_85-aarch64-qcow2_customize-boot.json:6
test/data/manifests/rhel_85-ppc64le-qcow2_customize-boot.json:6
test/data/manifests/rhel_85-aarch64-openstack-boot.json:6
test/data/manifests/rhel_85-aarch64-edge_commit-boot.json:6
test/data/manifests/rhel_86-s390x-qcow2_customize-boot.json:6
test/data/manifests/rhel_84-x86_64-vhd-boot.json:6
test/data/manifests/rhel_84-x86_64-vmdk-boot.json:6
test/data/manifests/rhel_84-x86_64-rhel_edge_commit-boot.json:9
test/data/manifests/rhel_84-x86_64-rhel_edge_commit_rt-boot.json:9
test/data/manifests/rhel_84-x86_64-openstack-boot.json:6
test/data/manifests/rhel_85-s390x-qcow2_customize-boot.json:6
test/data/manifests/rhel_84-aarch64-rhel_edge_commit-boot.json:6
test/data/manifests/rhel_8-x86_64-vmdk-boot.json:6
test/data/manifests/rhel_84-aarch64-openstack-boot.json:6
test/data/manifests/rhel_84-x86_64-gce_rhui-boot.json:6
test/data/manifests/rhel_8-x86_64-openstack-boot.json:6
test/data/manifests/rhel_86-x86_64-vhd-boot.json:6
test/data/manifests/rhel_8-aarch64-rhel_edge_commit-boot.json:6
test/data/manifests/rhel_84-x86_64-gce-boot.json:6
test/data/manifests/rhel_8-x86_64-vhd-boot.json:6
test/data/manifests/rhel_8-aarch64-openstack-boot.json:6
test/data/manifests/rhel_8-x86_64-rhel_edge_commit-boot.json:9
test/data/manifests/rhel_90_beta-x86_64-tar-boot.json:6
test/data/manifests/rhel_90_beta-x86_64-qcow2-boot.json:6
test/data/manifests/rhel_90_beta-x86_64-ec2_sap-boot.json:18
test/data/manifests/rhel_90_beta-x86_64-ec2_ha-boot.json:12
test/data/manifests/rhel_90_beta-x86_64-ec2-boot.json:9
test/data/manifests/rhel_90_beta-x86_64-edge_installer_with_users-boot.json:6
test/data/manifests/rhel_90_beta-s390x-tar-boot.json:6
test/data/manifests/rhel_90_beta-x86_64-ami-boot.json:6
test/data/manifests/rhel_90_beta-ppc64le-tar-boot.json:6
test/data/manifests/rhel_90_beta-s390x-qcow2-boot.json:6
test/data/manifests/rhel_90_beta-aarch64-tar-boot.json:6
test/data/manifests/rhel_90_beta-ppc64le-qcow2-boot.json:6
test/data/manifests/rhel_85-x86_64-qcow2_customize-boot.json:6
test/data/manifests/rhel_90_beta-x86_64-image_installer_with_users-boot.json:8
test/data/manifests/rhel_90_beta-aarch64-edge_container-boot.json:8
test/data/manifests/rhel_90_beta-aarch64-qcow2-boot.json:6
test/data/manifests/rhel_90_beta-aarch64-ami-boot.json:6
test/data/manifests/rhel_90_beta-aarch64-ec2-boot.json:9
test/data/manifests/rhel_90_beta-x86_64-edge_installer-boot.json:6
test/data/manifests/rhel_86-x86_64-tar-boot.json:6
test/data/manifests/rhel_86-x86_64-edge_simplified_installer-boot.json:6
test/data/manifests/rhel_86-x86_64-qcow2-boot.json:6
test/data/manifests/rhel_86-x86_64-edge_installer_with_users-boot.json:6
test/data/manifests/rhel_86-x86_64-image_installer_with_users-boot.json:8
test/data/manifests/rhel_86-x86_64-edge_installer-boot.json:6
test/data/manifests/rhel_86-x86_64-ec2_sap-boot.json:21
test/data/manifests/rhel_86-s390x-tar-boot.json:6
test/data/manifests/rhel_86-x86_64-ec2-boot.json:9
test/data/manifests/rhel_90_beta-x86_64-image_installer-boot.json:8
test/data/manifests/rhel_86-x86_64-image_installer-boot.json:8
test/data/manifests/rhel_86-ppc64le-tar-boot.json:6
test/data/manifests/rhel_86-aarch64-tar-boot.json:6
test/data/manifests/rhel_86-s390x-qcow2-boot.json:6
test/data/manifests/rhel_86-x86_64-azure_rhui-boot.json:6
test/data/manifests/rhel_86-ppc64le-qcow2-boot.json:6
test/data/manifests/rhel_86-aarch64-qcow2-boot.json:6
test/data/manifests/rhel_86-aarch64-edge_simplified_installer-boot.json:6
test/data/manifests/rhel_86-aarch64-image_installer_with_users-boot.json:8
test/data/manifests/rhel_86-aarch64-image_installer-boot.json:8
test/data/manifests/rhel_86-aarch64-edge_container-boot.json:8
test/data/manifests/rhel_86-aarch64-edge_installer-boot.json:6
test/data/manifests/rhel_85-x86_64-tar-boot.json:6
test/data/manifests/rhel_86-aarch64-edge_installer_with_users-boot.json:6
test/data/manifests/rhel_86-x86_64-ec2_ha-boot.json:12
test/data/manifests/rhel_86-x86_64-ami-boot.json:6
test/data/manifests/rhel_85-x86_64-qcow2-boot.json:6
test/data/manifests/rhel_86-aarch64-ec2-boot.json:9
test/data/manifests/rhel_85-x86_64-image_installer_with_users-boot.json:8
test/data/manifests/rhel_85-x86_64-edge_container-boot.json:8
test/data/manifests/rhel_85-x86_64-edge_commit_rt-boot.json:9
test/data/manifests/rhel_85-x86_64-edge_installer_with_users-boot.json:6
test/data/manifests/rhel_85-x86_64-edge_commit-boot.json:9
test/data/manifests/rhel_85-x86_64-image_installer-boot.json:8
test/data/manifests/rhel_85-x86_64-ec2-boot.json:9
test/data/manifests/rhel_85-x86_64-ec2_ha-boot.json:12
test/data/manifests/rhel_85-x86_64-azure_rhui-boot.json:6
test/data/manifests/rhel_85-x86_64-ami-boot.json:6
test/data/manifests/rhel_85-s390x-tar-boot.json:6
test/data/manifests/rhel_85-ppc64le-tar-boot.json:6
test/data/manifests/rhel_85-s390x-qcow2-boot.json:6
test/data/manifests/rhel_85-aarch64-tar-boot.json:6
test/data/manifests/rhel_85-ppc64le-qcow2-boot.json:6
test/data/manifests/rhel_85-aarch64-qcow2-boot.json:6
test/data/manifests/rhel_85-x86_64-edge_installer-boot.json:6
test/data/manifests/rhel_86-aarch64-ami-boot.json:6
test/data/manifests/rhel_85-aarch64-ec2-boot.json:9
test/data/manifests/rhel_84-x86_64-tar-boot.json:6
test/data/manifests/rhel_85-aarch64-ami-boot.json:6
test/data/manifests/rhel_85-aarch64-edge_installer-boot.json:6
test/data/manifests/rhel_85-aarch64-edge_installer_with_users-boot.json:6
test/data/manifests/rhel_84-x86_64-rhel_edge_container-boot.json:8
test/data/manifests/rhel_84-x86_64-qcow2-boot.json:6
test/data/manifests/rhel_84-x86_64-qcow2_customize-boot.json:6
test/data/manifests/rhel_85-aarch64-edge_container-boot.json:8
test/data/manifests/rhel_84-s390x-qcow2_customize-boot.json:6
test/data/manifests/rhel_84-x86_64-rhel_edge_installer-boot.json:6
test/data/manifests/rhel_84-ppc64le-tar-boot.json:6
test/data/manifests/rhel_84-s390x-qcow2-boot.json:6
test/data/manifests/rhel_84-ppc64le-qcow2-boot.json:6
test/data/manifests/rhel_84-ppc64le-qcow2_customize-boot.json:6
test/data/manifests/rhel_84-aarch64-rhel_edge_container-boot.json:8
test/data/manifests/rhel_84-aarch64-qcow2_customize-boot.json:6
test/data/manifests/rhel_8-x86_64-tar-boot.json:6
test/data/manifests/rhel_84-aarch64-qcow2-boot.json:6
test/data/manifests/rhel_84-aarch64-ami-boot.json:6
test/data/manifests/rhel_8-x86_64-qcow2-boot.json:6
test/data/manifests/rhel_8-x86_64-qcow2_customize-boot.json:6
test/data/manifests/rhel_84-x86_64-rhel_edge_installer_with_users-boot.json:6
test/data/manifests/rhel_8-s390x-qcow2_customize-boot.json:6
test/data/manifests/rhel_8-ppc64le-tar-boot.json:6
test/data/manifests/rhel_84-aarch64-tar-boot.json:6
test/data/manifests/rhel_8-s390x-tar-boot.json:6
test/data/manifests/rhel_8-x86_64-ami-boot.json:6
test/data/manifests/rhel_8-aarch64-tar-boot.json:6
test/data/manifests/rhel_84-x86_64-ami-boot.json:6
test/data/manifests/rhel_8-ppc64le-qcow2_customize-boot.json:6
test/data/manifests/rhel_8-s390x-qcow2-boot.json:6
test/data/manifests/rhel_8-aarch64-ami-boot.json:6
test/data/manifests/rhel_8-aarch64-qcow2-boot.json:6
test/data/manifests/rhel_8-aarch64-qcow2_customize-boot.json:6
test/data/manifests/rhel_8-ppc64le-qcow2-boot.json:6
repositories/rhel-87.json:8
repositories/rhel-86.json:8
repositories/rhel-84.json:8
repositories/rhel-8.json:8
repositories/rhel-8-beta.json:8
```

**Comment by achilleas-k** [comment]
Yes, I should update those too.  Thankfully, an image-info update isn't required.

**Comment by thozza** [comment]
> Yes, I should update those too. Thankfully, an image-info update isn't required.

well, it actually may be needed for image test cases which are importing the key, because it is listed as an installed package, e.g.:
https://github.com/osbuild/osbuild-composer/blob/b4bec690ab0d18e611865a4b5ab61025f6d91e1f/test/data/manifests/rhel_84-x86_64-ami-boot.json#L9637-L9638

**Comment by achilleas-k** [comment]
> > Yes, I should update those too. Thankfully, an image-info update isn't required.
> 
> well, it actually may be needed for image test cases which are importing the key, because it is listed as an installed package, e.g.:
> 
> https://github.com/osbuild/osbuild-composer/blob/b4bec690ab0d18e611865a4b5ab61025f6d91e1f/test/data/manifests/rhel_84-x86_64-ami-boot.json#L9637-L9638

_huh_
The manifest tests passed though :thinking:

**Comment by thozza** [comment]
> _huh_ The manifest tests passed though 🤔

These are comparing only manifests. They do not build images and do not generate image-info report. This would most probably manifests as an issue in osbuild's CI, which is building images.

You could double-check if image-info needs regenerating by just trying to regenerate one image test cases also with image-info...

**Comment by achilleas-k** [comment]
> These are comparing only manifests. They do not build images and do not generate image-info report. This would most probably manifests as an issue in osbuild's CI, which is building images.

oh silly me.  I know the package list is compared in the manifest tests but now I realise this isn't a normal package and only appears after the import, right?

Aside: Some gcp tests are failing at key import.

**Comment by achilleas-k** [comment]
Something strange happened with the GCE image.  The google packages are failing to install, but it's not breaking the build.

**Comment by achilleas-k** [comment]
> Something strange happened with the GCE image. The google packages are failing to install, but it's not breaking the build.

@thozza I think I figured it out.

Ignoring (for now) the errors in the log that we talked about, I'm pretty sure the issue occurs when running image-info on a RHEL 9.0 host.  The GCE image types actually _do_ install the Google packages just fine.  The repos have SHA-1 keys, but they're installed in the OS, which uses rpm from the build root which is fine with SHA-1 (say, on RHEL 8.6).
Then image-info runs on RHEL 9.0 (the beakers I was using) and doesn't list the packages because it finds a "bad" signature:
```
error: rpmdbNextIterator: skipping h#     308
Header V4 RSA/SHA1 Signature, key ID 3e1ba8d5: BAD
Header SHA256 digest: OK
Header SHA1 digest: OK
```

For now, I can get away with regenerating the test cases on RHEL 8.6.  That should be fine.  Cross-distro builds of GCE from RHEL 9.0 to RHEL 8.x wont work though until we get a SHA-256 key for the Google repos (or we remove the gpg check for them).

**Comment by achilleas-k** [comment]
Rebased on #2578 and by extension #2552

**Review by thozza — DISMISSED** [review]
LGTM

**Comment by achilleas-k** [comment]
Gonna need another approval in a few mins.  Pushing RHEL 8.5 manifests that needed changes after reverting the rebase.

**Review by thozza — APPROVED** [review]

**Review by gicmo — APPROVED** [review]
👍

I wonder if we really should not just do what we do for Azure-rhui and read the keys from `/etc` and don't specify them in the repos.

**Pull request merged**
