### PR TITLE
test: Run Edge tests on RHEL 8.5

### PR DESCRIPTION
**Pull request by henrywang**
PR #1391 has been merged, but Edge integration test did not get run. Since Edge integration test on RHEL 8.5 (not just Edge tests, but all integration tests on RHEL 8.5) has not been run yet. I have to open this PR to run test and see what happens.

And to open this PR I update `ostree.sh` and remove fedora 32 test because it's not covered by CI.

### CODE REVIEW

**Comment by henrywang** [comment]
@ondrejbudai @atodorov Could you please help set variable `RHEL85_NIGHTLY_REPO` used by https://github.com/osbuild/osbuild-composer/blob/1e54cd4493d0f611340c90fd64dc7c7281d5d2cd/schutzbot/mockbuild.sh#L85
Thanks.

**Comment by atodorov** [comment]
> @ondrejbudai @atodorov Could you please help set variable `RHEL85_NIGHTLY_REPO` used by

Done.

**Review by atodorov — COMMENTED** [review]
+1 for the Fedora32 removal but the subject says "Run Edge tests on 8.5". I see nothing related to 8.5 here. 

Are we missing a commit here or the subject is incorrect ?

**Comment by henrywang** [comment]
> +1 for the Fedora32 removal but the subject says "Run Edge tests on 8.5". I see nothing related to 8.5 here.
> 
> Are we missing a commit here or the subject is incorrect ?

No, this PR is to Run Edge tests on RHEL 8.5. To open this PR, I update ostree.sh and remove fedora 32 test.
This PR might have more commit to fix Edge test issue, because it's the first time to run edge test on RHEL 8.5.

**Comment by henrywang** [comment]
@atodorov The openstack deployment reports error. I can find the this RHEL 8.5 nightly image id from my PSI openstack account. So the image id is not the same for all projects?
```
Error: Error creating OpenStack server: Bad request with: [POST https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13774/v2.1/servers], error message: {"badRequest": {"code": 400, "message": "Can not find requested image"}}
```

**Comment by henrywang** [comment]
@achilleas-k @gicmo All edge related tests are all passed. Pin to osbuild commit(which has `rng-tools` fix included by mounting /sys read only) fixed that issue!

1. [`ostree.sh` on RHEL-8](https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1390936522)
2. [`ostree.sh` on RHEL-8.5](https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1390936523)
3. [`ostree-ng.sh` on RHEL-8.5](https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1390936524)

**Comment by henrywang** [comment]
@atodorov @ondrejbudai Do we have plan to pin `RHEL-8` test to `RHEL-8.4`? As Edge, we need RHEL 8.4 environment because Edge has 8.4 z-stream fix([bz#1951192](https://bugzilla.redhat.com/show_bug.cgi?id=1951192)) and old image types(`rhel-edge-commit`, `rhel-edge-container`, and `rhel-edge-installer` on RHEL 8.4 only) should be tested to make sure both of new image type on RHEL 8.5 and old image type on RHEL 8.4 work. Thanks.

**Comment by ondrejbudai** [comment]
Yes, this is on my todo-list. :)

**Review by atodorov — APPROVED** [review]
LGTM, it seems that the failures aren't related to the current changes.

**Comment by atodorov** [comment]
Everything reports PASS! Will go ahead and merge!

**Pull request merged**
