### PR TITLE
Add new image type 'minimal-rpm' for fedora

### PR DESCRIPTION
**Pull request by sarmahaj**
This pull request includes:

- New image type named 'minimal-rpm' has been added to fedora. 
- Reference taken from https://github.com/osbuild/osbuild-composer/pull/2878 which is now superceded by #3004 , since ref PR is in draft stage , marking this one as draft too.
- Image is basically a minimal rpm bootable image supports aarch64 & x86
- After building the image with osbuild-composer, its tested on both x86 and aarch64 machines, boots fine.

https://github.com/osbuild/osbuild-composer/pull/2878

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by nullr0ute** [comment]
Firstly can we rename this from armsystemready to just minimal. While it's planned to be used primarily for testing arm things non of this is either arm or systemready specific

**Comment by nullr0ute** [comment]
Dependent on  #2878

**Comment by sarmahaj** [comment]
Closing this PR ,since dependent PR #2878 is closed.

**Comment by ondrejbudai** [comment]
@sarmahaj I believe that's misunderstanding, #2878 was just superseded by https://github.com/osbuild/osbuild-composer/pull/3004

**Comment by nullr0ute** [comment]
This will need to be rebased to #3077 but let's wait until that actually lands

**Comment by sarmahaj** [comment]
Created a new PR https://github.com/osbuild/osbuild-composer/pull/3181 for this work.
Closing this PR.

**Pull request closed without merging**
