### PR TITLE
internal/distro/rhel85: move systemd logs kargs to the installer image

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@linux.com>

This PR fixes https://github.com/osbuild/osbuild-composer/issues/1701

### CODE REVIEW

**Review by ondrejbudai — DISMISSED** [review]

**Comment by gicmo** [comment]
Might need an adaption of the greenboot tests since logging target changed. Otherwise looks good.

**Comment by runcom** [comment]
> Might need an adaption of the greenboot tests since logging target changed

is that something that lives in this repo?

**Review by teg — DISMISSED** [review]
We need to discuss whether to still land this for 8.5.

**Comment by henrywang** [comment]
@yih-redhat I checked `greenboot` log, this PR fixed #1701. Could you please update `check-ostree.yaml` and remove un-used log check task? Thanks.

**Comment by henrywang** [comment]
@yih-redhat ansible fact `vda4_detected` is not required in this case. Could you please remove it? Thanks.

**Comment by yih-redhat** [comment]
> @yih-redhat ansible fact `vda4_detected` is not required in this case. Could you please remove it? Thanks.

Got it, thanks! Antonio will remove it as it's one-line change.

**Comment by runcom** [comment]
this should be good to go now and can go in

**Comment by henrywang** [comment]
Looks good to me. Thanks @runcom!

**Review by henrywang — APPROVED** [review]
LGTM. Thanks @runcom!

**Review by gicmo — APPROVED** [review]
Looks good to me :parasol_on_ground:

**Pull request merged**
