### PR TITLE
distro: add fedora 34 and 35 aliases to f33

### PR DESCRIPTION
**Pull request by msehnout**
This PR is an alternative to https://github.com/osbuild/osbuild-composer/pull/1426, specifically a result of this discussion: https://github.com/osbuild/osbuild-composer/pull/1426#issuecomment-852196746

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by teg — COMMENTED** [review]
Really nice!

**Review by ondrejbudai — DISMISSED** [review]
Awesome!

**Comment by ondrejbudai** [comment]
oh, the unit tests are failing, we need to fix it before merging.

**Comment by msehnout** [comment]
> oh, the unit tests are failing, we need to fix it before merging.

 

Go structure initialization strikes again. It should be fixed now, but Github didn't propagate the changes from my fork to this PR. Let's wait a bit longer.

**Review by ondrejbudai — DISMISSED** [review]

**Comment by ondrejbudai** [comment]
okay, the RPMs are currently unbuildable. This will fix itself when this update gets pushed to stable (should happen tomorrow): https://bodhi.fedoraproject.org/updates/FEDORA-2021-53ed7029f2

**Comment by thozza** [comment]
Great Work @msehnout.

Yesterday I suggested on Slack to add similar alias for RHEL-8.5 in 8.4 definitions until we port all supported images to 8.5. @teg agreed. Do you think you could add it as part of this PR? If it is too much hassle, it can be a different PR as well.

**Review by teg — APPROVED** [review]

**Review by ondrejbudai — APPROVED** [review]

**Comment by ondrejbudai** [comment]
I went through all the failed tests and I see the following issues: #1447, #1448, https://github.com/osbuild/osbuild/issues/482

Everything seems to be irrelevant to this PR.

**Pull request merged**
