### PR TITLE
Rename funcs in sanity tests

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by ondrejbudai** [comment]
Schutzbot seems to unhappy though.

**Comment by atodorov** [comment]
> Schutzbot seems to unhappy though.

Yes, the failure is https://github.com/osbuild/osbuild-composer/issues/664

**Comment by atodorov** [comment]
There seems to be another failure here which comes from `composer-cli compose image`. I think this is the relevant log from Jenkins:

```
May 28 12:47:19 fedora31-107 osbuild-worker[3513]: Waiting for a new job...
May 28 12:47:30 fedora31-107 osbuild-composer[3520]: 2020/05/28 12:47:30 http: panic serving @: write unix /run/weldr/api.socket->@: write: broken pipe
May 28 12:47:30 fedora31-107 osbuild-composer[3520]: goroutine 706 [running]:
May 28 12:47:30 fedora31-107 osbuild-composer[3520]: net/http.(*conn).serve.func1(0xc0000f80a0)
May 28 12:47:30 fedora31-107 osbuild-composer[3520]:         /usr/lib/golang/src/net/http/server.go:1767 +0x13b
May 28 12:47:30 fedora31-107 osbuild-composer[3520]: panic(0x55a5903b6220, 0xc0000f4d70)
May 28 12:47:30 fedora31-107 osbuild-composer[3520]:         /usr/lib/golang/src/runtime/panic.go:679 +0x1b6
May 28 12:47:30 fedora31-107 osbuild-composer[3520]: github.com/osbuild/osbuild-composer/internal/common.PanicOnError(...)
May 28 12:47:30 fedora31-107 osbuild-composer[3520]:         /builddir/build/BUILD/osbuild-composer-2e58642484928f21464bbac166a70ff28bab717f/_build/src/github.com/osbuild/osbuild-composer/internal/common/helpers.go:23
May 28 12:47:30 fedora31-107 osbuild-composer[3520]: github.com/osbuild/osbuild-composer/internal/weldr.(*API).composeImageHandler(0xc0000d2500, 0x55a590428900, 0xc0000ee540, 0xc000104400, 0xc00037a280, 0x2, 0x4)
May 28 12:47:30 fedora31-107 osbuild-composer[3520]:         /builddir/build/BUILD/osbuild-composer-2e58642484928f21464bbac166a70ff28bab717f/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:2031 +0xfe4
May 28 12:47:30 fedora31-107 osbuild-composer[3520]: github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000068a20, 0x55a590428900, 0xc0000ee540, 0xc000104400)
May 28 12:47:30 fedora31-107 osbuild-composer[3520]:         /usr/share/gocode/src/github.com/julienschmidt/httprouter/router.go:387 +0xa3f
May 28 12:47:30 fedora31-107 osbuild-composer[3520]: github.com/osbuild/osbuild-composer/internal/weldr.(*API).ServeHTTP(0xc0000d2500, 0x55a590428900, 0xc0000ee540, 0xc000104400)
May 28 12:47:30 fedora31-107 osbuild-composer[3520]:         /builddir/build/BUILD/osbuild-composer-2e58642484928f21464bbac166a70ff28bab717f/_build/src/github.com/osbuild/osbuild-composer/internal/weldr/api.go:150 +0x144
May 28 12:47:30 fedora31-107 osbuild-composer[3520]: net/http.serverHandler.ServeHTTP(0xc0000ee380, 0x55a590428900, 0xc0000ee540, 0xc000104400)
May 28 12:47:30 fedora31-107 osbuild-composer[3520]:         /usr/lib/golang/src/net/http/server.go:2802 +0xa6
May 28 12:47:30 fedora31-107 osbuild-composer[3520]: net/http.(*conn).serve(0xc0000f80a0, 0x55a590429640, 0xc00033e080)
May 28 12:47:30 fedora31-107 osbuild-composer[3520]:         /usr/lib/golang/src/net/http/server.go:1890 +0x877
May 28 12:47:30 fedora31-107 osbuild-composer[3520]: created by net/http.(*Server).Serve
May 28 12:47:30 fedora31-107 osbuild-composer[3520]:         /usr/lib/golang/src/net/http/server.go:2928 +0x386
```

**Comment by teg** [comment]
Would love to merge this, but I guess we need a fix for #664 to land first.

**Comment by atodorov** [comment]
> Would love to merge this, but I guess we need a fix for #664 to land first.

@teg the latest comment points to a different issue IMO. Can you take a look.

**Comment by larskarlitski** [comment]
This is merged as part of #730.

**Pull request closed without merging**
