### PR TITLE
deps: update osbuild/images to 9548bf0d0140

### PR DESCRIPTION
**Pull request by achilleas-k**
Update osbuild/images dependency to osbuild/images@9548bf0d0140

Relevant PRs:
- https://github.com/osbuild/images/pull/43
- https://github.com/osbuild/images/pull/91

@henrywang It's now possible to specify parent ostree commits using the commit ID, like we could before we introduced changing refs. (see https://github.com/osbuild/osbuild-composer/issues/3107).

Can we add a test case for this to one of the ostree tests?  Building a child commit from a parent, but specify the parent using the commit ID instead of the ref.

### CODE REVIEW

**Comment by henrywang** [comment]
@achilleas-k Questions about this change:

1. Does `--parent <parent ref>` still work? If not, the rebase upgrade, like upgrade from rhel 8 to rhel 9 will not work.
2. Commit ID is used as vaule of `--parent`. Which ref will be used if there're two or more refs in ostree repo?
3. If we have issue on 1 or 2, we should add one more arg `--commit`

**Comment by achilleas-k** [comment]
> @achilleas-k Questions about this change:
> 
> 1. Does `--parent <parent ref>` still work? If not, the rebase upgrade, like upgrade from rhel 8 to rhel 9 will not work.

Yes, it still works.

> 2. Commit ID is used as vaule of `--parent`. Which ref will be used if there're two or more refs in ostree repo?

The ref for the new (child) commit will be the `--ref` argument or the default for the distribution of it's not specified.  For pulling the parent, the ref doesn't matter.  It just pulls the commit with the given ID from the repo.

> 3. If we have issue on 1 or 2, we should add one more arg `--commit`

There shouldn't be any issues.

**Comment by achilleas-k** [comment]
Looking good.  Failures are
```
An error occurred (VpcLimitExceeded) when calling the CreateVpc operation: The maximum number of VPCs has been reached.
```

Marking PR as ready.

**Comment by henrywang** [comment]
@achilleas-k Yes, it's not caused by this PR.

**Comment by henrywang** [comment]
@achilleas-k All green now.

**Review by ondrejbudai — APPROVED** [review]

**Pull request merged**
