### PR TITLE
tests: Make TestSources distro independent. Refs #315

### PR DESCRIPTION
**Pull request by atodorov**
by loading repositories configuration first and then running `composer-cli sources info <repo>` on the first repository found.

@teg I took a different approach for this. Please review.

### CODE REVIEW

**Comment by atodorov** [comment]
@teg +1 for leaving the sanity tests as-is and doing more checking elsewhere. 

My motivation here is to make this piece of code distro independent without having to hard-code the repository names in the actual test code b/c I don't like hard coding it. Other than that there is no difference in the size of this diff regardless which approach we take.

**Comment by atodorov** [comment]
> I think we should do a mapping in the test from distro to expected source name. Then we can test both against lorax composer and osbuild composer to check they are the same.

@teg IIRC lorax composer doesn't care about the names. This proposed scenario doesn't make sense to me. I can't figure out what are we trying to validate here (other than the names are as defined in repositories json files).  However this is a separate discussion.

**Comment by teg** [comment]
I think these tests should not depend on `osbuild-composer` internals, and I do not think we need to verify here that the names of the system sources are as expected. If we want that, we could add that to the `weldr` test.

I still think it makes sense to test that `sources info` works, without getting into the specific behaviour. How about something like this (untested):
```patch
diff --git a/cmd/osbuild-tests/main_test.go b/cmd/osbuild-tests/main_test.go
index a3b5ed8..083a3a4 100644
--- a/cmd/osbuild-tests/main_test.go
+++ b/cmd/osbuild-tests/main_test.go
@@ -77,10 +77,9 @@ gpgkey_urls = ["https://url/path/to/gpg-key"]
        require.NoError(t, err)
 
        runComposerCLI(t, false, "sources", "list")
-       // todo: this will fail on RHEL
-       runComposerCLI(t, false, "sources", "info", "fedora")
 
        runComposerCLI(t, false, "sources", "add", sources_toml.Name())
+       runComposerCLI(t, false, "sources", "info", "osbuild-test-addon-source")
        runComposerCLI(t, false, "sources", "change", sources_toml.Name())
        runComposerCLI(t, false, "sources", "delete", "osbuild-test-addon-source")
 }
```

**Comment by atodorov** [comment]
@teg I like your idea. It makes the change very minimal

**Comment by teg** [comment]
Thanks!

**Pull request merged**
