### PR TITLE
distro/rhel8: Updates for RHEL for Edge

### PR DESCRIPTION
**Pull request by nullr0ute**
We now have greenboot available so update the packages and services
also add exclude sections as subscription-manager is for some reason
getting pulled in which brings dnf and other deps we explicitly don't
want.

Signed-off-by: Peter Robinson <pbrobinson@gmail.com>

### CODE REVIEW

**Comment by teg** [comment]
Thanks for this @nullr0ute! As we don't have CI tests to verify these images (apart from: "they build and have the content we think they should"), could you include a comment in the commit message about how this was tested, and in particular that the greenboot behavior was verified to work as intended after this change?

**Comment by nullr0ute** [comment]
> Thanks for this @nullr0ute! As we don't have CI tests to verify these images (apart from: "they build and have the content we think they should"), could you include a comment in the commit message about how this was tested, and in particular that the greenboot behavior was verified to work as intended after this change?

The greenboot config is as it is in Fedora, I've not personally done a full end to end test here but I'm not sure why that's a requirement of getting this patch merged.

**Comment by teg** [comment]
I discussed this offline with @nullr0ute, and we are now on the same page. But just for the sake of completeness, for anyone else following along: we need all changes to be tested either manually or by CI (obviously the latter is the preference). It is not as easy as it could be to test these sorts of changes locally, but to make that easier we build and provide RPMs for every PR. For now, these are only accessible behind the RH VPN by clicking on the [Details](https://osbuildci.cloud.paas.psi.redhat.com/job/osbuild/job/osbuild-composer/job/PR-893/1/display/redirect) link in `schutzbot-psi` and getting the repo config from the `Mock` stage. We are working on improving on this.

For this to work though, we need the unit tests to pass, so they need to be updated as part of this PR for the RPMs to build at all. That can be done by running:
`./tools/test-case-generators/generate-test-cases --distro rhel-8 --arch x86_64 --image-types rhel-edge-commit --keep-image-info --output test/cases --store /tmp`
and
`./tools/test-case-generators/generate-test-cases --distro rhel-8 --arch aarch64 --image-types rhel-edge-commit --keep-image-info --output test/cases --store /tmp`.

To make the integration tests pass again, we need to also run the same without the `--keep-image-info` argument, which is better done on a machine with the right architecture. Again, something we are working on improving (ideally the CI should spit these new test cases out whenever they fail, rather than requiring anyone to regenerate them).

**Comment by gicmo** [comment]
For reference the corresponding Fedora IoT presets, which include greenboot: https://src.fedoraproject.org/rpms/fedora-release/blob/master/f/80-iot.preset

**Comment by teg** [comment]
I pushed a couple of commits to hopefully make the tests pass. I'm not very happy at all with having to test against RHEL8.3 nightly snapshots for this, but for the time being we don't have any other choice.
The tests only verify that the commit has been built, so before we land this, could someone please verify that it works as expected, the RPMs can be found at http://osbuild-composer-repos.s3-website.us-east-2.amazonaws.com/osbuild/osbuild-composer/PR-893/413e35f/rhel83_x86_64 .

**Comment by henrywang** [comment]
I tried on my local environment with the following osbuild* installed:
```shell
osbuild-19-1.20200808gitf92a00b.20200808gitf92a00b.el8.noarch
osbuild-selinux-19-1.20200808gitf92a00b.20200808gitf92a00b.el8.noarch
osbuild-composer-worker-18-1.20200808git2cb2b32.el8.x86_64
osbuild-composer-18-1.20200808git2cb2b32.el8.x86_64
python3-osbuild-19-1.20200808gitf92a00b.20200808gitf92a00b.el8.noarch
osbuild-ostree-19-1.20200808gitf92a00b.20200808gitf92a00b.el8.noarch
```
I got the following error when building ostree image:
```shell
setfiles: /run/osbuild/tree/etc/selinux/targeted/contexts/files/file_contexts: line 2481 has invalid context syste
m_u:object_r:virt_var_lockd_t:s0
setfiles: /run/osbuild/tree/etc/selinux/targeted/contexts/files/file_contexts: line 2481 has invalid context syste
m_u:object_r:virt_var_lockd_t:s0
/run/osbuild/tree/etc/selinux/targeted/contexts/files/file_contexts: Invalid argument
Traceback (most recent call last):
  File "/run/osbuild/lib/stages/org.osbuild.selinux", line 61, in <module>
    r = main(args["tree"], args["options"])
  File "/run/osbuild/lib/stages/org.osbuild.selinux", line 52, in main
    subprocess.run(["setfiles", "-F", "-r", f"{tree}", f"{file_contexts}", f"{tree}"], check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['setfiles', '-F', '-r', '/run/osbuild/tree', '/run/osbuild/tree/etc/selin
ux/targeted/contexts/files/file_contexts', '/run/osbuild/tree']' returned non-zero exit status 1.
```

**Comment by teg** [comment]
> I tried on my local environment with the following osbuild* installed:
> 
> ```shell
> osbuild-19-1.20200808gitf92a00b.20200808gitf92a00b.el8.noarch
> ```

This appears to not be from the most recent CI run for this PR. The repository should be
```
[osbuild-mock]
name=osbuild mock osbuild/osbuild-composer/PR-893-c2587ed rhel83
baseurl=http://osbuild-composer-repos.s3-website.us-east-2.amazonaws.com/osbuild/osbuild-composer/PR-893/c2587ed/rhel83_x86_64
enabled=1
gpgcheck=0
# Default dnf repo priority is 99. Lower number means higher priority.
priority=5
```

Which contains `osbuild-19-1.20200810git3c556c3.20200810git3c556c3.el8.noarch`.

**Comment by henrywang** [comment]
Thanks @teg!
I updated repo and looks everything works well.

1. `subscription-manager` removed and its dependence `dnf` got removed as well
2. `greenboot`, `greenboot-grub2`, `greenboot-rpm-ostree-grub2`, `greenboot-reboot` installed.
```shell
greenboot-grub2-0.10.3-5.el8.x86_64
greenboot-rpm-ostree-grub2-0.10.3-5.el8.x86_64
greenboot-reboot-0.10.3-5.el8.x86_64
greenboot-0.10.3-5.el8.x86_64
```
3. service `greenboot-grub2-set-counter`, `greenboot-grub2-set-success`, `greenboot-healthcheck`, `greenboot-rpm-ostree-grub2-check-fallback`, `redboot-auto-reboot` got installed and enabled
4. only `greenboot-healthcheck` started, it matched service defined in https://github.com/fedora-iot/greenboot/tree/master/usr/lib/systemd/system

**Comment by henrywang** [comment]
Some tests on greenboot:
1. service log checking:
```shell
Aug 12 02:51:55 localhost.localdomain systemd[1]: Starting greenboot Health Checks Runner...
Aug 12 02:51:56 localhost.localdomain greenboot[736]: Running Required Health Check Scripts...
Aug 12 02:51:56 localhost.localdomain 00_required_scripts_start.sh[746]: Running greenboot Required Health Check >
Aug 12 02:51:56 localhost.localdomain greenboot[736]: Script '00_required_scripts_start.sh' SUCCESS
Aug 12 02:51:56 localhost.localdomain greenboot[736]: Running Wanted Health Check Scripts...
Aug 12 02:51:56 localhost.localdomain 00_wanted_scripts_start.sh[755]: Running greenboot Wanted Health Check Scri>
Aug 12 02:51:56 localhost.localdomain greenboot[736]: Script '00_wanted_scripts_start.sh' SUCCESS
Aug 12 02:51:56 localhost.localdomain systemd[1]: Started greenboot Health Checks Runner.
```
2. `sudo grub2-editenv list`
```shell
kernelopts=root=UUID=2f8e3a26-2117-4ce6-ac24-cd251d7070ee ro net.ifnames=0 modprobe.blacklist=vc4 crashkernel=auto console=ttyS0,115200
boot_success=1
boot_counter=2
```

**Comment by teg** [comment]
Thansk @henrywang! I guess this means there is no point in moving forward with this PR until the functionality actually works? (assuming the issue is in greenboot, and not in the image generation, of course).

**Comment by gicmo** [comment]
cc @LorbusChris

**Comment by LorbusChris** [comment]
@henrywang It seems the `greenboot-rpm-ostree-grub2-check-fallback` service didn't run, and the bootloader entries therefore weren't cleaned up, which is why it booted into the broken commit again.

Please double check the service is enabled - or show the journal entries for it if it was indeed enabled.

**Comment by LorbusChris** [comment]
@henrywang please also provide the journal for the fallback boot (the good one, after 3times trying the bad one, before booting back into the bad one), so we can investigate why boot_complete.target was never reached there.

**Comment by LorbusChris** [comment]
Actually, there is a race between `greenboot-rpm-ostree-grub2-check-fallback.service` and `greenboot-grub2-set-success.service`, and when success is set before the fallback check, the bootloader entries are never cleaned up, which would explain point 2.

Will PR a fix and rebuild the package.

But that still doesn't explain why success wasn't set on the fallback boot, so the journal logs would still be helpful here :)

**Comment by teg** [comment]
@LorbusChris if you have a look at the `image-info` dict in https://github.com/osbuild/osbuild-composer/blob/5990444de4c8e907f427dcc32ddc6033af71a943/test/cases/rhel_8-x86_64-rhel_edge_commit-boot.json you can see a description of the default image created with this commit (against a recent RHEL8.3 nightly). Do the installed packages and the enabled/disabled systemd services look right to you? I see a handful of systemd services that seem greenboot related, but are not enabled.

**Comment by henrywang** [comment]
> Thansk @henrywang! I guess this means there is no point in moving forward with this PR until the functionality actually works? (assuming the issue is in greenboot, and not in the image generation, of course).

IMHO, the issue is not related with this PR, we can land it if you have no more comments. Thanks.

**Comment by henrywang** [comment]
@LorbusChris,

**Normal boot, no `exit 1` script in `/etc/greenboot/check/required.d/`** 
1. service `greenboot-rpm-ostree-grub2-check-fallback` is enabled

```
[admin@ostree-guest ~]$ systemctl status greenboot-rpm-ostree-grub2-check-fallback
● greenboot-rpm-ostree-grub2-check-fallback.service - Check for fallback boot
   Loaded: loaded (/usr/lib/systemd/system/greenboot-rpm-ostree-grub2-check-fallback.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
```

2. no log for `greenboot-rpm-ostree-grub2-check-fallback`
```
[admin@ostree-guest ~]$ journalctl -u greenboot-rpm-ostree-grub2-check-fallback
-- Logs begin at Thu 2020-08-13 05:40:07 UTC, end at Thu 2020-08-13 06:01:10 UTC. --
-- No entries --
```

**Install `greenboot-failing-unit-1.0-1.el8.noarch` with rpm-ostree and reboot**

1. report `[FAILED] Failed to start greenboot Health Checks Runner`, and reboot
2. report `[FAILED] Failed to start greenboot Health Checks Runner`, and reboot
3. report `[FAILED] Failed to start greenboot Health Checks Runner`, and reboot
4. rollback to `good commit`. Looks no log for service `greenboot-rpm-ostree-grub2-check-fallback`

```
[admin@ostree-guest ~]$ sudo rpm-ostree status
State: idle
Deployments:
  ostree://rhel-edge:rhel/8/x86_64/edge
                 Timestamp: 2020-08-13T05:38:32Z
                BaseCommit: 194033144cba394dffe0b13fa8c8c6add4ce471fa0eabb8900ca3eab77056deb
                      Diff: 1 added
             LocalPackages: greenboot-failing-unit-1.0-1.el8.noarch

* ostree://rhel-edge:rhel/8/x86_64/edge
                 Timestamp: 2020-08-13T05:38:32Z
                    Commit: 194033144cba394dffe0b13fa8c8c6add4ce471fa0eabb8900ca3eab77056deb
```

```
[admin@ostree-guest ~]$ systemctl status greenboot-rpm-ostree-grub2-check-fallback
● greenboot-rpm-ostree-grub2-check-fallback.service - Check for fallback boot
   Loaded: loaded (/usr/lib/systemd/system/greenboot-rpm-ostree-grub2-check-fallback.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
```
```
[admin@ostree-guest ~]$ sudo journalctl -b -0 -u boot-complete.target -u greenboot -u greenboot-healthcheck -u greenboot-rpm-ostree-grub2-check-fallback -u greenboot-grub2-set-counter -u greenboot-grub2-set-success -u greenboot-status -u redboot -u redboot-auto-reboot -u redboot.target
-- Logs begin at Thu 2020-08-13 06:11:43 UTC, end at Thu 2020-08-13 06:16:13 UTC. --
Aug 13 06:11:53 localhost.localdomain systemd[1]: Starting greenboot Health Checks Runner...
Aug 13 06:11:53 localhost.localdomain greenboot[718]: Running Required Health Check Scripts...
Aug 13 06:11:53 localhost.localdomain 00_required_scripts_start.sh[724]: Running greenboot Required Health Check Scripts
Aug 13 06:11:53 localhost.localdomain greenboot[718]: Script '00_required_scripts_start.sh' SUCCESS
Aug 13 06:11:53 localhost.localdomain greenboot[718]: Running Wanted Health Check Scripts...
Aug 13 06:11:53 localhost.localdomain 00_wanted_scripts_start.sh[740]: Running greenboot Wanted Health Check Scripts
Aug 13 06:11:53 localhost.localdomain greenboot[718]: Script '00_wanted_scripts_start.sh' SUCCESS
Aug 13 06:11:53 localhost.localdomain systemd[1]: Started greenboot Health Checks Runner.
```

**Comment by LorbusChris** [comment]
Ok it seems the culprit here for 1) is that `greenboot-task-runner.service` isn't enabled, which is required to start the set-success service.
I've actually be meaning to change that to use systemd's bless boot service. That'll require preset changes again, though.
I'll look into it next week.

**Comment by teg** [comment]
@LorbusChris thanks! Does this mean that we should not need to alter anything else in this PR? Could you give us a ping when the fixes land in the next RHEL nightly, so we can re-run our tests before merging?

**Comment by LorbusChris** [comment]
yes, I'll rebuild the packages on monday and ping here once it's landed in the pools!

**Comment by teg** [comment]
@LorbusChris any update on this?

FYI, @nullr0ute, @mrguitar this is unlikely to land before RHEL 8.3 at this point.

**Comment by nullr0ute** [comment]
> FYI, @nullr0ute, @mrguitar this is unlikely to land before RHEL 8.3 at this point.

For reference this was on me. The new build has been pushed and should be in a compose soon, there looks to be something that needs to be waived in the errata and that should be done today.

**Comment by teg** [comment]
I spoke with @msekletar from the systemd team, and he recommends (and I agree) that this should be solved by backporting https://github.com/systemd/systemd/commit/329d20db3cb02d789473b8f7e4a59526fcbf5728 (and related stuff) in the systemd package.

**Comment by teg** [comment]
I did a systemd scratch build with the proposed fix: http://brew-task-repos.usersys.redhat.com/repos/scratch/tgunders/systemd/239/40.el8/systemd-239-40.el8-scratch.repo

**Comment by teg** [comment]
I built an edge commit with the systemd scratch-build, and it appears to work for me as expected. Thanks @gicmo for the suggestion!

**Comment by larskarlitski** [comment]
> I built an edge commit with the systemd scratch-build, and it appears to work for me as expected. Thanks @gicmo for the suggestion!

I have verified again that it works with your scratch build and @gicmo's scripts. Thanks!

**Comment by henrywang** [comment]
I added @teg's repo into osbuild-composer sources, and ostree image building and installation works as expected.
```
systemd-libs-239-40.el8.x86_64
systemd-udev-239-40.el8.x86_64
clevis-systemd-13-3.el8.x86_64
systemd-pam-239-40.el8.x86_64
systemd-239-40.el8.x86_64
```
```
greenboot-rpm-ostree-grub2-0.11-1.el8.x86_64
greenboot-status-0.11-1.el8.x86_64
greenboot-0.11-1.el8.x86_64
greenboot-grub2-0.11-1.el8.x86_64
greenboot-reboot-0.11-1.el8.x86_64
```
```
[admin@ostree-guest ~]$ sudo journalctl -b -0 \
>     -u boot-complete.target \
>     -u greenboot \
>     -u greenboot-healthcheck \
>     -u greenboot-rpm-ostree-grub2-check-fallback \
>     -u greenboot-grub2-set-counter \
>     -u greenboot-grub2-set-success \
>     -u greenboot-status \
>     -u redboot \
>     -u redboot-auto-reboot \
>     -u redboot.target
-- Logs begin at Tue 2020-08-25 03:33:33 UTC, end at Tue 2020-08-25 05:09:16 UTC. --
Aug 25 03:33:43 localhost.localdomain systemd[1]: Starting Check for fallback boot...
Aug 25 03:33:43 localhost.localdomain systemd[1]: Started Check for fallback boot.
Aug 25 03:33:43 localhost.localdomain systemd[1]: Starting greenboot Health Checks Runner...
Aug 25 03:33:43 localhost.localdomain greenboot[747]: Running Required Health Check Scripts...
Aug 25 03:33:44 localhost.localdomain 00_required_scripts_start.sh[752]: Running greenboot Required Health Check >
Aug 25 03:33:44 localhost.localdomain greenboot[747]: Script '00_required_scripts_start.sh' SUCCESS
Aug 25 03:33:44 localhost.localdomain greenboot[747]: Running Wanted Health Check Scripts...
Aug 25 03:33:44 localhost.localdomain 00_wanted_scripts_start.sh[759]: Running greenboot Wanted Health Check Scri>
Aug 25 03:33:44 localhost.localdomain greenboot[747]: Script '00_wanted_scripts_start.sh' SUCCESS
Aug 25 03:33:44 localhost.localdomain systemd[1]: Started greenboot Health Checks Runner.
Aug 25 03:33:44 localhost.localdomain systemd[1]: Reached target Boot Completion Check.
Aug 25 03:33:44 localhost.localdomain systemd[1]: Starting Mark boot as successful in grubenv...
Aug 25 03:33:44 localhost.localdomain systemd[1]: Starting greenboot MotD Generator...
Aug 25 03:33:44 localhost.localdomain systemd[1]: Started Mark boot as successful in grubenv.
Aug 25 03:33:44 localhost.localdomain greenboot-status[770]: Boot Status is GREEN - Health Check SUCCESS
Aug 25 03:33:44 localhost.localdomain systemd[1]: Started greenboot MotD Generator.
[admin@ostree-guest ~]$ sudo grub2-editenv list
kernelopts=root=UUID=d08945e7-fe89-4460-b813-e31464df48f1 ro net.ifnames=0 modprobe.blacklist=vc4 crashkernel=auto console=ttyS0,115200
boot_success=1
```

**Comment by henrywang** [comment]
**Install `greenboot-failing-unit-1.0-1.el8.noarch` with rpm-ostree and reboot**

1. report `[FAILED] Failed to start greenboot Health Checks Runner`, and reboot
2. report `[FAILED] Failed to start greenboot Health Checks Runner`, and reboot
3. report `[FAILED] Failed to start greenboot Health Checks Runner`, and reboot
4. rollback to `good commit`. Log of `greenboot-rpm-ostree-grub2-check-fallback` shows a rollback happened.

```
[admin@ostree-guest ~]$ sudo rpm-ostree status
State: idle
Deployments:
* ostree://rhel-edge:rhel/8/x86_64/edge
                 Timestamp: 2020-08-25T03:32:00Z
                    Commit: 927136447c9e08106aadb0d6c7000f266783f36cc4e3f4a28bfecf4abd13ac9e

  ostree://rhel-edge:rhel/8/x86_64/edge
                 Timestamp: 2020-08-25T03:32:00Z
                BaseCommit: 927136447c9e08106aadb0d6c7000f266783f36cc4e3f4a28bfecf4abd13ac9e
             LocalPackages: greenboot-failing-unit-1.0-1.el8.noarch
```
```
[admin@ostree-guest ~]$ systemctl status greenboot-rpm-ostree-grub2-check-fallback
● greenboot-rpm-ostree-grub2-check-fallback.service - Check for fallback boot
   Loaded: loaded (/usr/lib/systemd/system/greenboot-rpm-ostree-grub2-check-fallback.service; enabled; vendor preset: disabled)
   Active: active (exited) since Tue 2020-08-25 05:20:23 UTC; 4min 2s ago
  Process: 734 ExecStart=/usr/libexec/greenboot/greenboot-rpm-ostree-grub2-check-fallback (code=exited, status=0/SUCCESS)
 Main PID: 734 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 23500)
   Memory: 0B
   CGroup: /system.slice/greenboot-rpm-ostree-grub2-check-fallback.service

Aug 25 05:20:14 localhost.localdomain systemd[1]: Starting Check for fallback boot...
Aug 25 05:20:14 localhost.localdomain greenboot-rpm-ostree-grub2-check-fallback[734]: Specifying boot ID or boot offset has no effect, no persistent journal was found.
Aug 25 05:20:17 localhost.localdomain greenboot-rpm-ostree-grub2-check-fallback[734]: Moving '927136447c9e08106aadb0d6c7000f266783f36cc4e3f4a28bfecf4abd13ac9e.0' to be first deployment
Aug 25 05:20:17 localhost.localdomain greenboot-rpm-ostree-grub2-check-fallback[734]: Transaction complete; bootconfig swap: no; deployment count change: 0
Aug 25 05:20:23 localhost.localdomain greenboot-rpm-ostree-grub2-check-fallback[734]: Run "systemctl reboot" to start a reboot
Aug 25 05:20:23 localhost.localdomain greenboot-rpm-ostree-grub2-check-fallback[734]: FALLBACK BOOT DETECTED! Default rpm-ostree deployment has been rolled back.
Aug 25 05:20:23 localhost.localdomain systemd[1]: Started Check for fallback boot.
```
```
[admin@ostree-guest ~]$ sudo journalctl -b -0 \
>     -u boot-complete.target \
>     -u greenboot \
>     -u greenboot-healthcheck \
>     -u greenboot-rpm-ostree-grub2-check-fallback \
>     -u greenboot-grub2-set-counter \
>     -u greenboot-grub2-set-success \
>     -u greenboot-status \
>     -u redboot \
>     -u redboot-auto-reboot \
>     -u redboot.target
-- Logs begin at Tue 2020-08-25 05:20:05 UTC, end at Tue 2020-08-25 05:26:01 UTC. --
Aug 25 05:20:14 localhost.localdomain systemd[1]: Starting Check for fallback boot...
Aug 25 05:20:14 localhost.localdomain greenboot-rpm-ostree-grub2-check-fallback[734]: Specifying boot ID or boot offset has no effect, no persistent journal was found.
Aug 25 05:20:17 localhost.localdomain greenboot-rpm-ostree-grub2-check-fallback[734]: Moving '927136447c9e08106aadb0d6c7000f266783f36cc4e3f4a28bfecf4abd13ac9e.0' to be first deployment
Aug 25 05:20:17 localhost.localdomain greenboot-rpm-ostree-grub2-check-fallback[734]: Transaction complete; bootconfig swap: no; deployment count change: 0
Aug 25 05:20:23 localhost.localdomain greenboot-rpm-ostree-grub2-check-fallback[734]: Run "systemctl reboot" to start a reboot
Aug 25 05:20:23 localhost.localdomain greenboot-rpm-ostree-grub2-check-fallback[734]: FALLBACK BOOT DETECTED! Default rpm-ostree deployment has been rolled back.
Aug 25 05:20:23 localhost.localdomain systemd[1]: Started Check for fallback boot.
Aug 25 05:20:23 localhost.localdomain systemd[1]: Starting greenboot Health Checks Runner...
Aug 25 05:20:23 localhost.localdomain greenboot[812]: Running Required Health Check Scripts...
Aug 25 05:20:23 localhost.localdomain 00_required_scripts_start.sh[819]: Running greenboot Required Health Check Scripts
Aug 25 05:20:23 localhost.localdomain greenboot[812]: Script '00_required_scripts_start.sh' SUCCESS
Aug 25 05:20:23 localhost.localdomain greenboot[812]: Running Wanted Health Check Scripts...
Aug 25 05:20:23 localhost.localdomain 00_wanted_scripts_start.sh[832]: Running greenboot Wanted Health Check Scripts
Aug 25 05:20:23 localhost.localdomain greenboot[812]: Script '00_wanted_scripts_start.sh' SUCCESS
Aug 25 05:20:23 localhost.localdomain systemd[1]: Started greenboot Health Checks Runner.
Aug 25 05:20:23 localhost.localdomain systemd[1]: Reached target Boot Completion Check.
Aug 25 05:20:23 localhost.localdomain systemd[1]: Starting Mark boot as successful in grubenv...
Aug 25 05:20:24 localhost.localdomain systemd[1]: Starting greenboot MotD Generator...
Aug 25 05:20:24 localhost.localdomain systemd[1]: Started Mark boot as successful in grubenv.
Aug 25 05:20:24 localhost.localdomain greenboot-status[852]: Boot Status is GREEN - Health Check SUCCESS
Aug 25 05:20:24 localhost.localdomain greenboot-status[852]: FALLBACK BOOT DETECTED! Default rpm-ostree deployment has been rolled back.
Aug 25 05:20:24 localhost.localdomain systemd[1]: Started greenboot MotD Generator.
```
```
[admin@ostree-guest ~]$ sudo grub2-editenv list
kernelopts=root=UUID=d08945e7-fe89-4460-b813-e31464df48f1 ro net.ifnames=0 modprobe.blacklist=vc4 crashkernel=auto console=ttyS0,115200
boot_success=1
```
```
[admin@ostree-guest ~]$ sudo systemctl status greenboot-grub2-set-success.service
● greenboot-grub2-set-success.service - Mark boot as successful in grubenv
   Loaded: loaded (/usr/lib/systemd/system/greenboot-grub2-set-success.service; enabled; vendor preset: disabled)
   Active: active (exited) since Tue 2020-08-25 05:20:24 UTC; 7min ago
  Process: 850 ExecStart=/usr/bin/grub2-editenv - unset boot_counter (code=exited, status=0/SUCCESS)
  Process: 842 ExecStart=/usr/bin/grub2-editenv - set boot_success=1 (code=exited, status=0/SUCCESS)
 Main PID: 850 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 23500)
   Memory: 0B
   CGroup: /system.slice/greenboot-grub2-set-success.service

Aug 25 05:20:23 localhost.localdomain systemd[1]: Starting Mark boot as successful in grubenv...
Aug 25 05:20:24 localhost.localdomain systemd[1]: Started Mark boot as successful in grubenv.
```
**Reboot again -> everything works as expected**
```
[admin@ostree-guest ~]$ sudo rpm-ostree status
State: idle
Deployments:
* ostree://rhel-edge:rhel/8/x86_64/edge
                 Timestamp: 2020-08-25T03:32:00Z
                    Commit: 927136447c9e08106aadb0d6c7000f266783f36cc4e3f4a28bfecf4abd13ac9e

  ostree://rhel-edge:rhel/8/x86_64/edge
                 Timestamp: 2020-08-25T03:32:00Z
                BaseCommit: 927136447c9e08106aadb0d6c7000f266783f36cc4e3f4a28bfecf4abd13ac9e
             LocalPackages: greenboot-failing-unit-1.0-1.el8.noarch
```
```
[admin@ostree-guest ~]$ sudo grub2-editenv list
kernelopts=root=UUID=d08945e7-fe89-4460-b813-e31464df48f1 ro net.ifnames=0 modprobe.blacklist=vc4 crashkernel=auto console=ttyS0,115200
boot_success=1
boot_indeterminate=0
```

**Comment by henrywang** [comment]
Verified on nightly build `systemd-239-40.el8.x86_64` and `greenboot-0.11-1.el8.x86_64`. Save result as above. systemd and greenboot fixed issues in this PR.

**Comment by teg** [comment]
Test failure on f31 is unrelated.

**Review by teg — APPROVED** [review]

**Pull request merged**
