### PR TITLE
RHEL 9.0: Drop IA32

### PR DESCRIPTION
**Pull request by achilleas-k**
Cherry-picked from @runcom's PR (thank you Antonio).  I think it's better to isolate this change and merge it separately.

Quoting a comment from @nullr0ute that adds relevant context: https://github.com/osbuild/osbuild-composer/pull/1884/commits/c108d7d0a63ed405ab4ba33db17547ec0e1ebd0a#r787575502
> For reference, and this is perfectly fine, the reason the ia32 grub2/shim gets pulled in by default there's been a number of very bad devices that are 64bit but with 32bit firmware and those are needed to boot it and then the kernel runs 64 bit. I doubt we'll need to ever support such a device but I'm adding this comment for reference.

----

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by gicmo — DISMISSED** [review]
LGTM but what about image-info?

**Comment by achilleas-k** [comment]
Well... I need to regenerate it don't I...

**Comment by runcom** [comment]
:+1: (I'll rebase once merged my other PR)

**Comment by henrywang** [comment]
@achilleas-k Thanks for doing this!
We still has selinux issue (https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/2015029263#L3170) in this case.
And in `installer` test, we have a new error `No such file or directory: '/boot/efi/EFI/redhat/shimia32.efi'" jobId=a1ba92cd-df79-4537-82ca-76eec9179db0`. We should exclude ia32 when build boot-able ISO, I think.

**Comment by gicmo** [comment]
> @achilleas-k Thanks for doing this!
> We still has selinux issue (https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/2015029263#L3170) in this case.
> And in `installer` test, we have a new error `No such file or directory: '/boot/efi/EFI/redhat/shimia32.efi'" jobId=a1ba92cd-df79-4537-82ca-76eec9179db0`. We should exclude ia32 when build boot-able ISO, I think.

```
  Running scriptlet: osbuild-selinux-41-1.20211108gitf7bf23f.el9.noar   190/202 
2066Failed to resolve allow statement at /var/lib/selinux/targeted/tmp/modules/200/osbuild/cil:89
2067/usr/sbin/semodule:  Failed!
2068uavc:  op=load_policy lsm=selinux seqno=7 res=1  Running scriptlet: osbuild-41-1.20211108gitf7bf23f.el9.noarch         191/202 
```
Yeah the installation failed. Seems like an old version of osbuild is being used.

**Comment by achilleas-k** [comment]
Need to update repos before regenerating manifests but we're waiting on greenboot

**Comment by runcom** [comment]
LGTM can we merge this?

**Review by Gundersanne — APPROVED** [review]

**Pull request merged**
