### PR TITLE
test: Add 'kernel-rt' and kernel customization test

### PR DESCRIPTION
**Pull request by henrywang**
1.  Since kernel upgrading from 'default' to 'rt kernel' has SSH connection [issue](https://github.com/osbuild/osbuild-composer/issues/1222), 'install' kernel and 'upgrade' kernel must have 'kernel-rt' included.

2. Only RHEL 8.4 repo has 'rt kernel' repo, 'rt kernel' test will be RHEL 8.4 only

### CODE REVIEW

**Review by teg — DISMISSED** [review]

**Comment by henrywang** [comment]
@teg @dvdhrm, looks rt repo we're using now does not work with normal repo. I run `kernel-rt` test on RHEL 8.4 nightly repos, they work well.

repo list:
```
http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.4.0/compose/BaseOS/x86_64/os
http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.4.0/compose/AppStream/x86_64/os
http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.4.0/compose/RT/x86_64/os/
```

Error log:
```
2021-02-21 19:13:52,083: ostree: DNF error occured: DepsolveError: There was a problem depsolving ['python36', 'kernel-rt']: 
Problem: package kernel-rt-4.18.0-287.rt7.52.el8.x86_64 requires rt-setup, but none of the providers can be installed
- package rt-setup-2.1-2.el8.x86_64 requires tuned-profiles-realtime, but none of the providers can be installed
- conflicting requests
- nothing provides tuned = 2.15.0 needed by tuned-profiles-realtime-2.15.0-1.el8.noarch
blueprint: ostree v0.0.1
```

**Comment by dvdhrm** [comment]
@henrywang Can you elaborate what exactly the issue is? Which repositories do not work? And which work?

**Comment by teg** [comment]
The repositories used in the tests are the ones defined here: https://github.com/osbuild/osbuild-composer/blob/main/test/data/repositories/rhel-84.json. It looks to me that we are not using the most recent snapshots, and that in particular the snapshots used for the RT repositories do not match the ones AppStream and BaseOS ones. I would hope updating them should do the trick.

**Comment by henrywang** [comment]
Still has same issue:
```
[2021-03-06T12:41:29.121Z] 2021-03-06 07:41:27,387: ostree: DNF error occured: DepsolveError: There was a problem depsolving ['python36', 'kernel-rt']: 
[2021-03-06T12:41:29.122Z]  Problem: package kernel-rt-4.18.0-287.rt7.52.el8.x86_64 requires rt-setup, but none of the providers can be installed
[2021-03-06T12:41:29.122Z]   - package rt-setup-2.1-2.el8.x86_64 requires tuned-profiles-realtime, but none of the providers can be installed
[2021-03-06T12:41:29.122Z]   - conflicting requests
[2021-03-06T12:41:29.122Z]   - nothing provides tuned = 2.15.0 needed by tuned-profiles-realtime-2.15.0-1.el8.noarch
[2021-03-06T12:41:29.122Z] blueprint: ostree v0.0.1
```

**Comment by teg** [comment]
@henrywang I pushed a commit to update the snapshots, as I wasn't sure if your most recent comment were with our without updated snapshots.

**Comment by henrywang** [comment]
> @henrywang I pushed a commit to update the snapshots, as I wasn't sure if your most recent comment were with our without updated snapshots.

SUPER! Thanks @teg

**Comment by henrywang** [comment]
@ondrejbudai, the mock build failed [here](https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/PR-1243/5/pipeline). Could you please take a look if you have time? Thanks.

**Comment by teg** [comment]
I rebased. I think the mock config had to be changed recently. 🤞

**Comment by henrywang** [comment]
@teg, Thank you! All ostree tests are green.

**Review by teg — APPROVED** [review]
Thanks for this @henrywang!

**Pull request merged**
