### PR TITLE
rhel86/90: change isolevel of image-installer to 3

### PR DESCRIPTION
**Pull request by ondrejbudai**
So it can contain payload bigger than 4GiB.

Related: rhbz#2056451
Signed-off-by: Ondřej Budai <ondrej@budai.cz>

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by gicmo — DISMISSED** [review]
❤️

**Review by atodorov — APPROVED** [review]
qa_ack+

**Review by gicmo — APPROVED** [review]
❤️ thanks!

**Comment by ondrejbudai** [comment]
Had to disable the test on non-x86 architectures, `Workstation` is only available there.

**Review by gicmo — APPROVED** [review]
👍

**Comment by teg** [comment]
CI green except for the expected CS9 koji test.

**Pull request merged**
