### PR TITLE
update RHEL8.2 repo to a new one (the old one is gone)

### PR DESCRIPTION
**Pull request by msehnout**

### CODE REVIEW

**Comment by ondrejbudai** [comment]
What about using `http://download-ipv4.eng.brq.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.2.0/`?

**Comment by msehnout** [comment]
> What about using `http://download-ipv4.eng.brq.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.2.0/`?

That was my first idea as well, but I think we don't like repositories that change content which would be the case for this one.

**Comment by ondrejbudai** [comment]
As it's only nightly repository and we are using it only for development, I don't care using changing repository. :)

**Comment by msehnout** [comment]
> As it's only nightly repository and we are using it only for development, I don't care using changing repository. :)

You are probably right. As opposed to Fedora, we don't have any test that would compare output images with known image-info, so it should be fine even though it changes.

@teg WDYT?

**Comment by larskarlitski** [comment]
@teg made overriding repositories from the file system possible as part of #186: https://github.com/osbuild/osbuild-composer/pull/186/commits/32c6a40dd8219fe13e993c86b7f1cfdf46319256

He also changed it to the latest nightly (the symlink). I think we don't need this one.

Sorry!

**Pull request closed without merging**
