### PR TITLE
test/cases: add f32 and rhel82 tests for x86_64

### LINKED ISSUE #544: Need image test cases for Fedora 32
Fedora 32 releases next week (2020-04-28) and we need to generate test cases for the osbuild-composer image tests.

### PR DESCRIPTION
**Pull request by teg**
Generated with

$ sudo ./tools/test-case-generators/generate-test-cases --distro fedora-32 --arch x86_64 --store .osbuild/ --output test/cases/

Fixes #544.

Signed-off-by: Tom Gundersen <teg@jklm.no>

### CODE REVIEW

**Comment by major** [comment]
@teg Oh that's a fancy command. Can we add that one in the docs or readme somewhere?

**Comment by teg** [comment]
> @teg Oh that's a fancy command. Can we add that one in the docs or readme somewhere?

Will do!

**Comment by teg** [comment]
> Shouldn't we wait for the release? This still has the development repo URLs.

Good point! Updated the URL. Should be good to go now. Also added RHEL82 at the same time.

**Comment by teg** [comment]
The failing fedora31_base test is unrelated, as these new tests do not affect the weldr API tests.

**Pull request merged**
