### PR TITLE
Depsolving: avoid leaking disk space

### PR DESCRIPTION
**Pull request by lavocatt**
This commit removes the ID generation for dnfRepoConfig and replaces it
with the hash of the baseURL.
Solves #2020

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by lavocatt** [comment]
This would not work yet because some requests might need an ID (the one where there is no base_url for the repos)

**Comment by thozza** [comment]
So the ID is used as an identification of the repo in log messages in case there are some errors encountered while using it. Using hash instead of a numeric value may make it impossible to identify the problematic repo. I think that at least repo name should be set to make this possible. Some information about what I'm talking about is in #1863

**Comment by ondrejbudai** [comment]
I think that this might indeed help in some cases and I agree with @thozza's concerns.

I have a feeling that I, unfortunately, omitted one fact, @lavocatt, sorry about that: The main issue with the leaking is in the internal service - brew calls us using the Koji API and we get a set of brand new baseurls each time. So the hash would be different there and thus, we still have the leaking issue.

But I'm still happy to merge this if we settle on id==name, that sounds promising - although we need to check whether all repos have names, if not, we need a fallback.

**Comment by teg** [comment]
> But I'm still happy to merge this if we settle on id==name, that sounds promising - although we need to check whether all repos have names, if not, we need a fallback.

I agree with @thozza's point about making this debuggable. I'm still a bit concerned about reusing name as id, just because we would need to enforce:
 - name always exists
 - name is unique
 - name is suitable as an id

All of these things might always be true, but if have to add fallbacks we might not gain all that much. Would it be possible to keep id's opaque but either add a set a human-readable string to be printed in the logs (in case libdnfs supports that), or just print the id to name mapping in the logs too (as suggested by @lavocatt) so we could at least find out what it means when needed.

Apart from that: would love to see this land :)

**Comment by thozza** [comment]
My understanding is that a DNF repo can have both `ID` and `name` set do different values. We currently set only `ID` and my suggestion as well as @msehnout's suggestion in the past was to set `ID` to whatever we need, but also set the repo's `name` to a human readable value and then use it in logs...

From DNF documentation about `name`: A human-readable name of the repository. Defaults to the `ID` of the repository. https://dnf.readthedocs.io/en/latest/conf_ref.html#repo-options

**Comment by teg** [comment]
> My understanding is that a DNF repo can have both `ID` and `name` set do different values. We currently set only `ID` and my suggestion as well as @msehnout's suggestion in the past was to set `ID` to whatever we need, but also set the repo's `name` to a human readable value and then use it in logs...

Ah, perfect. Sorry, I had misunderstood you in the past. That makes perfect sense then. Could you make that part of this PR @lavocatt (as otherwise the new IDs would be even harder to debug) ?

**Comment by lavocatt** [comment]
> > My understanding is that a DNF repo can have both `ID` and `name` set do different values. We currently set only `ID` and my suggestion as well as @msehnout's suggestion in the past was to set `ID` to whatever we need, but also set the repo's `name` to a human readable value and then use it in logs...
> 
> Ah, perfect. Sorry, I had misunderstood you in the past. That makes perfect sense then. Could you make that part of this PR @lavocatt (as otherwise the new IDs would be even harder to debug) ?

Of course! If I get it right, I'll keep the ID as it is in the PR and I'll add a requirement in the API to provide a human readable name for each repo. The I'll log the association name/repo to ease the debug ?

**Comment by thozza** [comment]
@lavocatt I think that `dnf-json` already logs errors if there are any. It would be just good to verify that the `name` is used by DNF in these log messages, if provided. I think that it is important just to ensure that the `name` is set every time the list of repositories is passed to `dnf-json`. I'm not sure if it makes sense to make the repo `name` mandatory parameter of the Cloud API. Personally I think that this is not necessary and we can have some reasonable fallback. Using `name` is probably more important for the on-premise use case with Weldr API and we are already setting `name` for all repo definitions that we use by default.

**Comment by teg** [comment]
I think you can set the name in the libdnf api and it will log correctly.

**Comment by lavocatt** [comment]
I am closing this one because it is no longer relevant since https://github.com/osbuild/osbuild-composer/pull/2119.

**Pull request closed without merging**
