### PR TITLE
CI: Enable ostree tests on RHEL 9.0-beta

### PR DESCRIPTION
**Pull request by achilleas-k**
List of fixes/changes:
- Remove unavailable packages that were listed in the edge installer package set.
- Fixes for `ostree.sh` to make it compatible with both RHEL 8.5 and RHEL 9.0 beta
  - Installs `python3` in blueprint instead of `python36`.
  - Remove `debug` callback from ansible checks.
  - Support the new output structure from `weldr-client` where necessary.
- ~~Add `nss-altfiles` to the edge commit package set.~~
  - Rebased on `main` after #1798 was merged.
- Add `gnome-kiosk` to the installer package sets.
- New test script based on the old `ostree-ng.sh` script that was run in 8.4.  The new script is called `ostree-ng-og.sh`.

Individual commit messages contain more details.

A note on the new test script:
The `ostree-ng` test was updated to accommodate a change in the edge-container image type (see https://github.com/osbuild/osbuild-composer/pull/1595).  RHEL 9.0-beta uses the old edge-container configuration, however RHEL 9.0 GA should eventually adopt the new container.

Copying the old `ostree-ng` test (now called `ostree-ng-og`) and running it separately is better than having several conditions in the single test script to accommodate the old behaviour and then reverting them when the changes land in RHEL 9.

-----

This pull request includes:

- [x] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by achilleas-k** [comment]
This is now ready (pending CI greenness).  It includes the `nss-altfiles` fix, which means it includes #1798.  We can delay this until the other PR is merged and rebase.  I've edited the original comment with a list of fixes in this PR.

**Review by thozza — APPROVED** [review]
Nice work!

I'm not familiar enough with OSTree to assess the testing approach. However the CI with these test passed, which is a good sign. 😄  The rest of the changes look good to me.

There is a minor issue with the image test cases and `image-info` report, related to SELinux context. I would gladly ignore it as we actually don't run image test cases with `image-info` in composer CI and I'll be regenerating all image test cases as part of #1810 anyway.

There is nothing blocking this PR from my PoV, but it would be probably good if someone knowledgeable of OSTree reviewed it as well 🙂

**Review by henrywang — APPROVED** [review]
Looks good to me. Thanks @achilleas-k!

**Review by ondrejbudai — APPROVED** [review]
Amazing work, many thanks to you!

**Pull request merged**
