### PR TITLE
RHEL-90: use XBOOTLDR partition GUID for `/boot`

### PR DESCRIPTION
**Pull request by thozza**
Use the Extended Bootloader Partition GUID for `/boot`, instead of the
Linux filesystem data GUID. This is useful for autodetection of a
partition purpose based on its GUID without reading the `/etc/fstab`
first.

Related to https://bugzilla.redhat.com/show_bug.cgi?id=2057231

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by achilleas-k — APPROVED** [review]
:+1:

**Comment by thozza** [comment]
The pending PackIt tasks are actually duplicates and result of some weird behavior from yesterday when GH had some issues. All of the pending tasks have a duplicate, which finished just fine. So they can be ignored.

**Review by gicmo — APPROVED** [review]
❤️

**Comment by thozza** [comment]
exception has been granted -> merging....

**Pull request merged**
