### PR TITLE
Pin fedora repositories in Schutzfile + override mock templates with rpmrepo snapshots

### PR DESCRIPTION
**Pull request by jrusz**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by ondrejbudai — COMMENTED** [review]
What about just doing `cat /etc/yum.repos.d/* | sudo tee -a`? Might save us a few lines.

Also, it would be great to unify the cases a bit, it's almost the same code, just the file names differ.

Btw: what about Fedora?

**Review by atodorov — DISMISSED** [review]
LGTM.

**Comment by jrusz** [comment]
@ondrejbudai I've updated it, I think it looks a bit better now, can you take another look please? 

Also I'll need to apply some `sed` magic to https://github.com/osbuild/rpmrepo/blob/main/.github/workflows/scheduled-snapshots.yml#L111 because we don't want to override the main fedora repos because they don't change. Suggestions more than welcome :sweat_smile:

**Comment by jrusz** [comment]
I forgot to remove one commit.

**Comment by jrusz** [comment]
I forgot to remove one commit.

**Review by thozza — APPROVED** [review]
LGTM

**Pull request merged**
