### PR TITLE
Schutzbot: Start building on aarch64 for RHEL/CentOS

### PR DESCRIPTION
**Pull request by atodorov**
Opening again to see if we get different results than in #1229 (a nightly repo file seems to be lurking around on the filesystem and is messing up everything).

### CODE REVIEW

**Comment by atodorov** [comment]
@teg, @ondrejbudai I had all the jobs in the pipeline reporting PASS with 2 jobs still running and taking longer than usual, then out of nowhere the pipeline seems to have been updated/restarted (IDK what happened) and now it shows only the "CS8 Base" job. 

Any idea what caused this? 

If possible I'd like to merge this PR to avoid any further delays.

**Comment by ondrejbudai** [comment]
The pod with Jenkins got redeployed to another node. This always leads to jobs in a weird state. I've restarted the job.

**Comment by ondrejbudai** [comment]
The pod with Jenkins got redeployed to another node. This always leads to jobs in a weird state. I've restarted the job.

This is why we want to migrate Jenkins to EC2. Btw, you can see that a restart happened on https://osbuildci.cloud.paas.psi.redhat.com/computer/ . Every time restart happens, Jenkins resets the numbering of agents from 0. That's why we currently have an agent with name `f34cloudbase-0`.

**Comment by atodorov** [comment]
> The pod with Jenkins got redeployed to another node. This always leads to jobs in a weird state. I've restarted the job.
> 

Thanks. 

Everything reports PASS ATM.

**Review by teg — APPROVED** [review]
Great stuff! Thanks for this @atodorov!

**Pull request merged**
