### PR TITLE
internal/cloud/gcp: use `pkg.go.dev/cloud.google.com/go` for Compute Engine

### PR DESCRIPTION
**Pull request by thozza**
The internal GCP package used `pkg.go.dev/google.golang.org/api` [1] to
interact with Compute Engine API. Modify the package to use the new and
idiomatic `pkg.go.dev/cloud.google.com/go` [2] library for interacting
with the Compute Engine API. The new library have been already used to
interact with the Cloudbuild and Storage APIs. The new library was not
used for Compute Engine since the beginning, because at that time, it
didn't support Compute Engine.

Update go.mod and vendored packages.

[1] https://github.com/googleapis/google-api-go-client
[2] https://github.com/googleapis/google-cloud-go

Signed-off-by: Tomas Hozza <thozza@redhat.com>

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by ondrejbudai — COMMENTED** [review]
Awesome! I tried to do the exact thing several months ago but got hit by some blockers. :)

**Comment by thozza** [comment]
> Awesome! I tried to do the exact thing several months ago but got hit by some blockers. :)

I started implementing the "new" way of importing GCE images to GCP and did it using the new library so I decided to clean up the internal package and unify on a single upstream library for GCP. I'll see how long it will take to update the Fedora package 😕

**Comment by thozza** [comment]
OK, so this should be good to go in a ~week, once the following updates get into stable:

- https://bodhi.fedoraproject.org/updates/FEDORA-2022-cf6d196f3b
- https://bodhi.fedoraproject.org/updates/FEDORA-2022-d1c27c3242

**Review by achilleas-k — APPROVED** [review]
LGTM!

Are the packages still not available?

**Comment by thozza** [comment]
> Are the packages still not available?

If you mean the Fedora packages of Google Cloud Go SDK, they are already in stable repositories of all currently supported Fedora releases.

**Pull request merged**
