### PR TITLE
WIP: Api_tests: instancecheck with cloudapi's account

### PR DESCRIPTION
**Pull request by lavocatt**
Doe not give a key to the image but instead use the one image's account
are parametrized with.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by Gundersanne — COMMENTED** [review]
I think we should address https://github.com/osbuild/osbuild-composer/issues/1574#issuecomment-889280424 before doing this. I'm not entirely sure what's the way forward here. We either need to allow setting a password and force that if 'wheel' was added, or we need to allow passwordless sudo.

Also, PRs which are WIP [can be marked as draft ](https://github.blog/2019-02-14-introducing-draft-pull-requests/)
image

**Comment by ondrejbudai** [comment]
What's the status of this PR?

**Comment by ondrejbudai** [comment]
It seems to me that GCP and Azure are still missing tests for user customization in `api.sh`. Does anyone want to continue with this effort, @Gundersanne are @lavocatt, or are you busy doing other stuff? I'm fine with closing this one for now and returning to it later. :)

**Comment by Gundersanne** [comment]
@ondrejbudai afaik this also needs a think about passwordless sudo, users who are added to the wheel group don't have it while the default user usually has. Happy to have it closed for now but will leave it up to Thomas.

**Comment by lavocatt** [comment]
Closing this PR is fine for me too.

**Pull request closed without merging**
