### PR TITLE
dnfjson: add repository name and URL to repo-related error messages

### PR DESCRIPTION
**Pull request by achilleas-k**
If dnf-json returns an error that is related to a repository, it uses the ID to identify the repository that caused the error.  Since IDs can't easily be mapped back to a configuration, appending the URL and name (if any) to the error message makes it easier to identify which repository failed.

Keeping the ID in the message is also useful for finding the cache directory of the repository if needed.

For reference, this is what an error message looks like when it has both a name and URL:
```
DNF error occurred: RepoError: There was a problem reading a repository: Failed to download metadata for repo '7a71592ff8a03486179a467c6416bf29e6a7ce46ffee9bc8aa703ff07c3b16ad' [baseos: https://0.0.0.0/baseos/repo]: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

### CODE REVIEW

**Review by Gundersanne — DISMISSED** [review]
Perfect, thank you! :)

**Comment by achilleas-k** [comment]
Rebased and resolved conflicts.

**Review by ondrejbudai — DISMISSED** [review]

**Review by thozza — DISMISSED** [review]
Looks good.

However, DNF uses repo `id` only if the repo `name` is not set. We could actually omit the logic of modifying the error added in this PR and instead ensure that we always set the repo `name` to a reasonable value. Basically setting the repo `name` to the same human-readable value `[name: URL]` here https://github.com/osbuild/osbuild-composer/blob/09f57b6c2f8199a0a8a9365dfb56b3e52e7a60e4/internal/dnfjson/dnfjson.go#L186

**Comment by achilleas-k** [comment]
> Looks good.
> 
> However, DNF uses repo `id` only if the repo `name` is not set. We could actually omit the logic of modifying the error added in this PR and instead ensure that we always set the repo `name` to a reasonable value. Basically setting the repo `name` to the same human-readable value `[name: URL]` here
> 
> https://github.com/osbuild/osbuild-composer/blob/09f57b6c2f8199a0a8a9365dfb56b3e52e7a60e4/internal/dnfjson/dnfjson.go#L186

I tried this.  The error always gets reported with the repo ID.

**Comment by achilleas-k** [comment]
A minimal example:
```
$ cat dnfname.py
import dnf


base = dnf.Base()
base.conf.persistdir = "/tmp/rpmpersist"
base.conf.cachedir = "/tmp/rpmcache"


repo = dnf.repo.Repo("repoid", base.conf)
repo.name = "reponame"
repo.baseurl = "https://0.0.0.0/repo"

base.repos.add(repo)
base.fill_sack(load_system_repo=False)
base.install_specs(["whatever"], reponame="repoid")
base.resolve()

$ python3 ./dnfname.py
Errors during downloading metadata for repository 'repoid':
  - Curl error (7): Couldn't connect to server for https://0.0.0.0/repo/repodata/repomd.xml [Failed to connect to 0.0.0.0 port 443: Connection refused]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dnf/repo.py", line 573, in load
    ret = self._repo.load()
  File "/usr/lib64/python3.9/site-packages/libdnf/repo.py", line 331, in load
    return _repo.Repo_load(self)
libdnf._error.Error: Failed to download metadata for repo 'repoid': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/achilleas/./dnfname.py", line 14, in <module>
    base.fill_sack(load_system_repo=False)
  File "/usr/lib/python3.9/site-packages/dnf/base.py", line 399, in fill_sack
    self._add_repo_to_sack(r)
  File "/usr/lib/python3.9/site-packages/dnf/base.py", line 139, in _add_repo_to_sack
    repo.load()
  File "/usr/lib/python3.9/site-packages/dnf/repo.py", line 580, in load
    raise dnf.exceptions.RepoError(str(e))
dnf.exceptions.RepoError: Failed to download metadata for repo 'repoid': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

The URL appears in the first exception here because it's coming from `Curl` failing to connect to the server.  In most of our cases there's no curl error so it doesn't appear.
The `repo.name` (`reponame`) doesn't show up in the error even though I set it.  This even happens if I call `install_specs()` with `reponame` instead of `repoid`.

**Review by thozza — DISMISSED** [review]

**Comment by achilleas-k** [comment]
And now fedora builds are failing because it doesn't use the vendored version of `testify` so it doesn't have the (I guess new) `assert.ErrorContains()` function.

**Review by gicmo — APPROVED** [review]
:ok:

**Pull request merged**
