### PR TITLE
Fix issues reported by Coverity

### PR DESCRIPTION
**Pull request by thozza**
More information is in each separate commit message.

### CODE REVIEW

**Review by gicmo — DISMISSED** [review]
:+1: Thanks

**Comment by thozza** [comment]
- The c9s build issue is caused by `vendor/github.com/containers/libtrust/ec_key_openssl.go:23:15: undefined: ecdsa.HashSign` and should be resolved when a [new version of the `golang` package](https://kojihub.stream.centos.org/koji/buildinfo?buildID=25450) gets to c9s repos.
- F37 failures in CI are caused by our CI using old repo snapshots and installing old `podman` but new `containers-common` which results in `crun` not being installed as a dependency.

**Review by achilleas-k — DISMISSED** [review]

**Review by ondrejbudai — DISMISSED** [review]
Nice!

**Review by achilleas-k — APPROVED** [review]

**Comment by jrusz** [comment]
Updated terraform SHA to fix Fedora-37 ostree issues and rebased on `main`

**Review by gicmo — APPROVED** [review]
👍

**Pull request merged**
