### PR TITLE
Use the latest RPMRepo snapshot for RHEL-9.0 image tests

### PR DESCRIPTION
**Pull request by thozza**
This is needed to satisfy RPM dependencies of GCP guest tools, which
will be installed on the `gce` image type.

Signed-off-by: Tomas Hozza <thozza@redhat.com>

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by ondrejbudai** [comment]
Looks good but I would prefer to land https://github.com/osbuild/osbuild-composer/pull/2196 firstly, sorry. :/

**Comment by thozza** [comment]
> Looks good but I would prefer to land #2196 firstly, sorry. :/

Actually #2196 is updating image tests ti the same RPMRepo snapshot, so this PR may not be needed at all. So much wasted computing power on so many architectures 😵  😆

**Comment by thozza** [comment]
Reopened, because #2196 will take some time until it is mergeable.

**Review by achilleas-k — APPROVED** [review]
Thanks!

**Pull request merged**
