### PR TITLE
Update Arm EC2 instance to a newer one

### PR DESCRIPTION
**Pull request by atodorov**
This one is 1 vCPU + 4GiB RAM, the older one is 2 vCPU, same RAM

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the READMEs [listed here](https://github.com/osbuild/osbuild.github.io/blob/main/readme-list)
  - [ ] submit a PR for the [osbuild.org website](https://github.com/osbuild/osbuild.github.io/) repository if this PR changed any behavior not covered by the automatically updated READMEs

### CODE REVIEW

**Comment by atodorov** [comment]
Worked everywhere except on 8.4 though https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/6592229863. 

Do we need to make the instane type conditional on the os-distro/osbuild-composer version ?

**Comment by bcl** [comment]
That failure might be unrelated? I've been seeing it fail in unrelated PR. The log is so dense I can't figure out why though.

**Comment by atodorov** [comment]
> That failure might be unrelated? I've been seeing it fail in unrelated PR. The log is so dense I can't figure out why though.

I've restarted the failing job. If it fails again I will try making the change conditional to see how that goes.

**Comment by atodorov** [comment]
> > That failure might be unrelated? I've been seeing it fail in unrelated PR. The log is so dense I can't figure out why though.
> 
> I've restarted the failing job. If it fails again I will try making the change conditional to see how that goes.

8.4 x86_64 failed again, even with the aarch conditional change included:
https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/6626256752

and I am now noticing this was x86_64 not aarch64 so it's not related. Removing the extra if condition.

**Review by jrusz — APPROVED** [review]
So this fixes an issue with aarch64 aws machines? If so then LGTM. However the other unrelated failures are not looking so good :/

**Comment by atodorov** [comment]
Just FTR another timeout failure on 8.4-ga-x86_64: https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/6628855020

Will retest with a modified container for cloud-image-val where OpenTofy has been reverted back to Terraform.

**Comment by atodorov** [comment]
> Just FTR another timeout failure on 8.4-ga-x86_64: https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/6628855020
> 
> Will retest with a modified container for cloud-image-val where OpenTofu has been reverted back to Terraform, see [osbuild/cloud-image-val#314](https://github.com/osbuild/cloud-image-val/pull/314)


Even with this change 8.4-ga-x86_64 timedout with the same error:
https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/6646353712. 

In the next push I will remove the workaround commit for cloud-image-val and disable this test job.

**Review by jrusz — APPROVED** [review]
LGTM, the failing upgrade test should be resolved by https://github.com/osbuild/osbuild-composer/pull/4085 ... Let's get this merged and then I'll rebase and we should get a green CI again :)

**Pull request merged**
