### PR TITLE
Add 9.1 alias & 8.7 test repositories

### PR DESCRIPTION
**Pull request by ondrejbudai**
I would like to start releasing osbuild-composer into 8.7 and 9.1. For this, we need at least a minimal 8.7 and 9.1 support. This means:

- having a distro alias in the registry
- adding repositories
- adding repository overrides and initializing them in `provision.sh`

cc @ochosi 

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by ochosi — DISMISSED** [review]
LGTM!

**Comment by gicmo** [comment]
I like this, but on my RHEL-9.0-beta alias PR @thozza requested test manifests. I think we should have a clear policy on this.

**Comment by thozza** [comment]
> I like this, but on my RHEL-9.0-beta alias PR @thozza requested test manifests. I think we should have a clear policy on this.

Yes, at least manifests should be generated due to #2350, in short, every combination of distro x arch x image type should be covered by a manifest test at least. This should / will be eventually enforced by a CI test.

**Comment by ondrejbudai** [comment]
I generated all the testcases (without image-info)

**Pull request merged**
