### PR TITLE
weldr/api: indicate preloading progress in the log

### PR DESCRIPTION
**Pull request by schuellerf**
With this you can see if the preloading is already finished or not

### CODE REVIEW

**Comment by bcl** [comment]
I'm not understanding what additional info this adds. It already prints when it is done, and when I'm looking at the logs I don't care how many there are, just whether or not the one I'm interested in has failed to load the metadata.

**Comment by schuellerf** [comment]
For the service to be up and running and responsive they should _all_ be loaded, right?
The current logs didn't indicate if it's still busy preloading.
If this doesn't provide any value also for running the service to check if the startup is very slow or still not fully done, we can as well drop this

**Review by croissanne — COMMENTED** [review]
I'm also not sure what this contributes. I don't think the preload is technically required, it just makes it slightly faster when depsolving as it would have fetched the metadata.

**Comment by schuellerf** [comment]
Hmm - it's used with the getting started "service" mode but you are right it's not aws 🤔

**Pull request closed without merging**
