### PR TITLE
simplified-installer: add a test to mimic usb installation

### PR DESCRIPTION
**Pull request by runcom**
Turns out we've unfortunately broken USB installation with the new growfs service dealing with LVM in simplified installer - this test makes sure we test that by mimicking an USB being plugged in during installation (essentially having a new drive plugged into the VM). This test should just fail (get stuck) until we fix this in coreos-installer-dracut.

- [ ] Requires snapshot update https://github.com/osbuild/osbuild-composer/pull/3193

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by runcom** [comment]
cc @henrywang @7flying

**Comment by henrywang** [comment]
Test passed in PR https://github.com/coreos/coreos-installer-dracut/pull/18

**Comment by runcom** [comment]
> Test passed in PR [coreos/coreos-installer-dracut#18](https://github.com/coreos/coreos-installer-dracut/pull/18)

perfect, we need to rebuild coreos-installer to include our updated code and land that into nightlies too before proceeding here

**Comment by sarmahaj** [comment]
> Test passed in PR [coreos/coreos-installer-dracut#18](https://github.com/coreos/coreos-installer-dracut/pull/18)

Thats great! Thanks @runcom @henrywang

**Comment by yih-redhat** [comment]
I restarted the CI job, will check result later.

**Comment by yih-redhat** [comment]
Failed at this step, time out when provisioning edge vm with additional drive path. Will take a look of it.

greenprint "💿 Install ostree image via installer(ISO) on UEFI VM"
sudo virt-install  --name="${IMAGE_KEY}-usb"\
                   --disk path="${LIBVIRT_IMAGE_PATH}",format=qcow2 \
                   --disk path="${LIBVIRT_FAKE_USB_PATH}",format=qcow2 \
                   
            
Error message:
Creating domain...                                          |    0 B  00:00     
Domain is still running. Installation may be in progress.
Waiting 15 minutes for the installation to complete.
Installation has exceeded specified time limit. Exiting application.

**Comment by yih-redhat** [comment]
I tried it manually in my desktop, the vm installation hung there, and there is no output in the vm console.

@runcom Maybe it is because the latest coreos-installer package does not have this PR https://github.com/coreos/coreos-installer-dracut/pull/18? 

[root@yih-rhel91 osbuild-composer]# sudo virt-install  --name=add-usb --disk path="${LIBVIRT_IMAGE_PATH}",format=qcow2 --disk path="${LIBVIRT_FAKE_USB_PATH}",format=qcow2 --ram 3072 --vcpus 2 --network network=integration,mac=34:49:22:B0:83:32 --os-type linux --os-variant ${OS_VARIANT} --cdrom /var/lib/libvirt/images/108028fa-0bdc-400f-9b30-fc75919fe727-simplified-installer.iso --boot uefi,loader_ro=yes,loader_type=pflash,nvram_template=/usr/share/edk2/ovmf/OVMF_VARS.fd,loader_secure=no --nographics --noautoconsole --wait=15 --noreboot
WARNING  --os-type is deprecated and does nothing. Please stop using it.

Starting install...
Creating domain...                                                                                               |    0 B  00:00:00     

Domain is still running. Installation may be in progress.
Waiting 15 minutes for the installation to complete.
Installation has exceeded specified time limit. Exiting application.

**Comment by runcom** [comment]
Yes we need to rebuild coreos-installer

**Comment by yih-redhat** [comment]
> Yes we need to rebuild coreos-installer

Thank you, do you have plan when to rebuild it? :)

**Comment by runcom** [comment]
> Thank you, do you have plan when to rebuild it? :)

this week hopefully :)

**Comment by yih-redhat** [comment]
Will trigger test now, as https://bugzilla.redhat.com/show_bug.cgi?id=2144801 is ready for verify.

**Comment by yih-redhat** [comment]
We should be able to test this PR now, as coreos-installer fixed the usb issue, and rhel8.8/9.2 runners are enabled.

@runcom Since this PR was created long time ago, can you please help to rebase it? We need to run on 8.8/9.2 runners and  use the new repo snapshot.

**Pull request closed without merging**
