### PR TITLE
🧹 Clean up cruft from old jobs

### PR DESCRIPTION
**Pull request by major**
Delete any leftover `/tmp` files from previous test runs and turn
on the `cleanup_composer_directories` option to clean up the
osbuild-composer directories during the time the services are stopped.

Signed-off-by: Major Hayden <major@redhat.com>

### CODE REVIEW

**Comment by major** [comment]
schutzbot_fedora31_base schutzbot_fedora31_image

**Comment by major** [comment]
schutzbot_fedora31_base

**Comment by ondrejbudai** [comment]
schutzbot_fedora31_base
schutzbot_fedora32_image

**Comment by ondrejbudai** [comment]
schutzbot_fedora31_base

**Comment by ondrejbudai** [comment]
schutzbot_fedora32_image

**Comment by ondrejbudai** [comment]
`Failed to restart systemd-journald.service: Access denied`

I think this needs rebase because of the `sudo` changes?

**Pull request closed without merging**
