### PR TITLE
kojiapi: add simple test for the /status API

### PR DESCRIPTION
**Pull request by larskarlitski**
Add a simple unit test for the koji API.

This adds a Handler() method to the koji.Server struct, which made
writing the test easier. This is a direction we want to go in anyway in
the future.

### CODE REVIEW

**Review by teg — APPROVED** [review]
Thanks!

**Review by ondrejbudai — APPROVED** [review]
Thanks!

**Review by atodorov — APPROVED** [review]
LGTM

**Comment by larskarlitski** [comment]
Thanks for the reviews! Only the F32 Base test is failing, due to https://github.com/osbuild/osbuild-composer/issues/1031. This PR only adds a unit test.

**Pull request merged**
