### PR TITLE
distro/rhel8: add RHEL for Edge

### PR DESCRIPTION
**Pull request by teg**
This replaces #727, I'm taking it back over again ;)

Rebased on top of master, otherwise the commit is unchanged.

### CODE REVIEW

**Comment by nullr0ute** [comment]
What's the issue with usbguard?

**Comment by teg** [comment]
> What's the issue with usbguard?

It ships a custom SELinux policy, which `osbuild` did not handle correctly. We were ok with no SELinux at all, or if the host and target policies match, but not when they don't.

Fixed by: https://github.com/osbuild/osbuild/pull/442

**Comment by teg** [comment]
This allows building a RHEL for Edge commit and installing it using anaconda. A guide for how oto do that can be found here [https://www.osbuild.org/news/2020-06-01-how-to-ostree-anaconda.html]









I'm using Anaconda from F32, as the one from RHEL8.3 nightlies was throwing errors.

**Comment by teg** [comment]
I added some test cases and retested manually against the most recent osbuild release. `usbguard-daemon` is labelled correctly, and `inputhash` is set. This is ready to be merged unless Schutzbot objects.

**Comment by gicmo** [comment]
I am wondering how stable the `commit id` really is:

Using the demo repo I did two runs:

```
Pipeline for ostree commit is done
        ref: fedora/x86_64/osbuild-demo
  output id: 2956b6b441b514c6b78e50cc2b71082e5f74980a6cdda5fd1534374eff078da2
  commit id: 1fe7b34e33247d5522dfd076535f5a226899f7563d06fe45a1e39f9dc5797275
```

```
Pipeline for ostree commit is done
        ref: fedora/x86_64/osbuild-demo
  output id: 2956b6b441b514c6b78e50cc2b71082e5f74980a6cdda5fd1534374eff078da2
  commit id: b8355287cf33780a3f0b5237bfa3a100b3c33d8c5bd2ca56dc5b8ee6f6cfdaa5
```

**Comment by major** [comment]
CI failures look unrelated. I just re-ran the Schutzbot job.

**Comment by teg** [comment]
> I am wondering how stable the `commit id` really is:

Good point, this might bite us, even if this test run happened to pass. I reworked it to include the inputhash instead. As you suggested. This change only affects the tests, so now this is really ready to be merged.

**Pull request merged**
