### PR TITLE
add usb test in edge-simplified-installer

### PR DESCRIPTION
**Pull request by yih-redhat**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Comment by yih-redhat** [comment]
This PR needs new coreos-installer rpm which was created on 12/09/2022 and the current snapshot is 20221115.
May need to wait https://github.com/osbuild/osbuild-composer/pull/3200 merged to update the repo snapshot.

**Comment by yih-redhat** [comment]
@runcom in https://github.com/osbuild/osbuild-composer/pull/3065, you created a new case, includes new image, new vm. And in this pr I just added an usb disk to existing case. Do you think it's ok?

**Comment by runcom** [comment]
> @runcom in #3065, you created a new case, includes new image, new vm. And in this pr I just added an usb disk to existing case. Do you think it's ok?

yeah, as long as we have other cases without usb it's good :+1:

**Comment by yih-redhat** [comment]
included in https://github.com/osbuild/osbuild-composer/pull/3302 , closing this pull request.

**Pull request closed without merging**
