### PR TITLE
Add coverage notes and link to Coveralls in docs

### PR DESCRIPTION
**Pull request by atodorov**
just makes it easier to navigate to the coverage report

### CODE REVIEW

**Comment by larskarlitski** [comment]
I hate those, personally. I won't block this if more people like them that don't, of course.

Sorry.

**Comment by ondrejbudai** [comment]
I have no strong feelings, one way or the other.

**Comment by teg** [comment]
> I hate those, personally.

How come? My instinct is to like anything that's shiny and you can click on, but maybe I'm missing something? Would also be a nice little nudge to motivate people to work on unit tests :)

**Comment by dvdhrm** [comment]
> > I hate those, personally.
> 
> How come? My instinct is to like anything that's shiny and you can click on, but maybe I'm missing something. Would also be a nice little nudge to motivate people to work on unit tests :)

* It makes `README.md` much worse to read in a terminal / editor.
* It usually is placed at the top of `README.md`, completely out of place. This is the first line anyone sees in the official documentation when interacting with the project. Is that what we want to use that prime space for?
* For nearly all of the people stumbling over `README.md` it carries no value. (I am not saying that this is the majority of **views**, but merely the majority of **viewers**)
* It looks like advertising. Shiny, colorful, attention-magnet.

I honestly never understood these badges. Why is that information displayed at this location? What is it trying to achieve? Am I supposed to just stumble over it from time to time and wonder "ohh, I should improve coverage, these numbers look bad"? Or am I meant to push any changes I do to master before I can check on the front page of the project how the coverage numbers changed?

What I personally get out of these badges is a link to the tool.

But maybe that's just me. I don't mind much either. I just don't get it.

**Comment by larskarlitski** [comment]
What David said. (Except the advertisement thing, I don't get that one.)

In addition, I dislike that it ties a file in the repository the a specific location and branch on GitHub. If I make a fork, the badge still points to the master branch on osbuild/osbuild-composer. If a increase coverage on a branch, the badge doesn't update automatically.

It's mostly taste though.

**Comment by teg** [comment]
> In addition, I dislike that it ties a file in the repository the a specific location and branch on GitHub.

Ok, I'm convinced, let's not do this. It is easy enough to get to the coverage reports by looking at the CI runs for a given branch/PR.

**Comment by atodorov** [comment]
Based on above comments I've removed the badges and added a short section in test/README.md to point to coveralls.

> It is easy enough to get to the coverage reports by looking at the CI runs for a given branch/PR.

We should also make Coveralls report status updates as comments & checks on pull requests. I believe this is a setting somewhere in their UI.

**Comment by teg** [comment]
Looks good to me as well. But no idea what is up with CI on this. Surely unrelated.

**Comment by larskarlitski** [comment]
> Looks good to me as well. But no idea what is up with CI on this. Surely unrelated.

re-running.

**Pull request merged**
