### PR TITLE
templates/packer: switch to fedora-40

### PR DESCRIPTION
**Pull request by croissanne**
Fedora 38 is EOL, and packit no longer builds rpms for it.

### CODE REVIEW

**Review by schuellerf — CHANGES_REQUESTED** [review]
should we also remove this from `Schutzfile`, `tools/check-runners`  and 
`internal/cloudapi/v2/compose_test.go`?
Would this save some time during the checks?

also in `test/cases/minimal-raw.sh` it seems odd that `fedora-37` maps to `fedora37` and 38 to `fedora-unknown` 🤔

**Comment by croissanne** [comment]
> should we also remove this from `Schutzfile`, `tools/check-runners` and `internal/cloudapi/v2/compose_test.go`? Would this save some time during the checks?
> 
> also in `test/cases/minimal-raw.sh` it seems odd that `fedora-37` maps to `fedora37` and `fedora-38` to `fedora-unknown` 🤔

yea, I just wanted to fix the packer job first >.> Also yea that's not great in the minimal raw test ._.

**Review by schuellerf — APPROVED** [review]

**Comment by croissanne** [comment]
Ugh ok so ansible on fedora 39 is broken. I might try fedora 40.

**Review by thozza — APPROVED** [review]
Looks good.

**Pull request merged**
