### PR TITLE
enable cloud-init in RHEL 9 qcow2 images

### PR DESCRIPTION
**Pull request by ondrejbudai**
RHEL qcow2 images didn't have cloud-init enabled, this PR fixes that. Also, the libvirt test explicitly enabled cloud-init in a blueprint. This behavior was removed so an image without enabled cloud-init will fail the test suite from now on.

Fixes COMPOSER-920
Fixes rhbz#1960309

This pull request includes:

- [x] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by msehnout — DISMISSED** [review]
Looks fine! :+1:

**Comment by ondrejbudai** [comment]
I force-pushed a new commit which also disabled libvirt tests for vhd because the vhd images are meant for Azure and we now indeed test them in Azure so there's no need to test them in libvirt anymore. If someone wants to use our images in libvirt, he or she can just use qcow2 images.

**Review by msehnout — APPROVED** [review]
Still looks good to me and I expect the test failure to be unrelated.

PSI Schutzbot fails on:
```
ERROR    internal error: unknown feature amd-sev-es
```
which is a processor feature, I hope unrelated to enabling cloud-init service.

Gitlab CI failed to provision OSTree tests:
```
cat: /home/centos/jobs/openstack/fedora-33-x86_64/1266743787/ip: No such file or directory
Host  not found in /home/centos/.ssh/known_hosts
ERROR: Job failed: exit status 1
```

**Comment by msehnout** [comment]
@ondrejbudai would you like to merge it as is?

**Comment by ondrejbudai** [comment]
Yeah, only ostree tests failed because of infra issues.

**Pull request merged**
