### PR TITLE
osbuild2: update cloud-init stage with new options

### PR DESCRIPTION
**Pull request by msehnout**
Related to: https://github.com/osbuild/osbuild/pull/866/

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by achilleas-k — COMMENTED** [review]
We had a discussion recently about doing the option validation in the `NewXStage()` constructor instead of the `MarshalJSON()` method.
https://github.com/osbuild/osbuild-composer/issues/1785

In this case, I think it would probably also save us the trouble of having a custom marshaller, since there aren't any weird union values in the schema.

**Comment by msehnout** [comment]
> We had a discussion recently about doing the option validation in the `NewXStage()` constructor instead of the `MarshalJSON()` method. #1785

Yeah, I read that one. Actually that's why I created all those `validate()` functions, so that I can call it in the `NewXStage`. Just forgot to actually call it :facepalm:

**Comment by msehnout** [comment]
@achilleas-k Please have a look again. I wasn't sure whether to leave the `validate()` calls in the MarshalJSON functions or not. Right now the constructor as well as the marshalers call the functions, but it is a lot of boilerplate code. If we are ok with removing the validation from marshalers, we can remove a lot of lines and call the validation recursively (I didn't want to call `validate()` on internal variables in all the structures, because MarshalJSON calls MarshalJSON for every internal variable and in turn it calls `validate()`)

**Comment by achilleas-k** [comment]
Looks good.  Having a nested/recursive `validate()` call that starts from the `NewStage()` is much nicer I think.  Let's clean the custom marshallers, which should also remove the need for the type aliases.  The whole thing should look much cleaner then.

**Comment by msehnout** [comment]
I agree. The PR is updated and simplified now :-)

**Review by achilleas-k — APPROVED** [review]
Looks great.  Thanks!

**Pull request merged**
