### PR TITLE
Update RHEL and Fedora test cases

### PR DESCRIPTION
**Pull request by achilleas-k**
This pull request includes:

- [x] adequate testing for the new functionality or fixed issue
- [x] adequate documentation informing people about the change

Regenerated manifests for test cases for RHEL 8.3, RHEL 8.4, Fedora 32, and Fedora 33.  Changes in osbuild affect the image info, specifically the output of `rpm --verify`.  In RHEL images, the `/etc/machine-id` file no longer appears as modified, but in Fedora images it does.  This has been causing CI failures in recent osbuild builds.

For images that haven't been updated in a while, the RT repo was also added by the test case generator.

Schutzfile changed to use current `main` for osbuild: https://github.com/osbuild/osbuild/commit/6c68e45dbe6b8e7c7a7c40eed1ff66ee4932b050

### CODE REVIEW

**Comment by achilleas-k** [comment]
Converting to draft until all changes are covered.

**Comment by achilleas-k** [comment]
This is ready but we'll have to wait for CI to make sure it's all good.  Marking as ready.

**Comment by ondrejbudai** [comment]
Ouch, this now needs a rebase. :(

**Comment by achilleas-k** [comment]
Not sure what to do with this PR.  It'll be needed if we reintroduce the [machine-id truncation](https://github.com/osbuild/osbuild/commit/59184b23a24d302eeec627a656f1acefff7d6597), which was reverted, but there might be other changes in the manifests until then.

I'm going to close it and we can reopen it (or remake it) when the time comes.

**Pull request closed without merging**
