### PR TITLE
Image test cases tooling fix & data update

### PR DESCRIPTION
**Pull request by thozza**
This pull request includes:
- Fix of a bug in `generate-test-cases` tool, which caused the blueprint customization `overrides` from `format-request-map.json` to not be properly applied and used in the resulting test case manifests.
- Removed the `subscription` customization from the `tools/test-case-generators/format-request-map.json` as it did not affect generated image test cases. Images currently can not be subscribed via Blueprint customizations, only via Cloud API, which uses `imageOptions` to modify the resulting image. Our current tooling for image test cases relies only on Blueprint customizations for image customizations and does not allow `imageOptions` to be modified. Created issue #1177 so that we don't forget to add the support to our tooling and actual test cases for RHEL image subscription in the future.
- Updated `tools/test-case-generators/repos.json` to use the latest RHEL-8.3 and RHEL-8.4 RPMrepo snapshots.
- Regenerated all image test cases affected by changes done to `tools/test-case-generators/format-request-map.json` and `tools/test-case-generators/repos.json`, namely all `rhel-8` and `rhel-84` images.

### CODE REVIEW

**Comment by thozza** [comment]
There seems to be an issue with the changes to image test cases for `rhel-84`. I'll have to investigate it...

**Comment by thozza** [comment]
I'm currently blocked on #1189 to get merged, so that I can regenerate the `rhel-84` `qcow2` image test cases...

**Comment by ondrejbudai** [comment]
#1189 is now merged, so if you can rebase this PR, we should be good to go. :)

**Comment by thozza** [comment]
Thanks! Regeneration of image test cases is in progress... I'll post an update here, once the PR is updated with the latest image test cases...

**Review by teg — APPROVED** [review]
Thanks for all the work on this!

**Pull request merged**
