### PR TITLE
Add API v1 support to projects/source route

### LINKED ISSUE #475: The source API only implements v0 even though the server advertises v1
In WELDR API v1 the source response was changed to add an id field. The osbuild-composer API currently doesn't support the id field even though the server advertises V1 support.

Which brings up a good question about API version support. Should a V1 server be expected to support both versions of an API call? Seems to me like it shouldn't need to, but this may cause problems with UI that expects support for both. We never really defined this behavior, since lorax-composer supports both.

### PR DESCRIPTION
**Pull request by bcl**
Fixes #475

### CODE REVIEW

**Comment by bcl** [comment]
ok to test

**Comment by major** [comment]
add to whitelist

**Comment by major** [comment]
ok to test

**Comment by major** [comment]
@bcl remind me to add you to the admin list tomorrow. :)

**Comment by bcl** [comment]
> Very nice! Thanks for this! I noticed some comments about missing proxy support in the store, I don't think that's urgent, but would be good to add issues for missing bits (if you didn't already).

I'll do that. It's going to be another tricky one since it's a change to the store. Created #592 for this specific case, there is also #401 for an overall proxy.

**Comment by bcl** [comment]
NOTE: These tests need to be restarted when jenkins is back in working order.

**Comment by teg** [comment]
Would love to merge this. Seems Schutzbot is still unhappy. Might be worth retrying that now as it has seen some fixes late last week.

**Comment by larskarlitski** [comment]
> Would love to merge this. Seems Schutzbot is still unhappy. Might be worth retrying that now as it has seen some fixes late last week.

No, this seems to be a valid error:
```
--- FAIL: TestSources (0.48s)
    main_test.go:220:
                Error Trace:    main_test.go:220
                                                        main_test.go:82
                Error:          Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc000093d40), Stderr:[]uint8(nil)}
                Test:           TestSources
                Messages:       Command failed: exit status 1 - { 
                                    "sources": {}, 
                                    "errors": [
                                        {
                                            "id": "UnknownSource",
                                            "msg": "osbuild-test-addon-source is not a valid source"
                                        }
                                    ]
                                }   
FAIL
```

**Comment by bcl** [comment]
Yeah, it's failing consistently enough that I don't want to push it -- but I also cannot reproduce it locally so it's kinda stuck until I think of a better way to debug it.

**Comment by bcl** [comment]
Rebased on master, failure is the composer-cli issue which is currently in updates-testing...

**Pull request merged**
