### PR TITLE
composer: seed the random number generator

### PR DESCRIPTION
**Pull request by ondrejbudai**
I thought rand in Go is auto-seeded but I was wrong, see \[1\].
This commit adds seed initialization.

\[1\]: https://golang.org/pkg/math/rand/#Seed

### CODE REVIEW

**Comment by bcl** [comment]
Where is math/rand being used? I see crypto/rand being used in several places but not math/rand -- they are different :) crypto/rand gets its numbers from getrandom or /dev/urandom and is much better than math/rand which, even with it seeded, has a higher chance of collisions between systems (unlikely with the uses of Nano but still possible if a number of systems all start at the same time).

**Comment by ondrejbudai** [comment]
I added `math/rand` here: https://github.com/osbuild/osbuild-composer/pull/1131 I guess I can seed the `Manifest()` function with `crypto/rand`...

**Comment by ondrejbudai** [comment]
I force-pushed a version with `crypto/rand`. The global `rand.Seed()` call that I had before was ugly, I think this is nicer.

**Review by teg — APPROVED** [review]
Nice! I agree with Brian, nice to use proper random seed, even if it would not really make a difference for this usecase.

**Comment by bcl** [comment]
Ha, I was looking at the wrong branch when searching for math/rand use :) Looks good to me.

**Comment by ondrejbudai** [comment]
https://github.com/osbuild/koji-osbuild/pull/54 and https://github.com/osbuild/osbuild-composer/issues/1135 appeared, otherwise we're green. :green_heart:

**Pull request merged**
