### PR TITLE
Add support for packit

### PR DESCRIPTION
**Pull request by ochosi**
This is based on the packit configuration of osbuild.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by ondrejbudai — APPROVED** [review]
Makes sense!

**Comment by msehnout** [comment]
Is there any reason to use `fedora-rawhide` instead of `fedora-all`?

**Comment by ochosi** [comment]
> Is there any reason to use `fedora-rawhide` instead of `fedora-all`?

I would just start with `rawhide` and then maybe go to pushing to dist-git there directly and then take care of `fedora-all`

**Comment by teg** [comment]
I'm all for this!

Should we also consider going full source-git to make this even better integrated? I don't know what the blockers would be.

**Comment by ochosi** [comment]
> I'm all for this!
> 
> Should we also consider going full source-git to make this even better integrated? I don't know what the blockers would be.

Funny you should mention this - I discussed this yesterday with Ondřej briefly when discussing the PR / packit. I personally don't know enough about the subject but with a few pointers I'm happy to educate myself :)

**Pull request merged**
