### PR TITLE
workflow: Update to golangci-lint v1.49.0

### LINKED ISSUE #2972: golangci-lint should be updated to 1.49.0
The version of golangci-lint used in the workflow is old, v1.30.0, and needs to be updated and the new linting error fixed.

### PR DESCRIPTION
**Pull request by bcl**
Update golangci-lint version used in the workflow. Draft for now to see what it complains about. This will fix #2972

### CODE REVIEW

**Comment by ondrejbudai** [comment]
Great! Thank you for picking this up.

**Comment by ondrejbudai** [comment]
Btw, it might be a good idea to switch to their official github action](https://golangci-lint.run/usage/install/#github-actions) since it's finally available. The benefit is that it would get autoupdated by dependabot.

**Comment by bcl** [comment]
Ah, ha! So the linter complaints are only summarized in the logs, there are no line numbers. But GitHub adds the annotations to the file tab even for files not touched by the PR so that's where you look when it fails, not at the logs.

**Review by ondrejbudai — APPROVED** [review]
Looks good, thanks!

**Review by ondrejbudai — APPROVED** [review]
Thanks! :heart_eyes:

**Pull request merged**
