### PR TITLE
Update snapshots to 20220222

### PR DESCRIPTION
**Pull request by schutzbot**
Job(s) succeeded: 116
Job(s) failed: 0
Workflow run: https://github.com/osbuild/rpmrepo/actions/runs/1883527097

### CODE REVIEW

**Comment by achilleas-k** [comment]
CS9 Koji still failing because the test is is using the 20220208 repositories (from `test/data/repositories`?)

**Comment by Gundersanne** [comment]
> CS9 Koji still failing because the test is is using the 20220208 repositories (from `test/data/repositories`?)

well this is librpm crashing on the host, so I think we can use baseos/appstream from before the crash was introduced and CRB from latest until the next snapshot run. I'll push that to this PR.

**Review by ondrejbudai — DISMISSED** [review]

**Comment by teg** [comment]
(oops, pressed a button by mistake)

**Review by achilleas-k — APPROVED** [review]
Quite the trip

**Pull request merged**
