### PR TITLE
[TEST ONLY]Image tests update

### PR DESCRIPTION
**Pull request by thozza**
Testing image-info SELinux ctx fix/workaround for #1464

### CODE REVIEW

**Comment by atodorov** [comment]
@thozza I still see failures of the test jobs that you left uncommented. What's the status here? 

Reminder that this issue is blocking a chain of about 5 PRs+tickets so we should fix it as soon as possible.

**Comment by thozza** [comment]
> @thozza I still see failures of the test jobs that you left uncommented. What's the status here?

The status is that on Fri I regenerated the ostree-based images in VMs with the changed `image-info`, but I'm getting different results than what is produced in the CI. I need to investigate the issue further and determine what is the difference in the environment what am I missing.

> Reminder that this issue is blocking a chain of about 5 PRs+tickets so we should fix it as soon as possible.

Yes, I'm aware of it. Unfortunately regenerating image test cases takes quite a lot of time, as well as CI runs, so there is quite a big workaround.

**Comment by thozza** [comment]
I hopefully resolved all the issues and regenerated test cases. If this PR passes in CI, I'll close it and open a new one with just my changes...

**Comment by thozza** [comment]
There was still a failure on `rhel-8`, but it is a different issue. I suspect that the way `setfiles` is used by `image-info` on Fedora does not work on RHEL. Mainly due to logs like this:
```
🏃🏻 Running test: rhel_8-x86_64-rhel_edge_commit-boot.json
------------------------------------------------------------------------------
=== RUN   TestImages
=== RUN   TestImages/rhel_8-x86_64-rhel_edge_commit-boot.json
=== RUN   TestImages/rhel_8-x86_64-rhel_edge_commit-boot.json/image_info
usage:  setfiles [-diIDlmnpqvFW] [-e excludedir] [-r alt_root_path] spec_file pathname...
usage:  setfiles [-diIDlmnpqvFW] [-e excludedir] [-r alt_root_path] spec_file -f filename
usage:  setfiles -s [-diIDlmnpqvFW] spec_file
usage:  setfiles -c policyfile spec_file
ostree config get core.mode --repo=/var/tmp/tmpn_5_i9dg/root/repo
ostree refs --repo=/var/tmp/tmpn_5_i9dg/root/repo
ostree rev-parse rhel/8/x86_64/edge --repo=/var/tmp/tmpn_5_i9dg/root/repo
ostree checkout --force-copy efe76c8dce80b6aed9b7f5678324043c8c39b960f8384cba15c8ea3da26f012c /var/tmp/tmpjj2mj2pf/tree --repo=/var/tmp/tmpn_5_i9dg/root/repo
    main_test.go:106: 
...
```

I'm currently investigating this further...

**Comment by thozza** [comment]
The issue is that usage of `setfiles` on RHEL-8 is different than on Fedora and in the upstream and unfortunately it does not allow passing path to binary policy using `-c`. This is completely crucial for our use case, because we need to check the SELinux context of the files in the image using the policy from the image. I filled https://bugzilla.redhat.com/show_bug.cgi?id=1973754, but this won't help with `rhel-8` and `rhel-84` testing. I have a few ideas that I could work, but I need to verify some of them first:

1. For the time when `image-info` runs `setfiles` we could bind-mount the policy file from the image to the host. `setfiles` should be consistently using a specific binary policy file present on the host, so this may workaround the limitation. The policy file should be unmounted right after the check is finished. However I have no idea if this may cause any issues on the host system.
2. Chroot to the image filesystem tree and run `setfiles` from the image (this would actually require `policycoreutils` RPM to be installed in the image, which may not be the case all the time and desired at all).
3. Patch `setfiles` for the purpose of testing RHEL-8 images in our CI.

If anyone has any other ideas, please don't hesitate to bring them up...

**Comment by atodorov** [comment]
> this won't help with `rhel-8` and `rhel-84` testing. 

FTR `rhel-84` will become 8.5 very soon so we can start testing with an updated RPM including the backport you requested in Bugzilla. 

`rhel8` will become the 8.4 GA for which we still need a workaround (or request a z-stream update ?)

**Comment by thozza** [comment]
@atodorov I added a new CLI option to `osbuild-image-tests` to ignore the `selinux/context-mismatch` part of the image-info report and enabled it for RHEL-8. Based on my preliminary testing, it works nicely as a workaround for image tests on RHEL-8.

**Comment by thozza** [comment]
Image tests passed. I created #1485 with just my changes.

**Pull request closed without merging**
